QVision: Qt's Image, Video and Computer Vision Library
PARP Research Group Universidad de Murcia
QVKeypoint Class Reference
[Image processing]
Class for image key point data-type.
#include <QVKeypoint>
Public Member Functions
QVKeypoint (const double x=0.0, const double y=0.0, const double scale=0.0, const double orientation=0.0)
Default constructor.
QVKeypoint (const QVKeypoint &other)
Copy constructor.
operator QPointF () const
Point conversion operator. Gets the location of the image feature in a QPointF object.
QPointF location () const
Gets the location of the image feature. Gets the location of the image feature in a QPointF object.
double & x ()
Horizontal coordinate of the image feature.
double x () const
Horizontal coordinate of the image feature.
double & y ()
Vertical coordinate of the image feature.
double y () const
Vertical coordinate of the image feature.
double & scale ()
Scale of the image feature.
double scale () const
Scale of the image feature.
double & orientation ()
Orientation of the image feature.
double orientation () const
Orientation of the image feature.
Detailed Description
Class for image key point data-type.
The pixel location, the scale and the orientation identify several kinds of image features. This class models these image features.
Definition at line 39 of file qvkeypoint.h.
Constructor & Destructor Documentation
QVKeypoint::QVKeypoint (const double x = 0.0, const double y = 0.0, const double scale = 0.0, const double orientation = 0.0) [inline]
Default constructor.
Creates a new keypoint location for an image feature.
Parameters:
x horizontal image coordinate for the image feature.
y vertical image coordinate for the image feature.
scale scale of the image feature.
orientation orientation of the image feature.
Definition at line 54 of file qvkeypoint.h.
QVKeypoint::QVKeypoint (const QVKeypoint & other) [inline]
Copy constructor.
Creates a new keypoint location from another.
Parameters:
x horizontal image coordinate for the image feature.
y vertical image coordinate for the image feature.
scale scale of the image feature.
orientation orientation of the image feature.
Definition at line 66 of file qvkeypoint.h.
Member Function Documentation
QVKeypoint::operator QPointF () const [inline]
Point conversion operator. Gets the location of the image feature in a QPointF object.
Definition at line 75 of file qvkeypoint.h.
QPointF QVKeypoint::location () const [inline]
Gets the location of the image feature. Gets the location of the image feature in a QPointF object.
Definition at line 79 of file qvkeypoint.h.
Referenced by operator QPointF().
double& QVKeypoint::x () [inline]
Horizontal coordinate of the image feature.
Definition at line 82 of file qvkeypoint.h.
Referenced by getSiftGPUFeatures(), and saveSIFTDescriptorsInLoweSIFTFileFormat().
double QVKeypoint::x () const [inline]
Horizontal coordinate of the image feature.
Definition at line 85 of file qvkeypoint.h.
double& QVKeypoint::y () [inline]
Vertical coordinate of the image feature.
Definition at line 88 of file qvkeypoint.h.
Referenced by getSiftGPUFeatures(), and saveSIFTDescriptorsInLoweSIFTFileFormat().
double QVKeypoint::y () const [inline]
Vertical coordinate of the image feature.
Definition at line 91 of file qvkeypoint.h.
double& QVKeypoint::scale () [inline]
Scale of the image feature.
Definition at line 94 of file qvkeypoint.h.
Referenced by getSiftGPUFeatures(), and saveSIFTDescriptorsInLoweSIFTFileFormat().
double QVKeypoint::scale () const [inline]
Scale of the image feature.
Definition at line 97 of file qvkeypoint.h.
double& QVKeypoint::orientation () [inline]
Orientation of the image feature.
Definition at line 100 of file qvkeypoint.h.
Referenced by getSiftGPUFeatures(), and saveSIFTDescriptorsInLoweSIFTFileFormat().
double QVKeypoint::orientation () const [inline]
Orientation of the image feature.
Definition at line 103 of file qvkeypoint.h.
The documentation for this class was generated from the following file:
src/qvip/qvkeypoint.h
QVision framework. PARP research group. Copyright © 2007, 2008, 2009, 2010, 2011.