QVision: Qt's Image, Video and Computer Vision Library
PARP Research Group Universidad de Murcia
QVImage< Type, Channels > Class Template Reference
[Image processing]
Image representation class for the QVision.
#include <QVImage>
Inherits QVGenericImage.
Public Member Functions
QVImage (uInt cols=1, uInt rows=1)
Default constructor.
QVImage (QVImage< uChar, 1 > const &img)
Copy constructor.
QVImage (QVImage< uChar, 3 > const &img)
Overloaded copy constructor.
QVImage (QVImage< sChar, 1 > const &img)
QVImage (QVImage< sChar, 3 > const &img)
Overloaded copy constructor.
QVImage (QVImage< uShort, 1 > const &img)
Overloaded copy constructor.
QVImage (QVImage< uShort, 3 > const &img)
Overloaded copy constructor.
QVImage (QVImage< sShort, 1 > const &img)
Overloaded copy constructor.
QVImage (QVImage< sShort, 3 > const &img)
Overloaded copy constructor.
QVImage (QVImage< uInt, 1 > const &img)
Overloaded copy constructor.
QVImage (QVImage< uInt, 3 > const &img)
Overloaded copy constructor.
QVImage (QVImage< sInt, 1 > const &img)
Overloaded copy constructor.
QVImage (QVImage< sInt, 3 > const &img)
Overloaded copy constructor.
QVImage (QVImage< sFloat, 1 > const &img)
Overloaded copy constructor.
QVImage (QVImage< sFloat, 3 > const &img)
Overloaded copy constructor.
QVImage (const QString &filename)
QVImage (QVImage< uChar, 1 > const &red, QVImage< uChar, 1 > const &green, QVImage< uChar, 1 > const &blue)
Compose copy constructor.
QVImage (QVImage< uShort, 1 > const &red, QVImage< uShort, 1 > const &green, QVImage< uShort, 1 > const &blue)
Overloaded compose copy constructor.
QVImage (QVImage< sShort, 1 > const &red, QVImage< sShort, 1 > const &green, QVImage< sShort, 1 > const &blue)
Overloaded compose copy constructor.
QVImage (QVImage< sInt, 1 > const &red, QVImage< sInt, 1 > const &green, QVImage< sInt, 1 > const &blue)
Overloaded compose copy constructor.
QVImage (QVImage< sFloat, 1 > const &red, QVImage< sFloat, 1 > const &green, QVImage< sFloat, 1 > const &blue)
Overloaded compose copy constructor.
QVImage (const QImage &qImage)
Convert constructor for QImage objects.
operator QImage () const
Converts the QVImage to a QImage object.
QVImage (const IplImage *iplImage)
Convert constructor from OpenCV image objects (IplImage).
operator IplImage * () const
Converts the QVImage to an OpenCV image object (IplImage).
const char * getTypeQString () const
Overloaded function from QVGenericImage::getTypeQString().
uInt getRows () const
Overloaded function from QVGenericImage::getRows().
uInt getCols () const
Overloaded function from QVGenericImage::getCols().
uInt getStep () const
Overloaded function from QVGenericImage::getStep().
uInt getChannels () const
Overloaded function from QVGenericImage::getChannels().
uInt getDataSize () const
Overloaded function from QVGenericImage::getDataSize().
uInt getTypeSize () const
Overloaded function from QVGenericImage::getTypeSize().
const Type * getReadData () const
Method to obtain image data buffer, in read mode.
Type * getWriteData ()
Method to obtain image data buffer, in read/write mode.
void set (Type c1=0, Type c2=0, Type c3=0)
Sets pixel values for an image, to a given value.
bool isEmpty () const
Check if the image is empty.
void resize (const int cols, const int rows)
Resizes the image.
Type & operator() (const uInt col, const uInt row, const uInt channel=0)
Operator to access pixel values for a pixel channel, given it's coordinates.
Type & operator() (const QPoint point, const uInt channel=0)
Overload of operator (), to access pixel values for a pixel channel, given a QVPoint and a channel number.
QVImage< Type, 1 > operator() (const uInt channel=0) const
Operator to access pixel values for a pixel channel, given it's coordinates.
QVImage< Type, Channels > & operator= (const QVImage< uChar, 1 > &sourceImage)
Copy operator.
QVImage< Type, Channels > & operator= (const QVImage< uChar, 3 > &sourceImage)
Overloaded copy operator.
QVImage< Type, Channels > & operator= (const QVImage< sChar, 1 > &sourceImage)
QVImage< Type, Channels > & operator= (const QVImage< sChar, 3 > &sourceImage)
Overloaded copy operator.
QVImage< Type, Channels > & operator= (const QVImage< uShort, 1 > &sourceImage)
Overloaded copy operator.
QVImage< Type, Channels > & operator= (const QVImage< uShort, 3 > &sourceImage)
Overloaded copy operator.
QVImage< Type, Channels > & operator= (const QVImage< sShort, 1 > &sourceImage)
Overloaded copy operator.
QVImage< Type, Channels > & operator= (const QVImage< sShort, 3 > &sourceImage)
Overloaded copy operator.
QVImage< Type, Channels > & operator= (const QVImage< uInt, 1 > &sourceImage)
Overloaded copy operator.
QVImage< Type, Channels > & operator= (const QVImage< uInt, 3 > &sourceImage)
Overloaded copy operator.
QVImage< Type, Channels > & operator= (const QVImage< sInt, 1 > &sourceImage)
Overloaded copy operator.
QVImage< Type, Channels > & operator= (const QVImage< sInt, 3 > &sourceImage)
Overloaded copy operator.
QVImage< Type, Channels > & operator= (const QVImage< sFloat, 1 > &sourceImage)
Overloaded copy operator.
QVImage< Type, Channels > & operator= (const QVImage< sFloat, 3 > &sourceImage)
Overloaded copy operator.
bool operator== (const QVImage< Type, Channels > &img) const
Equality compare operator.
bool operator!= (const QVImage< Type, Channels > &img) const
Inequality compare operator.
QVImage< uChar, 1 > operator< (const QVImage< uChar, Channels > &img) const
Pixel wise 'less than' compare operator.
QVImage< uChar, 1 > operator< (const QVImage< uShort, Channels > &img) const
Pixel wise 'less than' compare operator.
QVImage< uChar, 1 > operator< (const QVImage< sShort, Channels > &img) const
Pixel wise 'less than' compare operator.
QVImage< uChar, 1 > operator< (const QVImage< sInt, Channels > &img) const
Pixel wise 'less than' compare operator.
QVImage< uChar, 1 > operator< (const QVImage< sFloat, Channels > &img) const
Pixel wise 'less than' compare operator.
QVImage< uChar, 1 > operator> (const QVImage< uChar, Channels > &img) const
Pixel wise 'greater than' compare operator.
QVImage< uChar, 1 > operator> (const QVImage< uShort, Channels > &img) const
Pixel wise 'greater than' compare operator.
QVImage< uChar, 1 > operator> (const QVImage< sShort, Channels > &img) const
Pixel wise 'greater than' compare operator.
QVImage< uChar, 1 > operator> (const QVImage< sInt, Channels > &img) const
Pixel wise 'greater than' compare operator.
QVImage< uChar, 1 > operator> (const QVImage< sFloat, Channels > &img) const
Pixel wise 'greater than' compare operator.
QVImage< uChar, 1 > operator<= (const QVImage< uChar, Channels > &img) const
Pixel wise 'less or equal than' compare operator.
QVImage< uChar, 1 > operator<= (const QVImage< uShort, Channels > &img) const
Pixel wise 'less or equal than' compare operator.
QVImage< uChar, 1 > operator<= (const QVImage< sShort, Channels > &img) const
Pixel wise 'less or equal than' compare operator.
QVImage< uChar, 1 > operator<= (const QVImage< sInt, Channels > &img) const
Pixel wise 'less or equal than' compare operator.
QVImage< uChar, 1 > operator<= (const QVImage< sFloat, Channels > &img) const
Pixel wise 'less or equal than' compare operator.
QVImage< uChar, 1 > operator>= (const QVImage< uChar, Channels > &img) const
Pixel wise 'greater or equal than' compare operator.
QVImage< uChar, 1 > operator>= (const QVImage< uShort, Channels > &img) const
Pixel wise 'greater or equal than' compare operator.
QVImage< uChar, 1 > operator>= (const QVImage< sShort, Channels > &img) const
Pixel wise 'greater or equal than' compare operator.
QVImage< uChar, 1 > operator>= (const QVImage< sInt, Channels > &img) const
Pixel wise 'greater or equal than' compare operator.
QVImage< uChar, 1 > operator>= (const QVImage< sFloat, Channels > &img) const
Pixel wise 'greater or equal than' compare operator.
QVImage< Type, Channels > operator+ (const Type constant) const
Pixel wise constant add operator.
QVImage< Type, Channels > operator* (const Type constant) const
Pixel wise constant product operator.
QVImage< Type, Channels > operator- (const Type constant) const
Pixel wise constant subtraction operator.
QVImage< Type, Channels > operator/ (const Type constant) const
Pixel wise constant division operator.
QVImage< Type, Channels > operator<< (const Type constant) const
Pixel wise bit-wise left shift operator.
QVImage< Type, Channels > operator>> (const Type constant) const
Pixel wise bit-wise right shift operator.
QVImage< Type, Channels > operator! () const
Pixel wise bit-wise NOT operation.
QVImage< Type, Channels > operator& (const Type constant) const
Pixel wise bit-wise boolean and operator.
QVImage< Type, Channels > operator| (const Type constant) const
Pixel wise bit-wise boolean or operator.
QVImage< Type, Channels > operator^ (const Type constant) const
Pixel wise bit-wise boolean xor operator.
QVImage< Type, Channels > operator+ (const QVImage< Type, Channels > &img) const
Pixel wise add operator.
QVImage< Type, Channels > operator* (const QVImage< Type, Channels > &img) const
Pixel wise mult operator.
QVImage< Type, Channels > operator- (const QVImage< Type, Channels > &img) const
Pixel wise subtraction operator.
QVImage< Type, Channels > operator/ (const QVImage< Type, Channels > &img) const
Pixel wise division operator.
template<>
const char * getTypeQString () const
Obtain a char string identifying the type of the image. real image contained in the QVGenericImage.
template<>
const char * getTypeQString () const
Obtain a char string identifying the type of the image. real image contained in the QVGenericImage.
template<>
const char * getTypeQString () const
Obtain a char string identifying the type of the image. real image contained in the QVGenericImage.
template<>
const char * getTypeQString () const
Obtain a char string identifying the type of the image. real image contained in the QVGenericImage.
template<>
const char * getTypeQString () const
Obtain a char string identifying the type of the image. real image contained in the QVGenericImage.
template<>
const char * getTypeQString () const
Obtain a char string identifying the type of the image. real image contained in the QVGenericImage.
template<>
const char * getTypeQString () const
Obtain a char string identifying the type of the image. real image contained in the QVGenericImage.
template<>
const char * getTypeQString () const
Obtain a char string identifying the type of the image. real image contained in the QVGenericImage.
template<>
const char * getTypeQString () const
Obtain a char string identifying the type of the image. real image contained in the QVGenericImage.
template<>
const char * getTypeQString () const
Obtain a char string identifying the type of the image. real image contained in the QVGenericImage.
template<>
const char * getTypeQString () const
Obtain a char string identifying the type of the image. real image contained in the QVGenericImage.
template<>
const char * getTypeQString () const
Obtain a char string identifying the type of the image. real image contained in the QVGenericImage.
Detailed Description
template<typename Type = uChar, int Channels = 1>
class QVImage< Type, Channels >
Image representation class for the QVision.
QVImage class extends QVGenericImage, and wraps the data buffer and other values related to an image in a simple and lightweight structure, easy to use.
For further info about image objects and image usage, see section BasicImageProcessing of the manual.
Template Parameters:
Type Pixel storage type. Can be uChar, sChar, uShort, sShort, uLong, sLong, sFloat or sDouble. For further info see section The QVImage class.
Channels Number of channels in the image. Usually 1 or 3.
Definition at line 201 of file qvimage.h.
Constructor & Destructor Documentation
template<typename Type = uChar, int Channels = 1> QVImage< Type, Channels >::QVImage (uInt cols = 1, uInt rows = 1) [inline]
Default constructor.
Parameters:
cols number of columns for the image.
rows number of rows for the image.
Definition at line 236 of file qvimage.h.
template<typename Type = uChar, int Channels = 1> QVImage< Type, Channels >::QVImage (QVImage< uChar, 1 > const & img)
Copy constructor.
This constructor can be used to construct an image from another one with same bit depth and channel number, or from an image differing in type or number of channels.
In the former case, this constructor will do a copy-on-write, duplicating the pointer to the data buffer of the image, and effectively copying the data only when modifying it if shared by more than one QVImage object.
In the latter case, it will always allocate a new data buffer for the image, and make a conversion from different bit depth or channel number. Note that you can never convert from an image that differs in data type and bit-depth with the constructed image.
This constructor will copy the ROI and anchor of the parameter image.
Parameters:
img image to be copied.
template<typename Type = uChar, int Channels = 1> QVImage< Type, Channels >::QVImage (QVImage< uChar, 3 > const & img)
Overloaded copy constructor.
template<typename Type = uChar, int Channels = 1> QVImage< Type, Channels >::QVImage (QVImage< sChar, 1 > const & img)
Parameters:
img image to be copied.
template<typename Type = uChar, int Channels = 1> QVImage< Type, Channels >::QVImage (QVImage< sChar, 3 > const & img)
Overloaded copy constructor.
template<typename Type = uChar, int Channels = 1> QVImage< Type, Channels >::QVImage (QVImage< uShort, 1 > const & img)
Overloaded copy constructor.
template<typename Type = uChar, int Channels = 1> QVImage< Type, Channels >::QVImage (QVImage< uShort, 3 > const & img)
Overloaded copy constructor.
template<typename Type = uChar, int Channels = 1> QVImage< Type, Channels >::QVImage (QVImage< sShort, 1 > const & img)
Overloaded copy constructor.
template<typename Type = uChar, int Channels = 1> QVImage< Type, Channels >::QVImage (QVImage< sShort, 3 > const & img)
Overloaded copy constructor.
template<typename Type = uChar, int Channels = 1> QVImage< Type, Channels >::QVImage (QVImage< uInt, 1 > const & img)
Overloaded copy constructor.
template<typename Type = uChar, int Channels = 1> QVImage< Type, Channels >::QVImage (QVImage< uInt, 3 > const & img)
Overloaded copy constructor.
template<typename Type = uChar, int Channels = 1> QVImage< Type, Channels >::QVImage (QVImage< sInt, 1 > const & img)
Overloaded copy constructor.
template<typename Type = uChar, int Channels = 1> QVImage< Type, Channels >::QVImage (QVImage< sInt, 3 > const & img)
Overloaded copy constructor.
template<typename Type = uChar, int Channels = 1> QVImage< Type, Channels >::QVImage (QVImage< sFloat, 1 > const & img)
Overloaded copy constructor.
template<typename Type = uChar, int Channels = 1> QVImage< Type, Channels >::QVImage (QVImage< sFloat, 3 > const & img)
Overloaded copy constructor.
template<typename Type = uChar, int Channels = 1> QVImage< Type, Channels >::QVImage (const QString & filename) [inline]
Todo:
document this function
Definition at line 302 of file qvimage.h.
template<typename Type = uChar, int Channels = 1> QVImage< Type, Channels >::QVImage (QVImage< uChar, 1 > const & red, QVImage< uChar, 1 > const & green, QVImage< uChar, 1 > const & blue)
Compose copy constructor.
This constructor can be used to construct a 3-channels image from 3 1-channel images.
This constructor will copy the ROI and anchor of the first parameter image.
Parameters:
red image to be copied to the first channel.
green image to be copied to the second channel.
blue image to be copied to the third channel.
template<typename Type = uChar, int Channels = 1> QVImage< Type, Channels >::QVImage (QVImage< uShort, 1 > const & red, QVImage< uShort, 1 > const & green, QVImage< uShort, 1 > const & blue)
Overloaded compose copy constructor.
template<typename Type = uChar, int Channels = 1> QVImage< Type, Channels >::QVImage (QVImage< sShort, 1 > const & red, QVImage< sShort, 1 > const & green, QVImage< sShort, 1 > const & blue)
Overloaded compose copy constructor.
template<typename Type = uChar, int Channels = 1> QVImage< Type, Channels >::QVImage (QVImage< sInt, 1 > const & red, QVImage< sInt, 1 > const & green, QVImage< sInt, 1 > const & blue)
Overloaded compose copy constructor.
template<typename Type = uChar, int Channels = 1> QVImage< Type, Channels >::QVImage (QVImage< sFloat, 1 > const & red, QVImage< sFloat, 1 > const & green, QVImage< sFloat, 1 > const & blue)
Overloaded compose copy constructor.
template<typename Type = uChar, int Channels = 1> QVImage< Type, Channels >::QVImage (const QImage & qImage)
Convert constructor for QImage objects.
template<typename Type = uChar, int Channels = 1> QVImage< Type, Channels >::QVImage (const IplImage * iplImage)
Convert constructor from OpenCV image objects (IplImage).
This function creates an image object importing the data from an OpenCV image (IplImage).
Note:
OpenCV compatibility option must be enabled at the QVision library compilation to use this constructor
Parameters:
iplImage pointer to the IplImage
See also:
operator IplImage *() const
Member Function Documentation
template<typename Type = uChar, int Channels = 1> QVImage< Type, Channels >::operator QImage () const
Converts the QVImage to a QImage object.
template<typename Type = uChar, int Channels = 1> QVImage< Type, Channels >::operator IplImage * () const
Converts the QVImage to an OpenCV image object (IplImage).
This function creates a new IplImage object with the same dimensions and content of the actual image.
Note:
OpenCV compatibility option must be enabled at the QVision library compilation to use this constructor
See also:
QVImage(const IplImage *)
template<typename Type = uChar, int Channels = 1> const char* QVImage< Type, Channels >::getTypeQString () const [virtual]
Overloaded function from QVGenericImage::getTypeQString().
Implements QVGenericImage.
template<typename Type = uChar, int Channels = 1> uInt QVImage< Type, Channels >::getRows () const [inline, virtual]
Overloaded function from QVGenericImage::getRows().
Implements QVGenericImage.
Definition at line 364 of file qvimage.h.
Referenced by applyHomography(), CountingSort(), QVKLTTracker::detect(), FASTFeatures(), FastLaplaceFilter(), FastSmoothFilter(), FilterDoG(), FilterLocalMax(), FilterSeparable(), getConnectedSetBorderContoursThreshold(), QVBRIEFDetector::getDescriptors(), QVVideoReader::getGrayImage(), getLineContoursThreshold4Connectivity(), getLineContoursThreshold8Connectivity(), getLTMSER(), getMSERContours(), QVVideoReader::getRGBImage(), getSiftGPUFeatures(), QVVideoReader::getYUVImage(), QVVideoReader::grab(), myFloodFill(), QVImage< uChar, 3 >::operator()(), QVImage< Type, Channels >::operator==(), QVComponentTree::QVComponentTree(), QVImage< uChar, 3 >::QVImage(), QVKLTTracker::redetect(), QVImage< uChar, 3 >::resize(), SmoothFilter(), QVKLTTracker::track(), QVCUDAImage< Type, Channels >::uploadToDevice(), and writeYUV4MPEG2Frame().
template<typename Type = uChar, int Channels = 1> uInt QVImage< Type, Channels >::getCols () const [inline, virtual]
Overloaded function from QVGenericImage::getCols().
Implements QVGenericImage.
Definition at line 367 of file qvimage.h.
Referenced by applyHomography(), CountingSort(), QVKLTTracker::detect(), FASTFeatures(), FastLaplaceFilter(), FastSmoothFilter(), FilterDoG(), FilterLocalMax(), FilterSeparable(), getConnectedSetBorderContoursThreshold(), QVBRIEFDetector::getDescriptors(), QVVideoReader::getGrayImage(), getLineContoursThreshold4Connectivity(), getLineContoursThreshold8Connectivity(), getLTMSER(), getMSERContours(), QVVideoReader::getRGBImage(), QVVideoReader::getYUVImage(), QVVideoReader::grab(), myFloodFill(), QVImage< uChar, 3 >::operator()(), QVImage< Type, Channels >::operator==(), QVComponentTree::QVComponentTree(), QVImage< uChar, 3 >::QVImage(), QVKLTTracker::redetect(), QVImage< uChar, 3 >::resize(), SmoothFilter(), QVKLTTracker::track(), QVCUDAImage< Type, Channels >::uploadToDevice(), and writeYUV4MPEG2Frame().
template<typename Type = uChar, int Channels = 1> uInt QVImage< Type, Channels >::getStep () const [inline, virtual]
Overloaded function from QVGenericImage::getStep().
Implements QVGenericImage.
Definition at line 370 of file qvimage.h.
Referenced by Abs(), AbsDiff(), Add(), AddC(), AddRandUniform_Direct(), And(), AndC(), Canny(), Compare(), CompareC(), ComputeThreshold_Otsu(), Convert(), Copy(), Dilate(), DistanceTransform_5x5(), Div(), DivC(), QVCUDAImage< Type, Channels >::downloadFromDevice(), Erode(), FASTFeatures(), FastLaplaceFilter(), FastMarching(), fastMaximalPoints(), FastSmoothFilter(), Filter(), FilterBox(), FilterColumn(), FilterGauss(), FilterHipass(), FilterLaplace(), FilterLowpass(), FilterMax(), FilterMedian(), FilterMedianColor(), FilterMedianCross(), FilterMedianHoriz(), FilterMedianVert(), FilterMedianWeightedCenter3x3(), FilterMin(), FilterRow(), FilterSobelHorizMask(), FilterSobelVertMask(), QVBRIEFDetector::getDescriptors(), getLTMSER(), getSiftGPUFeatures(), HistogramRange(), Inpaint(), InpaintInitAllocC1(), InpaintInitAllocC3(), Integral(), Ln(), LShiftC(), Max(), MaxEvery(), maximalPoints(), Mean(), Min(), MinEigenVal(), MinEvery(), Mul(), MulC(), MulScale(), Not(), QVImage< uChar, 3 >::operator QImage(), QVImage< uChar, 3 >::operator()(), Or(), OrC(), QVImage< uChar, 3 >::QVImage(), RGBToGray(), RGBToYUV420(), RShiftC(), Scale(), Set(), SmoothFilter(), Sqr(), Sub(), SubC(), Sum(), Threshold(), Threshold_LTValGTVal(), Threshold_Val(), QVCUDAImage< Type, Channels >::uploadToDevice(), Xor(), XorC(), and YUV420ToRGB().
template<typename Type = uChar, int Channels = 1> uInt QVImage< Type, Channels >::getChannels () const [inline, virtual]
Overloaded function from QVGenericImage::getChannels().
Implements QVGenericImage.
Definition at line 373 of file qvimage.h.
Referenced by QVImage< Type, Channels >::operator==().
template<typename Type = uChar, int Channels = 1> uInt QVImage< Type, Channels >::getDataSize () const [inline, virtual]
Overloaded function from QVGenericImage::getDataSize().
Implements QVGenericImage.
Definition at line 376 of file qvimage.h.
Referenced by QVImage< uChar, 3 >::isEmpty(), and QVImage< uChar, 3 >::operator()().
template<typename Type = uChar, int Channels = 1> uInt QVImage< Type, Channels >::getTypeSize () const [inline, virtual]
Overloaded function from QVGenericImage::getTypeSize().
Implements QVGenericImage.
Definition at line 379 of file qvimage.h.
template<typename Type = uChar, int Channels = 1> const Type* QVImage< Type, Channels >::getReadData () const [inline]
Method to obtain image data buffer, in read mode.
This method can be used to program fast access algorithms to pixel values in an image.
It is intended to be used only to read pixels in an image, thus getWriteData() method should be used when access to write or read/write is intended to be done.
This function will generally be faster than getWriteData(), because it will not need to realize copy on write, in the case that the image data buffer where shared with other QVImage.
Definition at line 391 of file qvimage.h.
Referenced by QVKLTTracker::detect(), FASTFeatures(), FastLaplaceFilter(), fastMaximalPoints(), FastSmoothFilter(), QVBRIEFDetector::getDescriptors(), getSiftGPUFeatures(), InpaintInitAllocC1(), InpaintInitAllocC3(), QVImage< uChar, 3 >::operator QImage(), QVKLTTracker::redetect(), SmoothFilter(), QVKLTTracker::track(), and QVCUDAImage< Type, Channels >::uploadToDevice().
template<typename Type = uChar, int Channels = 1> Type* QVImage< Type, Channels >::getWriteData () [inline]
Method to obtain image data buffer, in read/write mode.
This method can be used to program fast access algorithms to pixel values in an image.
This function will perform copy on write in the case that the data buffer for this image where shared with other QVImage's.
Thus can be slower than getReadData() method to access image pixels, but will ensure avoiding side effects on modifying shared buffers with other images.
Definition at line 403 of file qvimage.h.
Referenced by Canny(), QVCUDAImage< Type, Channels >::downloadFromDevice(), FastLaplaceFilter(), FastMarching(), FastSmoothFilter(), getLTMSER(), MinEigenVal(), QVImage< uChar, 3 >::QVImage(), qvOpticalFlowGPU(), and SmoothFilter().
template<typename Type = uChar, int Channels = 1> void QVImage< Type, Channels >::set (Type c1 = 0, Type c2 = 0, Type c3 = 0)
Sets pixel values for an image, to a given value.
This method uses the region of interest of the image, to set pixels inside it to a given value. It can be used either for one channel, or several channel images.
In the former case, it should be used with one parameter, only specifying value for the first channel, otherwise, values for other channels will be ignored. If no parameters are given, the image region of interest will be set to zero value pixels.
In the latter case, default values of 0 will be used if there are unspecified channel values.
Parameters:
c1 value to set pixel's first channel in the region of interest of the image.
c2 value to set pixel's second channel in the region of interest of the image.
c3 value to set pixel's third channel in the region of interest of the image.
template<typename Type = uChar, int Channels = 1> bool QVImage< Type, Channels >::isEmpty () const [inline]
Check if the image is empty.
Returns:
true if the image contains no data, false otherwise.
Definition at line 425 of file qvimage.h.
template<typename Type = uChar, int Channels = 1> void QVImage< Type, Channels >::resize (const int cols, const int rows) [inline]
Resizes the image.
This method reserves extra space for a larger image.
Parameters:
cols new columns number.
rows new row number.
Definition at line 436 of file qvimage.h.
template<typename Type = uChar, int Channels = 1> Type& QVImage< Type, Channels >::operator() (const uInt col, const uInt row, const uInt channel = 0) [inline]
Operator to access pixel values for a pixel channel, given it's coordinates.
This operator can be used either with one channel or multichannel images. In the first case, it shouldn't be given a channel number, to use the default zero value.
Parameters:
col column number of pixel to be accessed.
row row number of pixel to be accessed.
channel channel number of pixel to be accessed.
Definition at line 455 of file qvimage.h.
template<typename Type = uChar, int Channels = 1> Type& QVImage< Type, Channels >::operator() (const QPoint point, const uInt channel = 0) [inline]
Overload of operator (), to access pixel values for a pixel channel, given a QVPoint and a channel number.
This overload is like the previous, but can be used with a QPoint, to access a concrete pixel in the image.
Parameters:
point QPoint indicating location of the pixel to be accessed.
channel channel number of pixel to be accessed.
Definition at line 485 of file qvimage.h.
template<typename Type = uChar, int Channels = 1> QVImage<Type, 1> QVImage< Type, Channels >::operator() (const uInt channel = 0) const
Operator to access pixel values for a pixel channel, given it's coordinates.
This operator can be used either with one channel or multichannel images. In the first case, it shouldn't be given a channel number, to use the default zero value.
Parameters:
col column number of pixel to be accessed.
row row number of pixel to be accessed.
channel channel number of pixel to be accessed.
template<typename Type = uChar, int Channels = 1> QVImage<Type, Channels>& QVImage< Type, Channels >::operator= (const QVImage< uChar, 1 > & sourceImage)
Copy operator.
Like the copy constructor, this operator can be used to copy an image from another one with same bit depth and channel number, or from an image differing in type or number of channels.
In the former case, this operator will do a copy-on-write, duplicating the pointer to the data buffer of the image, and effectively copying the data only when modifying it if shared by more than one QVImage object.
In the latter case, it will always allocate a new data buffer for the image, and make a conversion from different bit depth or channel number. Note that you can never convert from an image that differs in data type and bit-depth with the constructed image.
The copy operator will copy the ROI and anchor of the parameter image.
Parameters:
img image to be copied.
template<typename Type = uChar, int Channels = 1> QVImage<Type, Channels>& QVImage< Type, Channels >::operator= (const QVImage< uChar, 3 > & sourceImage)
Overloaded copy operator.
template<typename Type = uChar, int Channels = 1> QVImage<Type, Channels>& QVImage< Type, Channels >::operator= (const QVImage< sChar, 1 > & sourceImage)
Parameters:
img image to be copied.
template<typename Type = uChar, int Channels = 1> QVImage<Type, Channels>& QVImage< Type, Channels >::operator= (const QVImage< sChar, 3 > & sourceImage)
Overloaded copy operator.
template<typename Type = uChar, int Channels = 1> QVImage<Type, Channels>& QVImage< Type, Channels >::operator= (const QVImage< uShort, 1 > & sourceImage)
Overloaded copy operator.
template<typename Type = uChar, int Channels = 1> QVImage<Type, Channels>& QVImage< Type, Channels >::operator= (const QVImage< uShort, 3 > & sourceImage)
Overloaded copy operator.
template<typename Type = uChar, int Channels = 1> QVImage<Type, Channels>& QVImage< Type, Channels >::operator= (const QVImage< sShort, 1 > & sourceImage)
Overloaded copy operator.
template<typename Type = uChar, int Channels = 1> QVImage<Type, Channels>& QVImage< Type, Channels >::operator= (const QVImage< sShort, 3 > & sourceImage)
Overloaded copy operator.
template<typename Type = uChar, int Channels = 1> QVImage<Type, Channels>& QVImage< Type, Channels >::operator= (const QVImage< uInt, 1 > & sourceImage)
Overloaded copy operator.
template<typename Type = uChar, int Channels = 1> QVImage<Type, Channels>& QVImage< Type, Channels >::operator= (const QVImage< uInt, 3 > & sourceImage)
Overloaded copy operator.
template<typename Type = uChar, int Channels = 1> QVImage<Type, Channels>& QVImage< Type, Channels >::operator= (const QVImage< sInt, 1 > & sourceImage)
Overloaded copy operator.
template<typename Type = uChar, int Channels = 1> QVImage<Type, Channels>& QVImage< Type, Channels >::operator= (const QVImage< sInt, 3 > & sourceImage)
Overloaded copy operator.
template<typename Type = uChar, int Channels = 1> QVImage<Type, Channels>& QVImage< Type, Channels >::operator= (const QVImage< sFloat, 1 > & sourceImage)
Overloaded copy operator.
template<typename Type = uChar, int Channels = 1> QVImage<Type, Channels>& QVImage< Type, Channels >::operator= (const QVImage< sFloat, 3 > & sourceImage)
Overloaded copy operator.
template<typename Type = uChar, int Channels = 1> bool QVImage< Type, Channels >::operator!= (const QVImage< Type, Channels > & img) const [inline]
Inequality compare operator.
This operator will compare two images of same bit depth and channel number, and will return true if images differ in any of:
dimensions (cols and rows).
region of interest.
content of region of interest. returning false otherwise.
Todo:
Shouldn't ignore dimensions in caparisons, and only check if region of interest content are the same?
Parameters:
img image to compare with this image.
Returns:
true if images are practically equal (same content of region of interest and dimensions).
Definition at line 601 of file qvimage.h.
template<typename Type = uChar, int Channels = 1> QVImage<uChar, 1> QVImage< Type, Channels >::operator< (const QVImage< uChar, Channels > & img) const
Pixel wise 'less than' compare operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Parameters:
img image to compare with this image.
Returns:
1-channel uChar bit depth image containing non-zero values for pixels which value for corresponding pixel in this image is less than value for corresponding pixel in given image.
template<typename Type = uChar, int Channels = 1> QVImage<uChar, 1> QVImage< Type, Channels >::operator< (const QVImage< uShort, Channels > & img) const
Pixel wise 'less than' compare operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Parameters:
img image to compare with this image.
Returns:
1-channel uChar bit depth image containing non-zero values for pixels which value for corresponding pixel in this image is less than value for corresponding pixel in given image.
template<typename Type = uChar, int Channels = 1> QVImage<uChar, 1> QVImage< Type, Channels >::operator< (const QVImage< sShort, Channels > & img) const
Pixel wise 'less than' compare operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Parameters:
img image to compare with this image.
Returns:
1-channel uChar bit depth image containing non-zero values for pixels which value for corresponding pixel in this image is less than value for corresponding pixel in given image.
template<typename Type = uChar, int Channels = 1> QVImage<uChar, 1> QVImage< Type, Channels >::operator< (const QVImage< sInt, Channels > & img) const
Pixel wise 'less than' compare operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Parameters:
img image to compare with this image.
Returns:
1-channel uChar bit depth image containing non-zero values for pixels which value for corresponding pixel in this image is less than value for corresponding pixel in given image.
template<typename Type = uChar, int Channels = 1> QVImage<uChar, 1> QVImage< Type, Channels >::operator< (const QVImage< sFloat, Channels > & img) const
Pixel wise 'less than' compare operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Parameters:
img image to compare with this image.
Returns:
1-channel uChar bit depth image containing non-zero values for pixels which value for corresponding pixel in this image is less than value for corresponding pixel in given image.
template<typename Type = uChar, int Channels = 1> QVImage<uChar, 1> QVImage< Type, Channels >::operator> (const QVImage< uChar, Channels > & img) const
Pixel wise 'greater than' compare operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Parameters:
img image to compare with this image.
Returns:
1-channel uChar bit depth image containing non-zero values for pixels which value for corresponding pixel in this image is greater than value for corresponding pixel in given image.
template<typename Type = uChar, int Channels = 1> QVImage<uChar, 1> QVImage< Type, Channels >::operator> (const QVImage< uShort, Channels > & img) const
Pixel wise 'greater than' compare operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Parameters:
img image to compare with this image.
Returns:
1-channel uChar bit depth image containing non-zero values for pixels which value for corresponding pixel in this image is greater than value for corresponding pixel in given image.
template<typename Type = uChar, int Channels = 1> QVImage<uChar, 1> QVImage< Type, Channels >::operator> (const QVImage< sShort, Channels > & img) const
Pixel wise 'greater than' compare operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Parameters:
img image to compare with this image.
Returns:
1-channel uChar bit depth image containing non-zero values for pixels which value for corresponding pixel in this image is greater than value for corresponding pixel in given image.
template<typename Type = uChar, int Channels = 1> QVImage<uChar, 1> QVImage< Type, Channels >::operator> (const QVImage< sInt, Channels > & img) const
Pixel wise 'greater than' compare operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Parameters:
img image to compare with this image.
Returns:
1-channel uChar bit depth image containing non-zero values for pixels which value for corresponding pixel in this image is greater than value for corresponding pixel in given image.
template<typename Type = uChar, int Channels = 1> QVImage<uChar, 1> QVImage< Type, Channels >::operator> (const QVImage< sFloat, Channels > & img) const
Pixel wise 'greater than' compare operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Parameters:
img image to compare with this image.
Returns:
1-channel uChar bit depth image containing non-zero values for pixels which value for corresponding pixel in this image is greater than value for corresponding pixel in given image.
template<typename Type = uChar, int Channels = 1> QVImage<uChar, 1> QVImage< Type, Channels >::operator<= (const QVImage< uChar, Channels > & img) const
Pixel wise 'less or equal than' compare operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Parameters:
img image to compare with this image.
Returns:
1-channel uChar bit depth image containing non-zero values for pixels which value for corresponding pixel in this image is less or equal than value for corresponding pixel in given image.
template<typename Type = uChar, int Channels = 1> QVImage<uChar, 1> QVImage< Type, Channels >::operator<= (const QVImage< uShort, Channels > & img) const
Pixel wise 'less or equal than' compare operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Parameters:
img image to compare with this image.
Returns:
1-channel uChar bit depth image containing non-zero values for pixels which value for corresponding pixel in this image is less or equal than value for corresponding pixel in given image.
template<typename Type = uChar, int Channels = 1> QVImage<uChar, 1> QVImage< Type, Channels >::operator<= (const QVImage< sShort, Channels > & img) const
Pixel wise 'less or equal than' compare operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Parameters:
img image to compare with this image.
Returns:
1-channel uChar bit depth image containing non-zero values for pixels which value for corresponding pixel in this image is less or equal than value for corresponding pixel in given image.
template<typename Type = uChar, int Channels = 1> QVImage<uChar, 1> QVImage< Type, Channels >::operator<= (const QVImage< sInt, Channels > & img) const
Pixel wise 'less or equal than' compare operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Parameters:
img image to compare with this image.
Returns:
1-channel uChar bit depth image containing non-zero values for pixels which value for corresponding pixel in this image is less or equal than value for corresponding pixel in given image.
template<typename Type = uChar, int Channels = 1> QVImage<uChar, 1> QVImage< Type, Channels >::operator<= (const QVImage< sFloat, Channels > & img) const
Pixel wise 'less or equal than' compare operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Parameters:
img image to compare with this image.
Returns:
1-channel uChar bit depth image containing non-zero values for pixels which value for corresponding pixel in this image is less or equal than value for corresponding pixel in given image.
template<typename Type = uChar, int Channels = 1> QVImage<uChar, 1> QVImage< Type, Channels >::operator>= (const QVImage< uChar, Channels > & img) const
Pixel wise 'greater or equal than' compare operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Parameters:
img image to compare with this image.
Returns:
1-channel uChar bit depth image containing non-zero values for pixels which value for corresponding pixel in this image is greater or equal than value for corresponding pixel in given image.
template<typename Type = uChar, int Channels = 1> QVImage<uChar, 1> QVImage< Type, Channels >::operator>= (const QVImage< uShort, Channels > & img) const
Pixel wise 'greater or equal than' compare operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Parameters:
img image to compare with this image.
Returns:
1-channel uChar bit depth image containing non-zero values for pixels which value for corresponding pixel in this image is greater or equal than value for corresponding pixel in given image.
template<typename Type = uChar, int Channels = 1> QVImage<uChar, 1> QVImage< Type, Channels >::operator>= (const QVImage< sShort, Channels > & img) const
Pixel wise 'greater or equal than' compare operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Parameters:
img image to compare with this image.
Returns:
1-channel uChar bit depth image containing non-zero values for pixels which value for corresponding pixel in this image is greater or equal than value for corresponding pixel in given image.
template<typename Type = uChar, int Channels = 1> QVImage<uChar, 1> QVImage< Type, Channels >::operator>= (const QVImage< sInt, Channels > & img) const
Pixel wise 'greater or equal than' compare operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Parameters:
img image to compare with this image.
Returns:
1-channel uChar bit depth image containing non-zero values for pixels which value for corresponding pixel in this image is greater or equal than value for corresponding pixel in given image.
template<typename Type = uChar, int Channels = 1> QVImage<uChar, 1> QVImage< Type, Channels >::operator>= (const QVImage< sFloat, Channels > & img) const
Pixel wise 'greater or equal than' compare operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Parameters:
img image to compare with this image.
Returns:
1-channel uChar bit depth image containing non-zero values for pixels which value for corresponding pixel in this image is greater or equal than value for corresponding pixel in given image.
template<typename Type = uChar, int Channels = 1> QVImage<Type, Channels> QVImage< Type, Channels >::operator+ (const Type constant) const
Pixel wise constant add operator.
Uses as the second operand a constant value for every pixel computed.
Saturation is used for integer bit depth data (any except sFloat bit depth). Regions of interests, and anchors are applied in this operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Parameters:
constant second operand value.
Returns:
resulting image for the operation.
template<typename Type = uChar, int Channels = 1> QVImage<Type, Channels> QVImage< Type, Channels >::operator* (const Type constant) const
Pixel wise constant product operator.
Uses as the second operand a constant value for every pixel computed.
Saturation is used for integer bit depth data (any except sFloat bit depth). Regions of interests, and anchors are applied in this operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Parameters:
constant second operand value.
Returns:
resulting image for the operation.
template<typename Type = uChar, int Channels = 1> QVImage<Type, Channels> QVImage< Type, Channels >::operator- (const Type constant) const
Pixel wise constant subtraction operator.
Uses as the second operand a constant value for every pixel computed.
Saturation is used for integer bit depth data (any except sFloat bit depth). Regions of interests, and anchors are applied in this operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Parameters:
constant second operand value.
Returns:
resulting image for the operation.
template<typename Type = uChar, int Channels = 1> QVImage<Type, Channels> QVImage< Type, Channels >::operator/ (const Type constant) const
Pixel wise constant division operator.
Uses as the second operand a constant value for every pixel computed.
Saturation is used for integer bit depth data (any except sFloat bit depth). Regions of interests, and anchors are applied in this operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Parameters:
constant second operand value.
Returns:
resulting image for the operation.
template<typename Type = uChar, int Channels = 1> QVImage<Type, Channels> QVImage< Type, Channels >::operator<< (const Type constant) const
Pixel wise bit-wise left shift operator.
Uses as the value to shift a constant value for every pixel computed.
Saturation is used for integer bit depth data (any except sFloat bit depth). Regions of interests, and anchors are applied in this operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Parameters:
constant second operand value.
Returns:
resulting image for the operation.
template<typename Type = uChar, int Channels = 1> QVImage<Type, Channels> QVImage< Type, Channels >::operator>> (const Type constant) const
Pixel wise bit-wise right shift operator.
Uses as the value to shift a constant value for every pixel computed.
Saturation is used for integer bit depth data (any except sFloat bit depth). Regions of interests, and anchors are applied in this operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Parameters:
constant second operand value.
Returns:
resulting image for the operation.
template<typename Type = uChar, int Channels = 1> QVImage<Type, Channels> QVImage< Type, Channels >::operator! () const
Pixel wise bit-wise NOT operation.
Regions of interests, and anchors are applied in this operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Returns:
resulting image for the operation.
template<typename Type = uChar, int Channels = 1> QVImage<Type, Channels> QVImage< Type, Channels >::operator& (const Type constant) const
Pixel wise bit-wise boolean and operator.
Regions of interests, and anchors are applied in this operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Parameters:
constant second operand value.
Returns:
resulting image for the operation.
template<typename Type = uChar, int Channels = 1> QVImage<Type, Channels> QVImage< Type, Channels >::operator| (const Type constant) const
Pixel wise bit-wise boolean or operator.
Regions of interests, and anchors are applied in this operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Parameters:
constant second operand value.
Returns:
resulting image for the operation.
template<typename Type = uChar, int Channels = 1> QVImage<Type, Channels> QVImage< Type, Channels >::operator^ (const Type constant) const
Pixel wise bit-wise boolean xor operator.
Regions of interests, and anchors are applied in this operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Parameters:
constant second operand value.
Returns:
resulting image for the operation.
template<typename Type = uChar, int Channels = 1> QVImage<Type, Channels> QVImage< Type, Channels >::operator+ (const QVImage< Type, Channels > & img) const
Pixel wise add operator.
Saturation is used for integer bit depth data (any except sFloat bit depth). Regions of interests, and anchors are applied in this operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Parameters:
img operand image.
Returns:
resulting image for the operation.
template<typename Type = uChar, int Channels = 1> QVImage<Type, Channels> QVImage< Type, Channels >::operator* (const QVImage< Type, Channels > & img) const
Pixel wise mult operator.
Saturation is used for integer bit depth data (any except sFloat bit depth). Regions of interests, and anchors are applied in this operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Parameters:
img operand image.
Returns:
resulting image for the operation.
template<typename Type = uChar, int Channels = 1> QVImage<Type, Channels> QVImage< Type, Channels >::operator- (const QVImage< Type, Channels > & img) const
Pixel wise subtraction operator.
Saturation is used for integer bit depth data (any except sFloat bit depth). Regions of interests, and anchors are applied in this operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Parameters:
img operand image.
Returns:
resulting image for the operation.
template<typename Type = uChar, int Channels = 1> QVImage<Type, Channels> QVImage< Type, Channels >::operator/ (const QVImage< Type, Channels > & img) const
Pixel wise division operator.
Saturation is used for integer bit depth data (any except sFloat bit depth). Regions of interests, and anchors are applied in this operator.
Note:
This operator is based on functionality from the Intel IPP library. Thus, compatibility with that library must be enabled to be available.
Parameters:
img operand image.
Returns:
resulting image for the operation.
template<> const char * QVImage< sChar, 1 >::getTypeQString () const [inline, virtual]
Obtain a char string identifying the type of the image. real image contained in the QVGenericImage.
Returns:
pointer to a constant char string identifying image type.
Implements QVGenericImage.
Definition at line 32 of file qvimage.cpp.
template<> const char * QVImage< sChar, 3 >::getTypeQString () const [inline, virtual]
Obtain a char string identifying the type of the image. real image contained in the QVGenericImage.
Returns:
pointer to a constant char string identifying image type.
Implements QVGenericImage.
Definition at line 33 of file qvimage.cpp.
template<> const char * QVImage< uShort, 1 >::getTypeQString () const [inline, virtual]
Obtain a char string identifying the type of the image. real image contained in the QVGenericImage.
Returns:
pointer to a constant char string identifying image type.
Implements QVGenericImage.
Definition at line 34 of file qvimage.cpp.
template<> const char * QVImage< uShort, 3 >::getTypeQString () const [inline, virtual]
Obtain a char string identifying the type of the image. real image contained in the QVGenericImage.
Returns:
pointer to a constant char string identifying image type.
Implements QVGenericImage.
Definition at line 35 of file qvimage.cpp.
template<> const char * QVImage< sShort, 1 >::getTypeQString () const [inline, virtual]
Obtain a char string identifying the type of the image. real image contained in the QVGenericImage.
Returns:
pointer to a constant char string identifying image type.
Implements QVGenericImage.
Definition at line 36 of file qvimage.cpp.
template<> const char * QVImage< sShort, 3 >::getTypeQString () const [inline, virtual]
Obtain a char string identifying the type of the image. real image contained in the QVGenericImage.
Returns:
pointer to a constant char string identifying image type.
Implements QVGenericImage.
Definition at line 37 of file qvimage.cpp.
template<> const char * QVImage< sInt, 1 >::getTypeQString () const [inline, virtual]
Obtain a char string identifying the type of the image. real image contained in the QVGenericImage.
Returns:
pointer to a constant char string identifying image type.
Implements QVGenericImage.
Definition at line 38 of file qvimage.cpp.
template<> const char * QVImage< sInt, 3 >::getTypeQString () const [inline, virtual]
Obtain a char string identifying the type of the image. real image contained in the QVGenericImage.
Returns:
pointer to a constant char string identifying image type.
Implements QVGenericImage.
Definition at line 39 of file qvimage.cpp.
template<> const char * QVImage< uInt, 1 >::getTypeQString () const [inline, virtual]
Obtain a char string identifying the type of the image. real image contained in the QVGenericImage.
Returns:
pointer to a constant char string identifying image type.
Implements QVGenericImage.
Definition at line 40 of file qvimage.cpp.
template<> const char * QVImage< uInt, 3 >::getTypeQString () const [inline, virtual]
Obtain a char string identifying the type of the image. real image contained in the QVGenericImage.
Returns:
pointer to a constant char string identifying image type.
Implements QVGenericImage.
Definition at line 41 of file qvimage.cpp.
template<> const char * QVImage< sFloat, 1 >::getTypeQString () const [inline, virtual]
Obtain a char string identifying the type of the image. real image contained in the QVGenericImage.
Returns:
pointer to a constant char string identifying image type.
Implements QVGenericImage.
Definition at line 42 of file qvimage.cpp.
template<> const char * QVImage< sFloat, 3 >::getTypeQString () const [inline, virtual]
Obtain a char string identifying the type of the image. real image contained in the QVGenericImage.
Returns:
pointer to a constant char string identifying image type.
Implements QVGenericImage.
Definition at line 43 of file qvimage.cpp.
The documentation for this class was generated from the following file:
src/qvip/qvimage.h
QVision framework. PARP research group. Copyright © 2007, 2008, 2009, 2010, 2011.