QVision: Qt's Image, Video and Computer Vision Library
PARP Research Group Universidad de Murcia
QVEuclideanMapping3 Class Reference
[Math functionality]
Class modeling rotation-translation transformations for 3D points.
#include <QVEuclideanMapping3>
Public Member Functions
QVEuclideanMapping3 ()
Default constructor.
QVEuclideanMapping3 (const QVEuclideanMapping3 &other)
Copy constructor.
QVEuclideanMapping3 (const QVQuaternion &q, const QV3DPointF &t)
Initialization from a quaternion rotation, and a translation vector.
QVEuclideanMapping3 (const double quatx, const double quaty, const double quatz, const double quatw, const double tx, const double ty, const double tz)
Initialization from the components of a quaternion rotation, and a translation vector.
QVEuclideanMapping3 (const QVVector &v)
Initialization from the components of a quaternion rotation, and a translation vector.
QVEuclideanMapping3 (const QVMatrix &Rt)
Initialization from a rotation-translation matrix.
QV3DPointF apply (const QV3DPointF &X) const
Applies the euclidean transformation for the point.
operator QVVector () const
Cast to a 7-size vector.
bool operator== (const QVEuclideanMapping3 &other) const
Equality compare operator.
bool operator!= (const QVEuclideanMapping3 &other) const
Inequality compare operator.
QVMatrix toRotationTranslationMatrix () const
Cast to a Rotation-translation matrix.
QVQuaternion getRotation () const
Returns the rotation quaternion of the mapping.
QV3DPointF getTranslation () const
Returns the translation of the mapping.
void setRotation (const QVQuaternion &other)
Sets the rotation quaternion of the mapping.
void setTranslation (const QV3DPointF &other)
Sets the translation of the mapping.
QVEuclideanMapping3 inverse () const
Computes the inverse of the mapping.
QVEuclideanMapping3 compose (const QVEuclideanMapping3 &other) const
Composes two euclidean mappings.
QVEuclideanMapping3 operator* (const QVEuclideanMapping3 &other) const
Composes two euclidean mappings.
QVEuclideanMapping3 operator/ (const QVEuclideanMapping3 &other) const
Divides an euclidean mapping by another one.
Detailed Description
Class modeling rotation-translation transformations for 3D points.
This class models elements from the E3 group. These elements are combinations of translations and rotations in the 3D euclidean space.
Each element from this class contains a quaternion and a 3D point, respectively representing the rotation and the translation of the elements of the 3D space.
Definition at line 44 of file qveuclideanmapping3.h.
Constructor & Destructor Documentation
QVEuclideanMapping3::QVEuclideanMapping3 () [inline]
Default constructor.
Definition at line 52 of file qveuclideanmapping3.h.
Referenced by compose(), and inverse().
QVEuclideanMapping3::QVEuclideanMapping3 (const QVEuclideanMapping3 & other) [inline]
Copy constructor.
Definition at line 55 of file qveuclideanmapping3.h.
QVEuclideanMapping3::QVEuclideanMapping3 (const QVQuaternion & q, const QV3DPointF & t) [inline]
Initialization from a quaternion rotation, and a translation vector.
Parameters:
q Quaternion for the rotation
t 3D point for the translation
Definition at line 60 of file qveuclideanmapping3.h.
QVEuclideanMapping3::QVEuclideanMapping3 (const double quatx, const double quaty, const double quatz, const double quatw, const double tx, const double ty, const double tz) [inline]
Initialization from the components of a quaternion rotation, and a translation vector.
Parameters:
quatx Coefficient for the i coordinate of the quaternion
quaty Coefficient for the j coordinate of the quaternion
quatz Coefficient for the k coordinate of the quaternion
quatw Coefficient for the real coordinate of the quaternion
tx The x coordinate of the translation
ty The y coordinate of the translation
tz The z coordinate of the translation
Definition at line 71 of file qveuclideanmapping3.h.
QVEuclideanMapping3::QVEuclideanMapping3 (const QVVector & v) [inline]
Initialization from the components of a quaternion rotation, and a translation vector.
Parameters:
v Vector of size 7 containing the coefficients for the i, j, k, and the real components of the quaternion, and the x, y, z components of the translation, in that order.
Definition at line 81 of file qveuclideanmapping3.h.
QVEuclideanMapping3::QVEuclideanMapping3 (const QVMatrix & Rt)
Initialization from a rotation-translation matrix.
Parameters:
Rt The rotation/translation matrix. It is equal to , where is the rotation matrix, and is the translation vector.
Definition at line 28 of file qveuclideanmapping3.cpp.
Member Function Documentation
QV3DPointF QVEuclideanMapping3::apply (const QV3DPointF & X) const [inline]
Applies the euclidean transformation for the point.
Parameters:
X Point to apply the euclidean rotation-translation transformation
Definition at line 93 of file qveuclideanmapping3.h.
QVEuclideanMapping3::operator QVVector () const [inline]
Cast to a 7-size vector.
Returns:
Vector of size 7 containing the coefficients for the i, j, k, and the real components of the quaternion, and the x, y, z components of the translation, in that order.
Definition at line 103 of file qveuclideanmapping3.h.
bool QVEuclideanMapping3::operator== (const QVEuclideanMapping3 & other) const [inline]
Equality compare operator.
Definition at line 121 of file qveuclideanmapping3.h.
bool QVEuclideanMapping3::operator!= (const QVEuclideanMapping3 & other) const [inline]
Inequality compare operator.
Definition at line 128 of file qveuclideanmapping3.h.
QVMatrix QVEuclideanMapping3::toRotationTranslationMatrix () const [inline]
Cast to a Rotation-translation matrix.
Returns:
A rotation translation matrix , where is the rotation matrix, and is the translation vector.
Definition at line 137 of file qveuclideanmapping3.h.
QVQuaternion QVEuclideanMapping3::getRotation () const [inline]
Returns the rotation quaternion of the mapping.
Definition at line 153 of file qveuclideanmapping3.h.
QV3DPointF QVEuclideanMapping3::getTranslation () const [inline]
Returns the translation of the mapping.
Definition at line 156 of file qveuclideanmapping3.h.
void QVEuclideanMapping3::setRotation (const QVQuaternion & other) [inline]
Sets the rotation quaternion of the mapping.
Definition at line 159 of file qveuclideanmapping3.h.
void QVEuclideanMapping3::setTranslation (const QV3DPointF & other) [inline]
Sets the translation of the mapping.
Definition at line 162 of file qveuclideanmapping3.h.
QVEuclideanMapping3 QVEuclideanMapping3::inverse () const [inline]
Computes the inverse of the mapping.
Definition at line 166 of file qveuclideanmapping3.h.
Referenced by operator/().
QVEuclideanMapping3 QVEuclideanMapping3::compose (const QVEuclideanMapping3 & other) const [inline]
Composes two euclidean mappings.
Definition at line 174 of file qveuclideanmapping3.h.
Referenced by operator*(), and operator/().
QVEuclideanMapping3 QVEuclideanMapping3::operator* (const QVEuclideanMapping3 & other) const [inline]
Composes two euclidean mappings.
Definition at line 181 of file qveuclideanmapping3.h.
QVEuclideanMapping3 QVEuclideanMapping3::operator/ (const QVEuclideanMapping3 & other) const [inline]
Divides an euclidean mapping by another one.
This operator is equivalent to the following code:
 this->compose(other.inverse())
Definition at line 191 of file qveuclideanmapping3.h.
The documentation for this class was generated from the following files:
src/qvmath/qveuclideanmapping3.h
src/qvmath/qveuclideanmapping3.cpp
QVision framework. PARP research group. Copyright © 2007, 2008, 2009, 2010, 2011.