QVision: Qt's Image, Video and Computer Vision Library
PARP Research Group Universidad de Murcia
QV3DPointF Class Reference
[Math functionality]
3D point representation
#include <QV3DPointF>
Inherits QVVector.
Public Member Functions
QV3DPointF (const double x=0.0, const double y=0.0, const double z=0.0)
Constructs a QV3DPointF object.
double x () const
Gets the value for the first coordinate of the 3D point.
double & x ()
Gets a reference to the first coordinate of the 3D point.
double y () const
Gets the value for the second coordinate of the 3D point.
double & y ()
Gets a reference to the second coordinate of the 3D point.
double z () const
Gets the value for the third coordinate of the 3D point.
double & z ()
Gets a reference to the third coordinate of the 3D point.
Detailed Description
3D point representation
This class models a point in the 3D space.
Definition at line 38 of file qv3dpointf.h.
Constructor & Destructor Documentation
QV3DPointF::QV3DPointF (const double x = 0.0, const double y = 0.0, const double z = 0.0) [inline]
Constructs a QV3DPointF object.
Parameters:
x Value for the first coordinate of the point.
y Value for the second coordinate of the point.
z Value for the third coordinate of the point.
Definition at line 48 of file qv3dpointf.h.
Member Function Documentation
double QV3DPointF::x () const [inline]
Gets the value for the first coordinate of the 3D point.
Definition at line 59 of file qv3dpointf.h.
Referenced by linearCameraCenterResection(), linearCameraResection(), optimizeReprojectionErrorForCameraPose(), and QV3DPointF().
double& QV3DPointF::x () [inline]
Gets a reference to the first coordinate of the 3D point.
Definition at line 62 of file qv3dpointf.h.
double QV3DPointF::y () const [inline]
Gets the value for the second coordinate of the 3D point.
Definition at line 65 of file qv3dpointf.h.
Referenced by linearCameraCenterResection(), linearCameraResection(), optimizeReprojectionErrorForCameraPose(), and QV3DPointF().
double& QV3DPointF::y () [inline]
Gets a reference to the second coordinate of the 3D point.
Definition at line 68 of file qv3dpointf.h.
double QV3DPointF::z () const [inline]
Gets the value for the third coordinate of the 3D point.
Definition at line 71 of file qv3dpointf.h.
Referenced by linearCameraCenterResection(), linearCameraResection(), optimizeReprojectionErrorForCameraPose(), and QV3DPointF().
double& QV3DPointF::z () [inline]
Gets a reference to the third coordinate of the 3D point.
Definition at line 74 of file qv3dpointf.h.
The documentation for this class was generated from the following file:
src/qvmath/qv3dpointf.h
QVision framework. PARP research group. Copyright © 2007, 2008, 2009, 2010, 2011.