QVision: Qt's Image, Video and Computer Vision Library
PARP Research Group Universidad de Murcia
QVDirectedGraph< Element > Class Template Reference
[Math functionality]
Directed graph class.
#include <qvdirectedgraph.h>
Public Member Functions
QVVector getNodesConnectivity () const
Returns the number of links connecting each node.
int getMinConnectivity () const
Returns the minimal number of links connecting each node.
int getMaxConnectivity () const
Returns the maximal number of links connecting each node.
double getMeanConnectivity () const
Returns the mean number of links connecting each node.
QVDirectedGraph ()
Constructor.
void insert (const int source, const int destination, const Element element)
Add a link between two nodes of the graph.
void insert (const QVGraphLink &link, const Element element)
Add a link between two nodes of the graph.
Element operator[] (const QVGraphLink &link) const
Retrieve element for a link between two nodes.
Element & operator[] (const QVGraphLink &link)
Retrieve element for a link between two nodes.
const Element value (const int source, const int destination) const
Retrieve element for a link between two nodes.
bool contains (const int source, const int destination) const
Retrieve element for a link between two nodes.
bool contains (const QVGraphLink &link) const
Retrieve element for a link between two nodes.
QList< QVGraphLink > getLinks () const
Retrieve links defined between the nodes of the graph.
void deleteInsufficientlyConnectedNodes (const int minConnections)
Delete nodes connected by less nodes than a given value, with other nodes in the graph.
int numNodes () const
Return the number of connected nodes in the graph.
int maxNodesIndex () const
Return the maximal index for the nodes in the graph.
int getMaxNodeIndex () const
Returns the maximal index for a node in the graph.
QMap< int, int > numLinksForNode () const
QMap< int, int > numLinksPerNode () const
Returns the number of connections for each node in the graph.
Detailed Description
template<typename Element>
class QVDirectedGraph< Element >
Directed graph class.
This class represents a directed graph.
Definition at line 49 of file qvdirectedgraph.h.
Constructor & Destructor Documentation
template<typename Element> QVDirectedGraph< Element >::QVDirectedGraph () [inline]
Constructor.
Definition at line 108 of file qvdirectedgraph.h.
Member Function Documentation
template<typename Element> QVVector QVDirectedGraph< Element >::getNodesConnectivity () const [inline]
Returns the number of links connecting each node.
Definition at line 57 of file qvdirectedgraph.h.
Referenced by QVDirectedGraph< Element >::getMaxConnectivity(), QVDirectedGraph< Element >::getMeanConnectivity(), and QVDirectedGraph< Element >::getMinConnectivity().
template<typename Element> int QVDirectedGraph< Element >::getMinConnectivity () const [inline]
Returns the minimal number of links connecting each node.
Definition at line 70 of file qvdirectedgraph.h.
template<typename Element> int QVDirectedGraph< Element >::getMaxConnectivity () const [inline]
Returns the maximal number of links connecting each node.
Definition at line 73 of file qvdirectedgraph.h.
template<typename Element> double QVDirectedGraph< Element >::getMeanConnectivity () const [inline]
Returns the mean number of links connecting each node.
Definition at line 76 of file qvdirectedgraph.h.
template<typename Element> void QVDirectedGraph< Element >::insert (const int source, const int destination, const Element element) [inline]
Add a link between two nodes of the graph.
Definition at line 113 of file qvdirectedgraph.h.
Referenced by getPointMatchingsListsVec(), and QVDirectedGraph< Element >::insert().
template<typename Element> void QVDirectedGraph< Element >::insert (const QVGraphLink & link, const Element element) [inline]
Add a link between two nodes of the graph.
Definition at line 123 of file qvdirectedgraph.h.
template<typename Element> Element QVDirectedGraph< Element >::operator[] (const QVGraphLink & link) const [inline]
Retrieve element for a link between two nodes.
Definition at line 133 of file qvdirectedgraph.h.
Referenced by QVDirectedGraph< Element >::operator[]().
template<typename Element> Element& QVDirectedGraph< Element >::operator[] (const QVGraphLink & link) [inline]
Retrieve element for a link between two nodes.
Definition at line 145 of file qvdirectedgraph.h.
template<typename Element> const Element QVDirectedGraph< Element >::value (const int source, const int destination) const [inline]
Retrieve element for a link between two nodes.
Definition at line 155 of file qvdirectedgraph.h.
template<typename Element> bool QVDirectedGraph< Element >::contains (const int source, const int destination) const [inline]
Retrieve element for a link between two nodes.
Definition at line 167 of file qvdirectedgraph.h.
Referenced by QVDirectedGraph< Element >::contains().
template<typename Element> bool QVDirectedGraph< Element >::contains (const QVGraphLink & link) const [inline]
Retrieve element for a link between two nodes.
Definition at line 173 of file qvdirectedgraph.h.
template<typename Element> QList<QVGraphLink> QVDirectedGraph< Element >::getLinks () const [inline]
Retrieve links defined between the nodes of the graph.
Definition at line 179 of file qvdirectedgraph.h.
Referenced by incrementalGEA().
template<typename Element> void QVDirectedGraph< Element >::deleteInsufficientlyConnectedNodes (const int minConnections) [inline]
Delete nodes connected by less nodes than a given value, with other nodes in the graph.
This method eliminates the nodes with a smaller connectivity, leaving a skeletal graph of the best connected nodes.
Definition at line 187 of file qvdirectedgraph.h.
template<typename Element> int QVDirectedGraph< Element >::numNodes () const [inline]
Return the number of connected nodes in the graph.
Definition at line 206 of file qvdirectedgraph.h.
Referenced by writeGraphToDotFile().
template<typename Element> int QVDirectedGraph< Element >::maxNodesIndex () const [inline]
Return the maximal index for the nodes in the graph.
Deprecated:
for getMaxNodeIndex
Definition at line 213 of file qvdirectedgraph.h.
Referenced by QVDirectedGraph< Element >::getMaxNodeIndex(), and QVDirectedGraph< Element >::getNodesConnectivity().
template<typename Element> int QVDirectedGraph< Element >::getMaxNodeIndex () const [inline]
Returns the maximal index for a node in the graph.
Definition at line 224 of file qvdirectedgraph.h.
template<typename Element> QMap<int, int> QVDirectedGraph< Element >::numLinksForNode () const [inline]
Deprecated:
for numLinksPerNode
Definition at line 239 of file qvdirectedgraph.h.
template<typename Element> QMap<int, int> QVDirectedGraph< Element >::numLinksPerNode () const [inline]
Returns the number of connections for each node in the graph.
Returns:
A map containing the number of links for each node in the graph.
Definition at line 247 of file qvdirectedgraph.h.
Referenced by QVDirectedGraph< Element >::deleteInsufficientlyConnectedNodes(), QVDirectedGraph< Element >::numLinksForNode(), and QVDirectedGraph< Element >::numNodes().
The documentation for this class was generated from the following file:
src/qvmath/qvdirectedgraph.h
QVision framework. PARP research group. Copyright © 2007, 2008, 2009, 2010, 2011.