QVision: Qt's Image, Video and Computer Vision Library
PARP Research Group Universidad de Murcia
QVCUDAImage< Type, Channels > Class Template Reference
[GPU functionality]
Class to manage images stored in the GPU for the QVision framework.
#include <QVCUDAImage>
Public Member Functions
QVCUDAImage ()
Default constructor for QVCUDAImage.
QVCUDAImage (QVImage< Type, Channels > qvimage)
Constructor for QVCUDAImage class from QVImage.
QVCUDAImage (const int c, const int r)
Constructor for QVCUDAImage class from scratch.
QVCUDAImage (const QVCUDAImage< Type, Channels > &src)
Copy constructor for QVCUDAImage class.
QVCUDAImage & operator= (const QVCUDAImage< Type, Channels > &src)
Assignment operator for QVCUDAImage class.
~QVCUDAImage ()
Destructor for QVCUDAImage class.
int getCols () const
Returns the number of cols of the image.
int getRows () const
Returns the number of rows of the image.
int getStep () const
Returns the step of the image.
Type * getData () const
Returns the pointer to the start of the device data for the image.
void resize (const int c, const int r)
Resizes a QVCUDAImage.
void uploadToDevice (const QVImage< Type, Channels > qvimage)
Uploads a (host) QVImage to a (device) QVCUDAImage.
void downloadFromDevice (QVImage< Type, Channels > &qvimage) const
Download a (device) QVCUDAImage to a (host) QVImage.
Detailed Description
template<typename Type, int Channels = 1>
class QVCUDAImage< Type, Channels >
Class to manage images stored in the GPU for the QVision framework.
This class is... //FIXME
Definition at line 47 of file qvcudaimage.h.
Constructor & Destructor Documentation
template<typename Type, int Channels = 1> QVCUDAImage< Type, Channels >::QVCUDAImage () [inline]
Default constructor for QVCUDAImage.
Constructs an empty QVCUDAImage.
Definition at line 53 of file qvcudaimage.h.
template<typename Type, int Channels = 1> QVCUDAImage< Type, Channels >::QVCUDAImage (QVImage< Type, Channels > qvimage) [inline]
Constructor for QVCUDAImage class from QVImage.
Constructs a QVCUDAImage which copies the contents of a QVImage when built.
Parameters:
qvimage Source QVImage.
Definition at line 59 of file qvcudaimage.h.
template<typename Type, int Channels = 1> QVCUDAImage< Type, Channels >::QVCUDAImage (const int c, const int r) [inline]
Constructor for QVCUDAImage class from scratch.
Constructs a new, empty QVCUDAImage with a given size.
Parameters:
c Number of requested cols.
r Number of requested rows.
Definition at line 69 of file qvcudaimage.h.
template<typename Type, int Channels = 1> QVCUDAImage< Type, Channels >::QVCUDAImage (const QVCUDAImage< Type, Channels > & src) [inline]
Copy constructor for QVCUDAImage class.
Definition at line 72 of file qvcudaimage.h.
template<typename Type, int Channels = 1> QVCUDAImage< Type, Channels >::~QVCUDAImage () [inline]
Destructor for QVCUDAImage class.
Definition at line 87 of file qvcudaimage.h.
Member Function Documentation
template<typename Type, int Channels = 1> QVCUDAImage& QVCUDAImage< Type, Channels >::operator= (const QVCUDAImage< Type, Channels > & src) [inline]
Assignment operator for QVCUDAImage class.
Definition at line 79 of file qvcudaimage.h.
template<typename Type, int Channels = 1> int QVCUDAImage< Type, Channels >::getCols () const [inline]
Returns the number of cols of the image.
Definition at line 90 of file qvcudaimage.h.
Referenced by QVCUDAImage< Type, Channels >::operator=(), QVCUDAFilterGauss(), QVCUDAImage< Type, Channels >::QVCUDAImage(), QVCUDAScaleDown(), QVCUDASubtract(), and QVCUDATest().
template<typename Type, int Channels = 1> int QVCUDAImage< Type, Channels >::getRows () const [inline]
Returns the number of rows of the image.
Definition at line 93 of file qvcudaimage.h.
Referenced by QVCUDAImage< Type, Channels >::operator=(), QVCUDAFilterGauss(), QVCUDAImage< Type, Channels >::QVCUDAImage(), QVCUDAScaleDown(), QVCUDASubtract(), and QVCUDATest().
template<typename Type, int Channels = 1> int QVCUDAImage< Type, Channels >::getStep () const [inline]
Returns the step of the image.
Definition at line 96 of file qvcudaimage.h.
Referenced by QVCUDAImage< Type, Channels >::operator=(), QVCUDAFilterGauss(), QVCUDAImage< Type, Channels >::QVCUDAImage(), QVCUDAScaleDown(), QVCUDASubtract(), and QVCUDATest().
template<typename Type, int Channels = 1> Type* QVCUDAImage< Type, Channels >::getData () const [inline]
Returns the pointer to the start of the device data for the image.
Definition at line 99 of file qvcudaimage.h.
Referenced by QVCUDAImage< Type, Channels >::operator=(), QVCUDAFilterGauss(), QVCUDAImage< Type, Channels >::QVCUDAImage(), QVCUDAScaleDown(), QVCUDASubtract(), and QVCUDATest().
template<typename Type, int Channels = 1> void QVCUDAImage< Type, Channels >::resize (const int c, const int r) [inline]
Resizes a QVCUDAImage.
The new image resizes to the new number of requested rows and cols (but completely discards the old image).
Parameters:
c Number of requested cols.
r Number of requested rows.
Definition at line 106 of file qvcudaimage.h.
Referenced by QVCUDAImage< Type, Channels >::operator=(), QVCUDAFilterGauss(), QVCUDAImage< Type, Channels >::QVCUDAImage(), QVCUDAScaleDown(), QVCUDASubtract(), QVCUDATest(), and QVCUDAImage< Type, Channels >::uploadToDevice().
template<typename Type, int Channels = 1> void QVCUDAImage< Type, Channels >::uploadToDevice (const QVImage< Type, Channels > qvimage) [inline]
Uploads a (host) QVImage to a (device) QVCUDAImage.
Definition at line 116 of file qvcudaimage.h.
Referenced by QVCUDAImage< Type, Channels >::QVCUDAImage().
template<typename Type, int Channels = 1> void QVCUDAImage< Type, Channels >::downloadFromDevice (QVImage< Type, Channels > & qvimage) const [inline]
Download a (device) QVCUDAImage to a (host) QVImage.
Definition at line 123 of file qvcudaimage.h.
The documentation for this class was generated from the following file:
src/qvcuda/qvcudaimage.h
QVision framework. PARP research group. Copyright © 2007, 2008, 2009, 2010, 2011.