QVision: Qt's Image, Video and Computer Vision Library
PARP Research Group Universidad de Murcia
Image Arithmetic and Logical Operations
[IPP wrapper functions]
Image processing functions that modify pixel values of an image using arithmetic or logical operations, and functions that perform image compositing based on opacity (alpha-blending).
Functions
void Add (const QVImage< uChar, 1 > &qvimage_pSrc1, const QVImage< uChar, 1 > &qvimage_pSrc2, QVImage< uChar, 1 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
Add image to accumulator.
void Add (const QVImage< uChar, 3 > &qvimage_pSrc1, const QVImage< uChar, 3 > &qvimage_pSrc2, QVImage< uChar, 3 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
Add image to accumulator.
void Add (const QVImage< uShort, 1 > &qvimage_pSrc1, const QVImage< uShort, 1 > &qvimage_pSrc2, QVImage< uShort, 1 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
Add image to accumulator.
void Add (const QVImage< uShort, 3 > &qvimage_pSrc1, const QVImage< uShort, 3 > &qvimage_pSrc2, QVImage< uShort, 3 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
Add image to accumulator.
void Add (const QVImage< sShort, 1 > &qvimage_pSrc1, const QVImage< sShort, 1 > &qvimage_pSrc2, QVImage< sShort, 1 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
Add image to accumulator.
void Add (const QVImage< sShort, 3 > &qvimage_pSrc1, const QVImage< sShort, 3 > &qvimage_pSrc2, QVImage< sShort, 3 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
Add image to accumulator.
void Add (const QVImage< sFloat, 1 > &qvimage_pSrc1, const QVImage< sFloat, 1 > &qvimage_pSrc2, QVImage< sFloat, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Add image to accumulator.
void Add (const QVImage< sFloat, 3 > &qvimage_pSrc1, const QVImage< sFloat, 3 > &qvimage_pSrc2, QVImage< sFloat, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Add image to accumulator.
void AddC (const QVImage< uChar, 1 > &qvimage_pSrc, const uChar value, QVImage< uChar, 1 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiAddC_8u_C1RSfs.
void AddC (const QVImage< uChar, 3 > &qvimage_pSrc, const uChar value[3], QVImage< uChar, 3 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiAddC_8u_C3RSfs.
void AddC (const QVImage< uShort, 1 > &qvimage_pSrc, const uShort value, QVImage< uShort, 1 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiAddC_16u_C1RSfs.
void AddC (const QVImage< uShort, 3 > &qvimage_pSrc, const uShort value[3], QVImage< uShort, 3 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiAddC_16u_C3RSfs.
void AddC (const QVImage< sShort, 1 > &qvimage_pSrc, const sShort value, QVImage< sShort, 1 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiAddC_16s_C1RSfs.
void AddC (const QVImage< sShort, 3 > &qvimage_pSrc, const sShort value[3], QVImage< sShort, 3 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiAddC_16s_C3RSfs.
void AddC (const QVImage< sFloat, 1 > &qvimage_pSrc, const sFloat value, QVImage< sFloat, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiAddC_32f_C1R.
void AddC (const QVImage< sFloat, 3 > &qvimage_pSrc, const sFloat value[3], QVImage< sFloat, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiAddC_32f_C3R.
void Mul (const QVImage< uChar, 1 > &qvimage_pSrc1, const QVImage< uChar, 1 > &qvimage_pSrc2, QVImage< uChar, 1 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
Adds, subtracts, or multiplies pixel values of two source images and places the results in a destination image.
void Mul (const QVImage< uChar, 3 > &qvimage_pSrc1, const QVImage< uChar, 3 > &qvimage_pSrc2, QVImage< uChar, 3 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
Adds, subtracts, or multiplies pixel values of two source images and places the results in a destination image.
void Mul (const QVImage< uShort, 1 > &qvimage_pSrc1, const QVImage< uShort, 1 > &qvimage_pSrc2, QVImage< uShort, 1 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
Adds, subtracts, or multiplies pixel values of two source images and places the results in a destination image.
void Mul (const QVImage< uShort, 3 > &qvimage_pSrc1, const QVImage< uShort, 3 > &qvimage_pSrc2, QVImage< uShort, 3 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
Adds, subtracts, or multiplies pixel values of two source images and places the results in a destination image.
void Mul (const QVImage< sShort, 1 > &qvimage_pSrc1, const QVImage< sShort, 1 > &qvimage_pSrc2, QVImage< sShort, 1 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
Adds, subtracts, or multiplies pixel values of two source images and places the results in a destination image.
void Mul (const QVImage< sShort, 3 > &qvimage_pSrc1, const QVImage< sShort, 3 > &qvimage_pSrc2, QVImage< sShort, 3 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
Adds, subtracts, or multiplies pixel values of two source images and places the results in a destination image.
void Mul (const QVImage< sFloat, 3 > &qvimage_pSrc1, const QVImage< sFloat, 3 > &qvimage_pSrc2, QVImage< sFloat, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Adds, subtracts, or multiplies pixel values of two source images and places the results in a destination image.
void Mul (const QVImage< sFloat, 1 > &qvimage_pSrc1, const QVImage< sFloat, 1 > &qvimage_pSrc2, QVImage< sFloat, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Adds, subtracts, or multiplies pixel values of two source images and places the results in a destination image.
void MulC (const QVImage< uChar, 1 > &qvimage_pSrc, const uChar value, QVImage< uChar, 1 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
Adds, subtracts, or multiplies pixel values of an image and a constant, and places the results in the same image.
void MulC (const QVImage< uChar, 3 > &qvimage_pSrc, const uChar value[3], QVImage< uChar, 3 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
Adds, subtracts, or multiplies pixel values of an image and a constant, and places the results in the same image.
void MulC (const QVImage< uShort, 1 > &qvimage_pSrc, const uShort value, QVImage< uShort, 1 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
Adds, subtracts, or multiplies pixel values of an image and a constant, and places the results in the same image.
void MulC (const QVImage< uShort, 3 > &qvimage_pSrc, const uShort value[3], QVImage< uShort, 3 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
Adds, subtracts, or multiplies pixel values of an image and a constant, and places the results in the same image.
void MulC (const QVImage< sShort, 1 > &qvimage_pSrc, const sShort value, QVImage< sShort, 1 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
Adds, subtracts, or multiplies pixel values of an image and a constant, and places the results in the same image.
void MulC (const QVImage< sShort, 3 > &qvimage_pSrc, const sShort value[3], QVImage< sShort, 3 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
Adds, subtracts, or multiplies pixel values of an image and a constant, and places the results in the same image.
void MulC (const QVImage< sFloat, 1 > &qvimage_pSrc, const sFloat value, QVImage< sFloat, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Adds, subtracts, or multiplies pixel values of an image and a constant, and places the results in the same image.
void MulC (const QVImage< sFloat, 3 > &qvimage_pSrc, const sFloat value[3], QVImage< sFloat, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Adds, subtracts, or multiplies pixel values of an image and a constant, and places the results in the same image.
void MulScale (const QVImage< uChar, 1 > &qvimage_pSrc1, const QVImage< uChar, 1 > &qvimage_pSrc2, QVImage< uChar, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiMulScale_8u_C1R.
void MulScale (const QVImage< uChar, 3 > &qvimage_pSrc1, const QVImage< uChar, 3 > &qvimage_pSrc2, QVImage< uChar, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiMulScale_8u_C3R.
void Sub (const QVImage< uChar, 1 > &qvimage_pSrc1, const QVImage< uChar, 1 > &qvimage_pSrc2, QVImage< uChar, 1 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiSub_8u_C1RSfs.
void Sub (const QVImage< uChar, 3 > &qvimage_pSrc1, const QVImage< uChar, 3 > &qvimage_pSrc2, QVImage< uChar, 3 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiSub_8u_C3RSfs.
void Sub (const QVImage< uShort, 1 > &qvimage_pSrc1, const QVImage< uShort, 1 > &qvimage_pSrc2, QVImage< uShort, 1 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiSub_16u_C1RSfs.
void Sub (const QVImage< uShort, 3 > &qvimage_pSrc1, const QVImage< uShort, 3 > &qvimage_pSrc2, QVImage< uShort, 3 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiSub_16u_C3RSfs.
void Sub (const QVImage< sShort, 1 > &qvimage_pSrc1, const QVImage< sShort, 1 > &qvimage_pSrc2, QVImage< sShort, 1 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiSub_16s_C1RSfs.
void Sub (const QVImage< sShort, 3 > &qvimage_pSrc1, const QVImage< sShort, 3 > &qvimage_pSrc2, QVImage< sShort, 3 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiSub_16s_C3RSfs.
void Sub (const QVImage< sFloat, 1 > &qvimage_pSrc1, const QVImage< sFloat, 1 > &qvimage_pSrc2, QVImage< sFloat, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiSub_32f_C1R.
void Sub (const QVImage< sFloat, 3 > &qvimage_pSrc1, const QVImage< sFloat, 3 > &qvimage_pSrc2, QVImage< sFloat, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiSub_32f_C3R.
void SubC (const QVImage< uChar, 1 > &qvimage_pSrc, const uChar value, QVImage< uChar, 1 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiSubC_8u_C1RSfs.
void SubC (const QVImage< uChar, 3 > &qvimage_pSrc, const uChar value[3], QVImage< uChar, 3 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiSubC_8u_C3RSfs.
void SubC (const QVImage< uShort, 1 > &qvimage_pSrc, const uShort value, QVImage< uShort, 1 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiSubC_16u_C1RSfs.
void SubC (const QVImage< sShort, 1 > &qvimage_pSrc, const sShort value, QVImage< sShort, 1 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiSubC_16s_C1RSfs.
void SubC (const QVImage< uShort, 3 > &qvimage_pSrc, const uShort value[3], QVImage< uShort, 3 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiSubC_16u_C3RSfs.
void SubC (const QVImage< sShort, 3 > &qvimage_pSrc, const sShort value[3], QVImage< sShort, 3 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiSubC_16s_C3RSfs.
void SubC (const QVImage< sFloat, 1 > &qvimage_pSrc, const sFloat value, QVImage< sFloat, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiSubC_32f_C1R.
void SubC (const QVImage< sFloat, 3 > &qvimage_pSrc, const sFloat value[3], QVImage< sFloat, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiSubC_32f_C3R.
void Div (const QVImage< uChar, 1 > &qvimage_pSrc1, const QVImage< uChar, 1 > &qvimage_pSrc2, QVImage< uChar, 1 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
Divides pixel values of an image by pixel values of another image and places the scaled results in the dividend source image.
void Div (const QVImage< uChar, 3 > &qvimage_pSrc1, const QVImage< uChar, 3 > &qvimage_pSrc2, QVImage< uChar, 3 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
Divides pixel values of an image by pixel values of another image and places the scaled results in the dividend source image.
void Div (const QVImage< uShort, 1 > &qvimage_pSrc1, const QVImage< uShort, 1 > &qvimage_pSrc2, QVImage< uShort, 1 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
Divides pixel values of an image by pixel values of another image and places the scaled results in the dividend source image.
void Div (const QVImage< uShort, 3 > &qvimage_pSrc1, const QVImage< uShort, 3 > &qvimage_pSrc2, QVImage< uShort, 3 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
Divides pixel values of an image by pixel values of another image and places the scaled results in the dividend source image.
void Div (const QVImage< sShort, 1 > &qvimage_pSrc1, const QVImage< sShort, 1 > &qvimage_pSrc2, QVImage< sShort, 1 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
Divides pixel values of an image by pixel values of another image and places the scaled results in the dividend source image.
void Div (const QVImage< sShort, 3 > &qvimage_pSrc1, const QVImage< sShort, 3 > &qvimage_pSrc2, QVImage< sShort, 3 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
Divides pixel values of an image by pixel values of another image and places the scaled results in the dividend source image.
void Div (const QVImage< sFloat, 3 > &qvimage_pSrc1, const QVImage< sFloat, 3 > &qvimage_pSrc2, QVImage< sFloat, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Divides pixel values of an image by pixel values of another image and places the scaled results in the dividend source image.
void Div (const QVImage< sFloat, 1 > &qvimage_pSrc1, const QVImage< sFloat, 1 > &qvimage_pSrc2, QVImage< sFloat, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Divides pixel values of an image by pixel values of another image and places the scaled results in the dividend source image.
void DivC (const QVImage< uChar, 1 > &qvimage_pSrc, const uChar value, QVImage< uChar, 1 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
Divides pixel values of a source image by a constant and places the scaled results in the same image.
void DivC (const QVImage< uChar, 3 > &qvimage_pSrc, const uChar value[3], QVImage< uChar, 3 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
Divides pixel values of a source image by a constant and places the scaled results in the same image.
void DivC (const QVImage< uShort, 1 > &qvimage_pSrc, const uShort value, QVImage< uShort, 1 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
Divides pixel values of a source image by a constant and places the scaled results in the same image.
void DivC (const QVImage< uShort, 3 > &qvimage_pSrc, const uShort value[3], QVImage< uShort, 3 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
Divides pixel values of a source image by a constant and places the scaled results in the same image.
void DivC (const QVImage< sShort, 1 > &qvimage_pSrc, const sShort value, QVImage< sShort, 1 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
Divides pixel values of a source image by a constant and places the scaled results in the same image.
void DivC (const QVImage< sShort, 3 > &qvimage_pSrc, const sShort value[3], QVImage< sShort, 3 > &qvimage_pDst, const int scaleFactor=1, const QPoint &destROIOffset=QPoint(0, 0))
Divides pixel values of a source image by a constant and places the scaled results in the same image.
void DivC (const QVImage< sFloat, 1 > &qvimage_pSrc, const sFloat value, QVImage< sFloat, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Divides pixel values of a source image by a constant and places the scaled results in the same image.
void DivC (const QVImage< sFloat, 3 > &qvimage_pSrc, const sFloat value[3], QVImage< sFloat, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Divides pixel values of a source image by a constant and places the scaled results in the same image.
void Abs (const QVImage< sShort, 1 > &qvimage_pSrc, QVImage< sShort, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Computes absolute value of each pixel of a source image and places results in the destination image; for in-place flavors - in the same source image.
void Abs (const QVImage< sFloat, 1 > &qvimage_pSrc, QVImage< sFloat, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Computes absolute value of each pixel of a source image and places results in the destination image; for in-place flavors - in the same source image.
void AbsDiff (const QVImage< uChar, 1 > &qvimage_pSrc1, const QVImage< uChar, 1 > &qvimage_pSrc2, QVImage< uChar, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Calculate absolute difference between corresponding pixels of the two images or between image pixels and scalar.
void AbsDiff (const QVImage< sFloat, 1 > &qvimage_pSrc1, const QVImage< sFloat, 1 > &qvimage_pSrc2, QVImage< sFloat, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Calculate absolute difference between corresponding pixels of the two images or between image pixels and scalar.
void Sqr (const QVImage< sFloat, 1 > &qvimage_pSrc, QVImage< sFloat, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Squares pixel values of an image and places results in the destination image; for in-place flavors - in the same image.
void Ln (const QVImage< sFloat, 1 > &qvimage_pSrc, QVImage< sFloat, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Computes the natural logarithm of each pixel values of a source image and places the results in the destination image; for in-place flavors - in the same image.
void Ln (const QVImage< sFloat, 3 > &qvimage_pSrc, QVImage< sFloat, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Computes the natural logarithm of each pixel values of a source image and places the results in the destination image; for in-place flavors - in the same image.
void And (const QVImage< uChar, 1 > &qvimage_pSrc1, const QVImage< uChar, 1 > &qvimage_pSrc2, QVImage< uChar, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiAnd_8u_C1R.
void And (const QVImage< uChar, 3 > &qvimage_pSrc1, const QVImage< uChar, 3 > &qvimage_pSrc2, QVImage< uChar, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiAnd_8u_C3R.
void And (const QVImage< uShort, 1 > &qvimage_pSrc1, const QVImage< uShort, 1 > &qvimage_pSrc2, QVImage< uShort, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiAnd_16u_C1R.
void And (const QVImage< uShort, 3 > &qvimage_pSrc1, const QVImage< uShort, 3 > &qvimage_pSrc2, QVImage< uShort, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiAnd_16u_C3R.
void And (const QVImage< sInt, 1 > &qvimage_pSrc1, const QVImage< sInt, 1 > &qvimage_pSrc2, QVImage< sInt, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiAnd_32s_C1R.
void And (const QVImage< sInt, 3 > &qvimage_pSrc1, const QVImage< sInt, 3 > &qvimage_pSrc2, QVImage< sInt, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiAnd_32s_C3R.
void Or (const QVImage< uChar, 1 > &qvimage_pSrc1, const QVImage< uChar, 1 > &qvimage_pSrc2, QVImage< uChar, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiOr_8u_C1R.
void Or (const QVImage< uChar, 3 > &qvimage_pSrc1, const QVImage< uChar, 3 > &qvimage_pSrc2, QVImage< uChar, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiOr_8u_C3R.
void Or (const QVImage< uShort, 1 > &qvimage_pSrc1, const QVImage< uShort, 1 > &qvimage_pSrc2, QVImage< uShort, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiOr_16u_C1R.
void Or (const QVImage< uShort, 3 > &qvimage_pSrc1, const QVImage< uShort, 3 > &qvimage_pSrc2, QVImage< uShort, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiOr_16u_C3R.
void Or (const QVImage< sInt, 1 > &qvimage_pSrc1, const QVImage< sInt, 1 > &qvimage_pSrc2, QVImage< sInt, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiOr_32s_C1R.
void Or (const QVImage< sInt, 3 > &qvimage_pSrc1, const QVImage< sInt, 3 > &qvimage_pSrc2, QVImage< sInt, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiOr_32s_C3R.
void Xor (const QVImage< uChar, 1 > &qvimage_pSrc1, const QVImage< uChar, 1 > &qvimage_pSrc2, QVImage< uChar, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiXor_8u_C1R.
void Xor (const QVImage< uChar, 3 > &qvimage_pSrc1, const QVImage< uChar, 3 > &qvimage_pSrc2, QVImage< uChar, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiXor_8u_C3R.
void Xor (const QVImage< uShort, 1 > &qvimage_pSrc1, const QVImage< uShort, 1 > &qvimage_pSrc2, QVImage< uShort, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiXor_16u_C1R.
void Xor (const QVImage< uShort, 3 > &qvimage_pSrc1, const QVImage< uShort, 3 > &qvimage_pSrc2, QVImage< uShort, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiXor_16u_C3R.
void Xor (const QVImage< sInt, 1 > &qvimage_pSrc1, const QVImage< sInt, 1 > &qvimage_pSrc2, QVImage< sInt, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiXor_32s_C1R.
void Xor (const QVImage< sInt, 3 > &qvimage_pSrc1, const QVImage< sInt, 3 > &qvimage_pSrc2, QVImage< sInt, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiXor_32s_C3R.
void Not (const QVImage< uChar, 1 > &qvimage_pSrc, QVImage< uChar, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Performs corresponding bitwise logical operation between pixels of two image (AndC OrC XorC - between pixel of the source image and a constant).
void Not (const QVImage< uChar, 3 > &qvimage_pSrc, QVImage< uChar, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Performs corresponding bitwise logical operation between pixels of two image (AndC OrC XorC - between pixel of the source image and a constant).
void AndC (const QVImage< uChar, 1 > &qvimage_pSrc, const uChar value, QVImage< uChar, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiAndC_8u_C1R.
void AndC (const QVImage< uChar, 3 > &qvimage_pSrc, const uChar value[3], QVImage< uChar, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiAndC_8u_C3R.
void AndC (const QVImage< uShort, 1 > &qvimage_pSrc, const uShort value, QVImage< uShort, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiAndC_16u_C1R.
void AndC (const QVImage< uShort, 3 > &qvimage_pSrc, const uShort value[3], QVImage< uShort, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiAndC_16u_C3R.
void AndC (const QVImage< sInt, 1 > &qvimage_pSrc, const sInt value, QVImage< sInt, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiAndC_32s_C1R.
void AndC (const QVImage< sInt, 3 > &qvimage_pSrc, const sInt value[3], QVImage< sInt, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiAndC_32s_C3R.
void OrC (const QVImage< uChar, 1 > &qvimage_pSrc, const uChar value, QVImage< uChar, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiOrC_8u_C1R.
void OrC (const QVImage< uChar, 3 > &qvimage_pSrc, const uChar value[3], QVImage< uChar, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiOrC_8u_C3R.
void OrC (const QVImage< uShort, 1 > &qvimage_pSrc, const uShort value, QVImage< uShort, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiOrC_16u_C1R.
void OrC (const QVImage< uShort, 3 > &qvimage_pSrc, const uShort value[3], QVImage< uShort, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiOrC_16u_C3R.
void OrC (const QVImage< sInt, 1 > &qvimage_pSrc, const sInt value, QVImage< sInt, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiOrC_32s_C1R.
void OrC (const QVImage< sInt, 3 > &qvimage_pSrc, const sInt value[3], QVImage< sInt, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiOrC_32s_C3R.
void XorC (const QVImage< uChar, 1 > &qvimage_pSrc, const uChar value, QVImage< uChar, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiXorC_8u_C1R.
void XorC (const QVImage< uChar, 3 > &qvimage_pSrc, const uChar value[3], QVImage< uChar, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiXorC_8u_C3R.
void XorC (const QVImage< uShort, 1 > &qvimage_pSrc, const uShort value, QVImage< uShort, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiXorC_16u_C1R.
void XorC (const QVImage< uShort, 3 > &qvimage_pSrc, const uShort value[3], QVImage< uShort, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiXorC_16u_C3R.
void XorC (const QVImage< sInt, 1 > &qvimage_pSrc, const sInt value, QVImage< sInt, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiXorC_32s_C1R.
void XorC (const QVImage< sInt, 3 > &qvimage_pSrc, const sInt value[3], QVImage< sInt, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiXorC_32s_C3R.
void LShiftC (const QVImage< uChar, 1 > &qvimage_pSrc, const uInt value, QVImage< uChar, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiLShiftC_8u_C1R.
void LShiftC (const QVImage< uChar, 3 > &qvimage_pSrc, const uInt value[3], QVImage< uChar, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiLShiftC_8u_C3R.
void RShiftC (const QVImage< uChar, 1 > &qvimage_pSrc, const uInt value, QVImage< uChar, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiRShiftC_8u_C1R.
void RShiftC (const QVImage< uChar, 3 > &qvimage_pSrc, const uInt value[3], QVImage< uChar, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiRShiftC_8u_C3R.
void LShiftC (const QVImage< uShort, 1 > &qvimage_pSrc, const uInt value, QVImage< uShort, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiLShiftC_16u_C1R.
void LShiftC (const QVImage< uShort, 3 > &qvimage_pSrc, const uInt value[3], QVImage< uShort, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiLShiftC_16u_C3R.
void RShiftC (const QVImage< uShort, 1 > &qvimage_pSrc, const uInt value, QVImage< uShort, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiRShiftC_16u_C1R.
void RShiftC (const QVImage< uShort, 3 > &qvimage_pSrc, const uInt value[3], QVImage< uShort, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiRShiftC_16u_C3R.
void LShiftC (const QVImage< sInt, 1 > &qvimage_pSrc, const uInt value, QVImage< sInt, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiLShiftC_32s_C1R.
void LShiftC (const QVImage< sInt, 3 > &qvimage_pSrc, const uInt value[3], QVImage< sInt, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiLShiftC_32s_C3R.
void RShiftC (const QVImage< sInt, 1 > &qvimage_pSrc, const uInt value, QVImage< sInt, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiRShiftC_32s_C1R.
void RShiftC (const QVImage< sInt, 3 > &qvimage_pSrc, const uInt value[3], QVImage< sInt, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiRShiftC_32s_C3R.
Detailed Description
Image processing functions that modify pixel values of an image using arithmetic or logical operations, and functions that perform image compositing based on opacity (alpha-blending).
Function Documentation
void Add (const QVImage< uChar, 1 > & qvimage_pSrc1, const QVImage< uChar, 1 > & qvimage_pSrc2, QVImage< uChar, 1 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
Add image to accumulator.
This is the QVision wrapper function for IPP's ippiAdd_8u_C1RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 887 of file qvippfunctions.cpp.
Referenced by Add(), QVAdd_sFloatC3Block::iterate(), QVAdd_sFloatC1Block::iterate(), QVAdd_uCharC3Block::iterate(), and QVAdd_uCharC1Block::iterate().
void Add (const QVImage< uChar, 3 > & qvimage_pSrc1, const QVImage< uChar, 3 > & qvimage_pSrc2, QVImage< uChar, 3 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
Add image to accumulator.
This is the QVision wrapper function for IPP's ippiAdd_8u_C3RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 906 of file qvippfunctions.cpp.
void Add (const QVImage< uShort, 1 > & qvimage_pSrc1, const QVImage< uShort, 1 > & qvimage_pSrc2, QVImage< uShort, 1 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
Add image to accumulator.
This is the QVision wrapper function for IPP's ippiAdd_16u_C1RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 925 of file qvippfunctions.cpp.
void Add (const QVImage< uShort, 3 > & qvimage_pSrc1, const QVImage< uShort, 3 > & qvimage_pSrc2, QVImage< uShort, 3 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
Add image to accumulator.
This is the QVision wrapper function for IPP's ippiAdd_16u_C3RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 944 of file qvippfunctions.cpp.
void Add (const QVImage< sShort, 1 > & qvimage_pSrc1, const QVImage< sShort, 1 > & qvimage_pSrc2, QVImage< sShort, 1 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
Add image to accumulator.
This is the QVision wrapper function for IPP's ippiAdd_16s_C1RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 963 of file qvippfunctions.cpp.
void Add (const QVImage< sShort, 3 > & qvimage_pSrc1, const QVImage< sShort, 3 > & qvimage_pSrc2, QVImage< sShort, 3 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
Add image to accumulator.
This is the QVision wrapper function for IPP's ippiAdd_16s_C3RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 982 of file qvippfunctions.cpp.
void Add (const QVImage< sFloat, 1 > & qvimage_pSrc1, const QVImage< sFloat, 1 > & qvimage_pSrc2, QVImage< sFloat, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Add image to accumulator.
This is the QVision wrapper function for IPP's ippiAdd_32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1001 of file qvippfunctions.cpp.
void Add (const QVImage< sFloat, 3 > & qvimage_pSrc1, const QVImage< sFloat, 3 > & qvimage_pSrc2, QVImage< sFloat, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Add image to accumulator.
This is the QVision wrapper function for IPP's ippiAdd_32f_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1018 of file qvippfunctions.cpp.
void AddC (const QVImage< uChar, 1 > & qvimage_pSrc, const uChar value, QVImage< uChar, 1 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiAddC_8u_C1RSfs.
This is the QVision wrapper function for IPP's ippiAddC_8u_C1RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1035 of file qvippfunctions.cpp.
Referenced by AddC(), QVAddC_sFloatC1Block::iterate(), and QVAddC_uCharC1Block::iterate().
void AddC (const QVImage< uChar, 3 > & qvimage_pSrc, const uChar value[3], QVImage< uChar, 3 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiAddC_8u_C3RSfs.
This is the QVision wrapper function for IPP's ippiAddC_8u_C3RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1053 of file qvippfunctions.cpp.
void AddC (const QVImage< uShort, 1 > & qvimage_pSrc, const uShort value, QVImage< uShort, 1 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiAddC_16u_C1RSfs.
This is the QVision wrapper function for IPP's ippiAddC_16u_C1RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1071 of file qvippfunctions.cpp.
void AddC (const QVImage< uShort, 3 > & qvimage_pSrc, const uShort value[3], QVImage< uShort, 3 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiAddC_16u_C3RSfs.
This is the QVision wrapper function for IPP's ippiAddC_16u_C3RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1089 of file qvippfunctions.cpp.
void AddC (const QVImage< sShort, 1 > & qvimage_pSrc, const sShort value, QVImage< sShort, 1 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiAddC_16s_C1RSfs.
This is the QVision wrapper function for IPP's ippiAddC_16s_C1RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1107 of file qvippfunctions.cpp.
void AddC (const QVImage< sShort, 3 > & qvimage_pSrc, const sShort value[3], QVImage< sShort, 3 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiAddC_16s_C3RSfs.
This is the QVision wrapper function for IPP's ippiAddC_16s_C3RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1125 of file qvippfunctions.cpp.
void AddC (const QVImage< sFloat, 1 > & qvimage_pSrc, const sFloat value, QVImage< sFloat, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiAddC_32f_C1R.
This is the QVision wrapper function for IPP's ippiAddC_32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1143 of file qvippfunctions.cpp.
void AddC (const QVImage< sFloat, 3 > & qvimage_pSrc, const sFloat value[3], QVImage< sFloat, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiAddC_32f_C3R.
This is the QVision wrapper function for IPP's ippiAddC_32f_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1159 of file qvippfunctions.cpp.
void Mul (const QVImage< uChar, 1 > & qvimage_pSrc1, const QVImage< uChar, 1 > & qvimage_pSrc2, QVImage< uChar, 1 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
Adds, subtracts, or multiplies pixel values of two source images and places the results in a destination image.
This is the QVision wrapper function for IPP's ippiMul_8u_C1RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1175 of file qvippfunctions.cpp.
Referenced by FilterHessianCornerResponseImage(), QVMul_sFloatC1Block::iterate(), QVMul_sFloatC3Block::iterate(), QVMul_uCharC3Block::iterate(), QVMul_uCharC1Block::iterate(), and Mul().
void Mul (const QVImage< uChar, 3 > & qvimage_pSrc1, const QVImage< uChar, 3 > & qvimage_pSrc2, QVImage< uChar, 3 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
Adds, subtracts, or multiplies pixel values of two source images and places the results in a destination image.
This is the QVision wrapper function for IPP's ippiMul_8u_C3RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1194 of file qvippfunctions.cpp.
void Mul (const QVImage< uShort, 1 > & qvimage_pSrc1, const QVImage< uShort, 1 > & qvimage_pSrc2, QVImage< uShort, 1 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
Adds, subtracts, or multiplies pixel values of two source images and places the results in a destination image.
This is the QVision wrapper function for IPP's ippiMul_16u_C1RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1213 of file qvippfunctions.cpp.
void Mul (const QVImage< uShort, 3 > & qvimage_pSrc1, const QVImage< uShort, 3 > & qvimage_pSrc2, QVImage< uShort, 3 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
Adds, subtracts, or multiplies pixel values of two source images and places the results in a destination image.
This is the QVision wrapper function for IPP's ippiMul_16u_C3RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1232 of file qvippfunctions.cpp.
void Mul (const QVImage< sShort, 1 > & qvimage_pSrc1, const QVImage< sShort, 1 > & qvimage_pSrc2, QVImage< sShort, 1 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
Adds, subtracts, or multiplies pixel values of two source images and places the results in a destination image.
This is the QVision wrapper function for IPP's ippiMul_16s_C1RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1251 of file qvippfunctions.cpp.
void Mul (const QVImage< sShort, 3 > & qvimage_pSrc1, const QVImage< sShort, 3 > & qvimage_pSrc2, QVImage< sShort, 3 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
Adds, subtracts, or multiplies pixel values of two source images and places the results in a destination image.
This is the QVision wrapper function for IPP's ippiMul_16s_C3RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1270 of file qvippfunctions.cpp.
void Mul (const QVImage< sFloat, 3 > & qvimage_pSrc1, const QVImage< sFloat, 3 > & qvimage_pSrc2, QVImage< sFloat, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Adds, subtracts, or multiplies pixel values of two source images and places the results in a destination image.
This is the QVision wrapper function for IPP's ippiMul_32f_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1289 of file qvippfunctions.cpp.
void Mul (const QVImage< sFloat, 1 > & qvimage_pSrc1, const QVImage< sFloat, 1 > & qvimage_pSrc2, QVImage< sFloat, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Adds, subtracts, or multiplies pixel values of two source images and places the results in a destination image.
This is the QVision wrapper function for IPP's ippiMul_32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1306 of file qvippfunctions.cpp.
void MulC (const QVImage< uChar, 1 > & qvimage_pSrc, const uChar value, QVImage< uChar, 1 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
Adds, subtracts, or multiplies pixel values of an image and a constant, and places the results in the same image.
This is the QVision wrapper function for IPP's ippiMulC_8u_C1RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1323 of file qvippfunctions.cpp.
Referenced by QVMulC_sFloatC1Block::iterate(), QVMulC_uCharC1Block::iterate(), and MulC().
void MulC (const QVImage< uChar, 3 > & qvimage_pSrc, const uChar value[3], QVImage< uChar, 3 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
Adds, subtracts, or multiplies pixel values of an image and a constant, and places the results in the same image.
This is the QVision wrapper function for IPP's ippiMulC_8u_C3RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1341 of file qvippfunctions.cpp.
void MulC (const QVImage< uShort, 1 > & qvimage_pSrc, const uShort value, QVImage< uShort, 1 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
Adds, subtracts, or multiplies pixel values of an image and a constant, and places the results in the same image.
This is the QVision wrapper function for IPP's ippiMulC_16u_C1RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1359 of file qvippfunctions.cpp.
void MulC (const QVImage< uShort, 3 > & qvimage_pSrc, const uShort value[3], QVImage< uShort, 3 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
Adds, subtracts, or multiplies pixel values of an image and a constant, and places the results in the same image.
This is the QVision wrapper function for IPP's ippiMulC_16u_C3RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1377 of file qvippfunctions.cpp.
void MulC (const QVImage< sShort, 1 > & qvimage_pSrc, const sShort value, QVImage< sShort, 1 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
Adds, subtracts, or multiplies pixel values of an image and a constant, and places the results in the same image.
This is the QVision wrapper function for IPP's ippiMulC_16s_C1RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1395 of file qvippfunctions.cpp.
void MulC (const QVImage< sShort, 3 > & qvimage_pSrc, const sShort value[3], QVImage< sShort, 3 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
Adds, subtracts, or multiplies pixel values of an image and a constant, and places the results in the same image.
This is the QVision wrapper function for IPP's ippiMulC_16s_C3RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1413 of file qvippfunctions.cpp.
void MulC (const QVImage< sFloat, 1 > & qvimage_pSrc, const sFloat value, QVImage< sFloat, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Adds, subtracts, or multiplies pixel values of an image and a constant, and places the results in the same image.
This is the QVision wrapper function for IPP's ippiMulC_32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1431 of file qvippfunctions.cpp.
void MulC (const QVImage< sFloat, 3 > & qvimage_pSrc, const sFloat value[3], QVImage< sFloat, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Adds, subtracts, or multiplies pixel values of an image and a constant, and places the results in the same image.
This is the QVision wrapper function for IPP's ippiMulC_32f_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1447 of file qvippfunctions.cpp.
void MulScale (const QVImage< uChar, 1 > & qvimage_pSrc1, const QVImage< uChar, 1 > & qvimage_pSrc2, QVImage< uChar, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiMulScale_8u_C1R.
This is the QVision wrapper function for IPP's ippiMulScale_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1463 of file qvippfunctions.cpp.
Referenced by QVMulScale_uCharC3Block::iterate(), QVMulScale_uCharC1Block::iterate(), and MulScale().
void MulScale (const QVImage< uChar, 3 > & qvimage_pSrc1, const QVImage< uChar, 3 > & qvimage_pSrc2, QVImage< uChar, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiMulScale_8u_C3R.
This is the QVision wrapper function for IPP's ippiMulScale_8u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1480 of file qvippfunctions.cpp.
void Sub (const QVImage< uChar, 1 > & qvimage_pSrc1, const QVImage< uChar, 1 > & qvimage_pSrc2, QVImage< uChar, 1 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiSub_8u_C1RSfs.
This is the QVision wrapper function for IPP's ippiSub_8u_C1RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1497 of file qvippfunctions.cpp.
Referenced by QVSub_sFloatC3Block::iterate(), QVSub_sFloatC1Block::iterate(), QVSub_uCharC3Block::iterate(), QVSub_uCharC1Block::iterate(), and Sub().
void Sub (const QVImage< uChar, 3 > & qvimage_pSrc1, const QVImage< uChar, 3 > & qvimage_pSrc2, QVImage< uChar, 3 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiSub_8u_C3RSfs.
This is the QVision wrapper function for IPP's ippiSub_8u_C3RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1516 of file qvippfunctions.cpp.
void Sub (const QVImage< uShort, 1 > & qvimage_pSrc1, const QVImage< uShort, 1 > & qvimage_pSrc2, QVImage< uShort, 1 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiSub_16u_C1RSfs.
This is the QVision wrapper function for IPP's ippiSub_16u_C1RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1535 of file qvippfunctions.cpp.
void Sub (const QVImage< uShort, 3 > & qvimage_pSrc1, const QVImage< uShort, 3 > & qvimage_pSrc2, QVImage< uShort, 3 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiSub_16u_C3RSfs.
This is the QVision wrapper function for IPP's ippiSub_16u_C3RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1554 of file qvippfunctions.cpp.
void Sub (const QVImage< sShort, 1 > & qvimage_pSrc1, const QVImage< sShort, 1 > & qvimage_pSrc2, QVImage< sShort, 1 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiSub_16s_C1RSfs.
This is the QVision wrapper function for IPP's ippiSub_16s_C1RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1573 of file qvippfunctions.cpp.
void Sub (const QVImage< sShort, 3 > & qvimage_pSrc1, const QVImage< sShort, 3 > & qvimage_pSrc2, QVImage< sShort, 3 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiSub_16s_C3RSfs.
This is the QVision wrapper function for IPP's ippiSub_16s_C3RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1592 of file qvippfunctions.cpp.
void Sub (const QVImage< sFloat, 1 > & qvimage_pSrc1, const QVImage< sFloat, 1 > & qvimage_pSrc2, QVImage< sFloat, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiSub_32f_C1R.
This is the QVision wrapper function for IPP's ippiSub_32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1611 of file qvippfunctions.cpp.
void Sub (const QVImage< sFloat, 3 > & qvimage_pSrc1, const QVImage< sFloat, 3 > & qvimage_pSrc2, QVImage< sFloat, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiSub_32f_C3R.
This is the QVision wrapper function for IPP's ippiSub_32f_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1628 of file qvippfunctions.cpp.
void SubC (const QVImage< uChar, 1 > & qvimage_pSrc, const uChar value, QVImage< uChar, 1 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiSubC_8u_C1RSfs.
This is the QVision wrapper function for IPP's ippiSubC_8u_C1RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1645 of file qvippfunctions.cpp.
Referenced by QVSubC_sFloatC1Block::iterate(), QVSubC_uCharC1Block::iterate(), and SubC().
void SubC (const QVImage< uChar, 3 > & qvimage_pSrc, const uChar value[3], QVImage< uChar, 3 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiSubC_8u_C3RSfs.
This is the QVision wrapper function for IPP's ippiSubC_8u_C3RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1663 of file qvippfunctions.cpp.
void SubC (const QVImage< uShort, 1 > & qvimage_pSrc, const uShort value, QVImage< uShort, 1 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiSubC_16u_C1RSfs.
This is the QVision wrapper function for IPP's ippiSubC_16u_C1RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1681 of file qvippfunctions.cpp.
void SubC (const QVImage< sShort, 1 > & qvimage_pSrc, const sShort value, QVImage< sShort, 1 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiSubC_16s_C1RSfs.
This is the QVision wrapper function for IPP's ippiSubC_16s_C1RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1699 of file qvippfunctions.cpp.
void SubC (const QVImage< uShort, 3 > & qvimage_pSrc, const uShort value[3], QVImage< uShort, 3 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiSubC_16u_C3RSfs.
This is the QVision wrapper function for IPP's ippiSubC_16u_C3RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1717 of file qvippfunctions.cpp.
void SubC (const QVImage< sShort, 3 > & qvimage_pSrc, const sShort value[3], QVImage< sShort, 3 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiSubC_16s_C3RSfs.
This is the QVision wrapper function for IPP's ippiSubC_16s_C3RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1735 of file qvippfunctions.cpp.
void SubC (const QVImage< sFloat, 1 > & qvimage_pSrc, const sFloat value, QVImage< sFloat, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiSubC_32f_C1R.
This is the QVision wrapper function for IPP's ippiSubC_32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1753 of file qvippfunctions.cpp.
void SubC (const QVImage< sFloat, 3 > & qvimage_pSrc, const sFloat value[3], QVImage< sFloat, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiSubC_32f_C3R.
This is the QVision wrapper function for IPP's ippiSubC_32f_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1769 of file qvippfunctions.cpp.
void Div (const QVImage< uChar, 1 > & qvimage_pSrc1, const QVImage< uChar, 1 > & qvimage_pSrc2, QVImage< uChar, 1 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
Divides pixel values of an image by pixel values of another image and places the scaled results in the dividend source image.
This is the QVision wrapper function for IPP's ippiDiv_8u_C1RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1785 of file qvippfunctions.cpp.
Referenced by Div(), QVDiv_sFloatC1Block::iterate(), QVDiv_sFloatC3Block::iterate(), QVDiv_uCharC3Block::iterate(), and QVDiv_uCharC1Block::iterate().
void Div (const QVImage< uChar, 3 > & qvimage_pSrc1, const QVImage< uChar, 3 > & qvimage_pSrc2, QVImage< uChar, 3 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
Divides pixel values of an image by pixel values of another image and places the scaled results in the dividend source image.
This is the QVision wrapper function for IPP's ippiDiv_8u_C3RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1804 of file qvippfunctions.cpp.
void Div (const QVImage< uShort, 1 > & qvimage_pSrc1, const QVImage< uShort, 1 > & qvimage_pSrc2, QVImage< uShort, 1 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
Divides pixel values of an image by pixel values of another image and places the scaled results in the dividend source image.
This is the QVision wrapper function for IPP's ippiDiv_16u_C1RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1823 of file qvippfunctions.cpp.
void Div (const QVImage< uShort, 3 > & qvimage_pSrc1, const QVImage< uShort, 3 > & qvimage_pSrc2, QVImage< uShort, 3 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
Divides pixel values of an image by pixel values of another image and places the scaled results in the dividend source image.
This is the QVision wrapper function for IPP's ippiDiv_16u_C3RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1842 of file qvippfunctions.cpp.
void Div (const QVImage< sShort, 1 > & qvimage_pSrc1, const QVImage< sShort, 1 > & qvimage_pSrc2, QVImage< sShort, 1 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
Divides pixel values of an image by pixel values of another image and places the scaled results in the dividend source image.
This is the QVision wrapper function for IPP's ippiDiv_16s_C1RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1861 of file qvippfunctions.cpp.
void Div (const QVImage< sShort, 3 > & qvimage_pSrc1, const QVImage< sShort, 3 > & qvimage_pSrc2, QVImage< sShort, 3 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
Divides pixel values of an image by pixel values of another image and places the scaled results in the dividend source image.
This is the QVision wrapper function for IPP's ippiDiv_16s_C3RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1880 of file qvippfunctions.cpp.
void Div (const QVImage< sFloat, 3 > & qvimage_pSrc1, const QVImage< sFloat, 3 > & qvimage_pSrc2, QVImage< sFloat, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Divides pixel values of an image by pixel values of another image and places the scaled results in the dividend source image.
This is the QVision wrapper function for IPP's ippiDiv_32f_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1899 of file qvippfunctions.cpp.
void Div (const QVImage< sFloat, 1 > & qvimage_pSrc1, const QVImage< sFloat, 1 > & qvimage_pSrc2, QVImage< sFloat, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Divides pixel values of an image by pixel values of another image and places the scaled results in the dividend source image.
This is the QVision wrapper function for IPP's ippiDiv_32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1916 of file qvippfunctions.cpp.
void DivC (const QVImage< uChar, 1 > & qvimage_pSrc, const uChar value, QVImage< uChar, 1 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
Divides pixel values of a source image by a constant and places the scaled results in the same image.
This is the QVision wrapper function for IPP's ippiDivC_8u_C1RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1933 of file qvippfunctions.cpp.
Referenced by DivC(), QVDivC_sFloatC1Block::iterate(), and QVDivC_uCharC1Block::iterate().
void DivC (const QVImage< uChar, 3 > & qvimage_pSrc, const uChar value[3], QVImage< uChar, 3 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
Divides pixel values of a source image by a constant and places the scaled results in the same image.
This is the QVision wrapper function for IPP's ippiDivC_8u_C3RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1951 of file qvippfunctions.cpp.
void DivC (const QVImage< uShort, 1 > & qvimage_pSrc, const uShort value, QVImage< uShort, 1 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
Divides pixel values of a source image by a constant and places the scaled results in the same image.
This is the QVision wrapper function for IPP's ippiDivC_16u_C1RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1969 of file qvippfunctions.cpp.
void DivC (const QVImage< uShort, 3 > & qvimage_pSrc, const uShort value[3], QVImage< uShort, 3 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
Divides pixel values of a source image by a constant and places the scaled results in the same image.
This is the QVision wrapper function for IPP's ippiDivC_16u_C3RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 1987 of file qvippfunctions.cpp.
void DivC (const QVImage< sShort, 1 > & qvimage_pSrc, const sShort value, QVImage< sShort, 1 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
Divides pixel values of a source image by a constant and places the scaled results in the same image.
This is the QVision wrapper function for IPP's ippiDivC_16s_C1RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2005 of file qvippfunctions.cpp.
void DivC (const QVImage< sShort, 3 > & qvimage_pSrc, const sShort value[3], QVImage< sShort, 3 > & qvimage_pDst, const int scaleFactor = 1, const QPoint & destROIOffset = QPoint(0, 0))
Divides pixel values of a source image by a constant and places the scaled results in the same image.
This is the QVision wrapper function for IPP's ippiDivC_16s_C3RSfs. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
scaleFactor Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2023 of file qvippfunctions.cpp.
void DivC (const QVImage< sFloat, 1 > & qvimage_pSrc, const sFloat value, QVImage< sFloat, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Divides pixel values of a source image by a constant and places the scaled results in the same image.
This is the QVision wrapper function for IPP's ippiDivC_32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2041 of file qvippfunctions.cpp.
void DivC (const QVImage< sFloat, 3 > & qvimage_pSrc, const sFloat value[3], QVImage< sFloat, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Divides pixel values of a source image by a constant and places the scaled results in the same image.
This is the QVision wrapper function for IPP's ippiDivC_32f_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2057 of file qvippfunctions.cpp.
void Abs (const QVImage< sShort, 1 > & qvimage_pSrc, QVImage< sShort, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Computes absolute value of each pixel of a source image and places results in the destination image; for in-place flavors - in the same source image.
This is the QVision wrapper function for IPP's ippiAbs_16s_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2073 of file qvippfunctions.cpp.
Referenced by Abs(), QVAbs_sFloatC1Block::iterate(), and QVAbs_sShortC1Block::iterate().
void Abs (const QVImage< sFloat, 1 > & qvimage_pSrc, QVImage< sFloat, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Computes absolute value of each pixel of a source image and places results in the destination image; for in-place flavors - in the same source image.
This is the QVision wrapper function for IPP's ippiAbs_32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2087 of file qvippfunctions.cpp.
void AbsDiff (const QVImage< uChar, 1 > & qvimage_pSrc1, const QVImage< uChar, 1 > & qvimage_pSrc2, QVImage< uChar, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Calculate absolute difference between corresponding pixels of the two images or between image pixels and scalar.
This is the QVision wrapper function for IPP's ippiAbsDiff_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2101 of file qvippfunctions.cpp.
Referenced by AbsDiff(), FilterDoG(), FilterHessianCornerResponseImage(), QVAbsDiff_sFloatC1Block::iterate(), and QVAbsDiff_uCharC1Block::iterate().
void AbsDiff (const QVImage< sFloat, 1 > & qvimage_pSrc1, const QVImage< sFloat, 1 > & qvimage_pSrc2, QVImage< sFloat, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Calculate absolute difference between corresponding pixels of the two images or between image pixels and scalar.
This is the QVision wrapper function for IPP's ippiAbsDiff_32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2119 of file qvippfunctions.cpp.
void Sqr (const QVImage< sFloat, 1 > & qvimage_pSrc, QVImage< sFloat, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Squares pixel values of an image and places results in the destination image; for in-place flavors - in the same image.
This is the QVision wrapper function for IPP's ippiSqr_32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2136 of file qvippfunctions.cpp.
Referenced by QVSqr_sFloatC1Block::iterate(), and Sqr().
void Ln (const QVImage< sFloat, 1 > & qvimage_pSrc, QVImage< sFloat, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Computes the natural logarithm of each pixel values of a source image and places the results in the destination image; for in-place flavors - in the same image.
This is the QVision wrapper function for IPP's ippiLn_32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2150 of file qvippfunctions.cpp.
Referenced by QVLn_sFloatC3Block::iterate(), QVLn_sFloatC1Block::iterate(), and Ln().
void Ln (const QVImage< sFloat, 3 > & qvimage_pSrc, QVImage< sFloat, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Computes the natural logarithm of each pixel values of a source image and places the results in the destination image; for in-place flavors - in the same image.
This is the QVision wrapper function for IPP's ippiLn_32f_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2164 of file qvippfunctions.cpp.
void And (const QVImage< uChar, 1 > & qvimage_pSrc1, const QVImage< uChar, 1 > & qvimage_pSrc2, QVImage< uChar, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiAnd_8u_C1R.
This is the QVision wrapper function for IPP's ippiAnd_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2178 of file qvippfunctions.cpp.
Referenced by And(), QVAnd_sIntC3Block::iterate(), QVAnd_sIntC1Block::iterate(), QVAnd_uShortC3Block::iterate(), QVAnd_uShortC1Block::iterate(), QVAnd_uCharC3Block::iterate(), and QVAnd_uCharC1Block::iterate().
void And (const QVImage< uChar, 3 > & qvimage_pSrc1, const QVImage< uChar, 3 > & qvimage_pSrc2, QVImage< uChar, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiAnd_8u_C3R.
This is the QVision wrapper function for IPP's ippiAnd_8u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2195 of file qvippfunctions.cpp.
void And (const QVImage< uShort, 1 > & qvimage_pSrc1, const QVImage< uShort, 1 > & qvimage_pSrc2, QVImage< uShort, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiAnd_16u_C1R.
This is the QVision wrapper function for IPP's ippiAnd_16u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2212 of file qvippfunctions.cpp.
void And (const QVImage< uShort, 3 > & qvimage_pSrc1, const QVImage< uShort, 3 > & qvimage_pSrc2, QVImage< uShort, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiAnd_16u_C3R.
This is the QVision wrapper function for IPP's ippiAnd_16u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2229 of file qvippfunctions.cpp.
void And (const QVImage< sInt, 1 > & qvimage_pSrc1, const QVImage< sInt, 1 > & qvimage_pSrc2, QVImage< sInt, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiAnd_32s_C1R.
This is the QVision wrapper function for IPP's ippiAnd_32s_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2246 of file qvippfunctions.cpp.
void And (const QVImage< sInt, 3 > & qvimage_pSrc1, const QVImage< sInt, 3 > & qvimage_pSrc2, QVImage< sInt, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiAnd_32s_C3R.
This is the QVision wrapper function for IPP's ippiAnd_32s_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2263 of file qvippfunctions.cpp.
void Or (const QVImage< uChar, 1 > & qvimage_pSrc1, const QVImage< uChar, 1 > & qvimage_pSrc2, QVImage< uChar, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiOr_8u_C1R.
This is the QVision wrapper function for IPP's ippiOr_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2280 of file qvippfunctions.cpp.
Referenced by QVOr_sIntC3Block::iterate(), QVOr_sIntC1Block::iterate(), QVOr_uShortC3Block::iterate(), QVOr_uShortC1Block::iterate(), QVOr_uCharC3Block::iterate(), QVOr_uCharC1Block::iterate(), and Or().
void Or (const QVImage< uChar, 3 > & qvimage_pSrc1, const QVImage< uChar, 3 > & qvimage_pSrc2, QVImage< uChar, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiOr_8u_C3R.
This is the QVision wrapper function for IPP's ippiOr_8u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2297 of file qvippfunctions.cpp.
void Or (const QVImage< uShort, 1 > & qvimage_pSrc1, const QVImage< uShort, 1 > & qvimage_pSrc2, QVImage< uShort, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiOr_16u_C1R.
This is the QVision wrapper function for IPP's ippiOr_16u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2314 of file qvippfunctions.cpp.
void Or (const QVImage< uShort, 3 > & qvimage_pSrc1, const QVImage< uShort, 3 > & qvimage_pSrc2, QVImage< uShort, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiOr_16u_C3R.
This is the QVision wrapper function for IPP's ippiOr_16u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2331 of file qvippfunctions.cpp.
void Or (const QVImage< sInt, 1 > & qvimage_pSrc1, const QVImage< sInt, 1 > & qvimage_pSrc2, QVImage< sInt, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiOr_32s_C1R.
This is the QVision wrapper function for IPP's ippiOr_32s_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2348 of file qvippfunctions.cpp.
void Or (const QVImage< sInt, 3 > & qvimage_pSrc1, const QVImage< sInt, 3 > & qvimage_pSrc2, QVImage< sInt, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiOr_32s_C3R.
This is the QVision wrapper function for IPP's ippiOr_32s_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2365 of file qvippfunctions.cpp.
void Xor (const QVImage< uChar, 1 > & qvimage_pSrc1, const QVImage< uChar, 1 > & qvimage_pSrc2, QVImage< uChar, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiXor_8u_C1R.
This is the QVision wrapper function for IPP's ippiXor_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2382 of file qvippfunctions.cpp.
Referenced by QVXor_sIntC3Block::iterate(), QVXor_sIntC1Block::iterate(), QVXor_uShortC3Block::iterate(), QVXor_uShortC1Block::iterate(), QVXor_uCharC3Block::iterate(), QVXor_uCharC1Block::iterate(), and Xor().
void Xor (const QVImage< uChar, 3 > & qvimage_pSrc1, const QVImage< uChar, 3 > & qvimage_pSrc2, QVImage< uChar, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiXor_8u_C3R.
This is the QVision wrapper function for IPP's ippiXor_8u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2399 of file qvippfunctions.cpp.
void Xor (const QVImage< uShort, 1 > & qvimage_pSrc1, const QVImage< uShort, 1 > & qvimage_pSrc2, QVImage< uShort, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiXor_16u_C1R.
This is the QVision wrapper function for IPP's ippiXor_16u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2416 of file qvippfunctions.cpp.
void Xor (const QVImage< uShort, 3 > & qvimage_pSrc1, const QVImage< uShort, 3 > & qvimage_pSrc2, QVImage< uShort, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiXor_16u_C3R.
This is the QVision wrapper function for IPP's ippiXor_16u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2433 of file qvippfunctions.cpp.
void Xor (const QVImage< sInt, 1 > & qvimage_pSrc1, const QVImage< sInt, 1 > & qvimage_pSrc2, QVImage< sInt, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiXor_32s_C1R.
This is the QVision wrapper function for IPP's ippiXor_32s_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2450 of file qvippfunctions.cpp.
void Xor (const QVImage< sInt, 3 > & qvimage_pSrc1, const QVImage< sInt, 3 > & qvimage_pSrc2, QVImage< sInt, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiXor_32s_C3R.
This is the QVision wrapper function for IPP's ippiXor_32s_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2467 of file qvippfunctions.cpp.
void Not (const QVImage< uChar, 1 > & qvimage_pSrc, QVImage< uChar, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Performs corresponding bitwise logical operation between pixels of two image (AndC OrC XorC - between pixel of the source image and a constant).
This is the QVision wrapper function for IPP's ippiNot_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2484 of file qvippfunctions.cpp.
Referenced by getLTMSERContours(), QVNot_uCharC3Block::iterate(), QVNot_uCharC1Block::iterate(), and Not().
void Not (const QVImage< uChar, 3 > & qvimage_pSrc, QVImage< uChar, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Performs corresponding bitwise logical operation between pixels of two image (AndC OrC XorC - between pixel of the source image and a constant).
This is the QVision wrapper function for IPP's ippiNot_8u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2498 of file qvippfunctions.cpp.
void AndC (const QVImage< uChar, 1 > & qvimage_pSrc, const uChar value, QVImage< uChar, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiAndC_8u_C1R.
This is the QVision wrapper function for IPP's ippiAndC_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2512 of file qvippfunctions.cpp.
Referenced by AndC(), getLTMSER(), and QVAndC_uCharC1Block::iterate().
void AndC (const QVImage< uChar, 3 > & qvimage_pSrc, const uChar value[3], QVImage< uChar, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiAndC_8u_C3R.
This is the QVision wrapper function for IPP's ippiAndC_8u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2528 of file qvippfunctions.cpp.
void AndC (const QVImage< uShort, 1 > & qvimage_pSrc, const uShort value, QVImage< uShort, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiAndC_16u_C1R.
This is the QVision wrapper function for IPP's ippiAndC_16u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2544 of file qvippfunctions.cpp.
void AndC (const QVImage< uShort, 3 > & qvimage_pSrc, const uShort value[3], QVImage< uShort, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiAndC_16u_C3R.
This is the QVision wrapper function for IPP's ippiAndC_16u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2560 of file qvippfunctions.cpp.
void AndC (const QVImage< sInt, 1 > & qvimage_pSrc, const sInt value, QVImage< sInt, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiAndC_32s_C1R.
This is the QVision wrapper function for IPP's ippiAndC_32s_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2576 of file qvippfunctions.cpp.
void AndC (const QVImage< sInt, 3 > & qvimage_pSrc, const sInt value[3], QVImage< sInt, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiAndC_32s_C3R.
This is the QVision wrapper function for IPP's ippiAndC_32s_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2592 of file qvippfunctions.cpp.
void OrC (const QVImage< uChar, 1 > & qvimage_pSrc, const uChar value, QVImage< uChar, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiOrC_8u_C1R.
This is the QVision wrapper function for IPP's ippiOrC_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2608 of file qvippfunctions.cpp.
Referenced by QVOrC_uCharC1Block::iterate(), and OrC().
void OrC (const QVImage< uChar, 3 > & qvimage_pSrc, const uChar value[3], QVImage< uChar, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiOrC_8u_C3R.
This is the QVision wrapper function for IPP's ippiOrC_8u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2624 of file qvippfunctions.cpp.
void OrC (const QVImage< uShort, 1 > & qvimage_pSrc, const uShort value, QVImage< uShort, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiOrC_16u_C1R.
This is the QVision wrapper function for IPP's ippiOrC_16u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2640 of file qvippfunctions.cpp.
void OrC (const QVImage< uShort, 3 > & qvimage_pSrc, const uShort value[3], QVImage< uShort, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiOrC_16u_C3R.
This is the QVision wrapper function for IPP's ippiOrC_16u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2656 of file qvippfunctions.cpp.
void OrC (const QVImage< sInt, 1 > & qvimage_pSrc, const sInt value, QVImage< sInt, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiOrC_32s_C1R.
This is the QVision wrapper function for IPP's ippiOrC_32s_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2672 of file qvippfunctions.cpp.
void OrC (const QVImage< sInt, 3 > & qvimage_pSrc, const sInt value[3], QVImage< sInt, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiOrC_32s_C3R.
This is the QVision wrapper function for IPP's ippiOrC_32s_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2688 of file qvippfunctions.cpp.
void XorC (const QVImage< uChar, 1 > & qvimage_pSrc, const uChar value, QVImage< uChar, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiXorC_8u_C1R.
This is the QVision wrapper function for IPP's ippiXorC_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2704 of file qvippfunctions.cpp.
Referenced by QVXorC_uCharC1Block::iterate(), and XorC().
void XorC (const QVImage< uChar, 3 > & qvimage_pSrc, const uChar value[3], QVImage< uChar, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiXorC_8u_C3R.
This is the QVision wrapper function for IPP's ippiXorC_8u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2720 of file qvippfunctions.cpp.
void XorC (const QVImage< uShort, 1 > & qvimage_pSrc, const uShort value, QVImage< uShort, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiXorC_16u_C1R.
This is the QVision wrapper function for IPP's ippiXorC_16u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2736 of file qvippfunctions.cpp.
void XorC (const QVImage< uShort, 3 > & qvimage_pSrc, const uShort value[3], QVImage< uShort, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiXorC_16u_C3R.
This is the QVision wrapper function for IPP's ippiXorC_16u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2752 of file qvippfunctions.cpp.
void XorC (const QVImage< sInt, 1 > & qvimage_pSrc, const sInt value, QVImage< sInt, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiXorC_32s_C1R.
This is the QVision wrapper function for IPP's ippiXorC_32s_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2768 of file qvippfunctions.cpp.
void XorC (const QVImage< sInt, 3 > & qvimage_pSrc, const sInt value[3], QVImage< sInt, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiXorC_32s_C3R.
This is the QVision wrapper function for IPP's ippiXorC_32s_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2784 of file qvippfunctions.cpp.
void LShiftC (const QVImage< uChar, 1 > & qvimage_pSrc, const uInt value, QVImage< uChar, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiLShiftC_8u_C1R.
This is the QVision wrapper function for IPP's ippiLShiftC_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2800 of file qvippfunctions.cpp.
Referenced by QVLShiftC_uCharC1Block::iterate(), and LShiftC().
void LShiftC (const QVImage< uChar, 3 > & qvimage_pSrc, const uInt value[3], QVImage< uChar, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiLShiftC_8u_C3R.
This is the QVision wrapper function for IPP's ippiLShiftC_8u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2816 of file qvippfunctions.cpp.
void RShiftC (const QVImage< uChar, 1 > & qvimage_pSrc, const uInt value, QVImage< uChar, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiRShiftC_8u_C1R.
This is the QVision wrapper function for IPP's ippiRShiftC_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2832 of file qvippfunctions.cpp.
Referenced by QVRShiftC_uCharC1Block::iterate(), and RShiftC().
void RShiftC (const QVImage< uChar, 3 > & qvimage_pSrc, const uInt value[3], QVImage< uChar, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiRShiftC_8u_C3R.
This is the QVision wrapper function for IPP's ippiRShiftC_8u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2848 of file qvippfunctions.cpp.
void LShiftC (const QVImage< uShort, 1 > & qvimage_pSrc, const uInt value, QVImage< uShort, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiLShiftC_16u_C1R.
This is the QVision wrapper function for IPP's ippiLShiftC_16u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2864 of file qvippfunctions.cpp.
void LShiftC (const QVImage< uShort, 3 > & qvimage_pSrc, const uInt value[3], QVImage< uShort, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiLShiftC_16u_C3R.
This is the QVision wrapper function for IPP's ippiLShiftC_16u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2880 of file qvippfunctions.cpp.
void RShiftC (const QVImage< uShort, 1 > & qvimage_pSrc, const uInt value, QVImage< uShort, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiRShiftC_16u_C1R.
This is the QVision wrapper function for IPP's ippiRShiftC_16u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2896 of file qvippfunctions.cpp.
void RShiftC (const QVImage< uShort, 3 > & qvimage_pSrc, const uInt value[3], QVImage< uShort, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiRShiftC_16u_C3R.
This is the QVision wrapper function for IPP's ippiRShiftC_16u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2912 of file qvippfunctions.cpp.
void LShiftC (const QVImage< sInt, 1 > & qvimage_pSrc, const uInt value, QVImage< sInt, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiLShiftC_32s_C1R.
This is the QVision wrapper function for IPP's ippiLShiftC_32s_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2928 of file qvippfunctions.cpp.
void LShiftC (const QVImage< sInt, 3 > & qvimage_pSrc, const uInt value[3], QVImage< sInt, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiLShiftC_32s_C3R.
This is the QVision wrapper function for IPP's ippiLShiftC_32s_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2944 of file qvippfunctions.cpp.
void RShiftC (const QVImage< sInt, 1 > & qvimage_pSrc, const uInt value, QVImage< sInt, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiRShiftC_32s_C1R.
This is the QVision wrapper function for IPP's ippiRShiftC_32s_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2960 of file qvippfunctions.cpp.
void RShiftC (const QVImage< sInt, 3 > & qvimage_pSrc, const uInt value[3], QVImage< sInt, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiRShiftC_32s_C3R.
This is the QVision wrapper function for IPP's ippiRShiftC_32s_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2976 of file qvippfunctions.cpp.
QVision framework. PARP research group. Copyright © 2007, 2008, 2009, 2010, 2011.