QVision: Qt's Image, Video and Computer Vision Library
PARP Research Group Universidad de Murcia
Filtering Functions
[IPP wrapper functions]
Image processing functions that perform linear and non-linear filtering operations on an image.
Functions
void Filter (const QVImage< sFloat > &src, QVImage< sFloat > &dest, const QVMatrix kernel, const QPoint &destROIOffset=QPoint(0, 0))
This function uses the general square kernel defined in the matrix kernel to filter an image, using a convolution operation.
void FilterColumn (const QVImage< sFloat > &src, QVImage< sFloat > &dest, const QVVector kernel, const QPoint &destROIOffset=QPoint(0, 0))
Filters an image using a spatial kernel that consists of a single column.This function uses the vertical column kernel contained in vector kernel to filter an image ROI.
void FilterRow (const QVImage< sFloat > &src, QVImage< sFloat > &dest, const QVVector kernel, const QPoint &destROIOffset=QPoint(0, 0))
Filters an image using a spatial kernel that consists of a single row.This function uses the vertical column kernel contained in vector kernel to filter an image ROI.
void FilterSharpen (const QVImage< uChar > &src, QVImage< uChar > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Filters an image using a sharpening filter.This function applies a sharpening filter to an image ROI. The corresponding kernel is the matrix of 3x3 size with the following values:
void FilterSharpen (const QVImage< sFloat > &src, QVImage< sFloat > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Filters an image using a sharpening filter.
void Erode3x3 (const QVImage< uChar > &src, QVImage< uChar > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Applies a morphological Erode3x3 filter.
void Erode3x3 (const QVImage< uShort > &src, QVImage< uShort > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Applies a morphological Erode3x3 filter.
void Erode3x3 (const QVImage< sFloat > &src, QVImage< sFloat > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Applies a morphological Erode3x3 filter.
void Erode3x3 (const QVImage< uChar, 3 > &src, QVImage< uChar, 3 > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Applies a morphological Erode3x3 filter.
void Erode3x3 (const QVImage< uShort, 3 > &src, QVImage< uShort, 3 > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Applies a morphological Erode3x3 filter.
void Erode3x3 (const QVImage< sFloat, 3 > &src, QVImage< sFloat, 3 > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Applies a morphological Erode3x3 filter.
void Dilate3x3 (const QVImage< uChar > &src, QVImage< uChar > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Applies a morphological Dilate3x3 filter.
void Dilate3x3 (const QVImage< uShort > &src, QVImage< uShort > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Applies a morphological Dilate3x3 filter.
void Dilate3x3 (const QVImage< sFloat > &src, QVImage< sFloat > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Applies a morphological Dilate3x3 filter.
void Dilate3x3 (const QVImage< uChar, 3 > &src, QVImage< uChar, 3 > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Applies a morphological Dilate3x3 filter.
void Dilate3x3 (const QVImage< uShort, 3 > &src, QVImage< uShort, 3 > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Applies a morphological Dilate3x3 filter.
void Dilate3x3 (const QVImage< sFloat, 3 > &src, QVImage< sFloat, 3 > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Applies a morphological Dilate3x3 filter.
void FilterSobelHoriz (const QVImage< uChar > &src, QVImage< uChar > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Applies a horizontal Sobel derivative filter (3x3) to an image.
void FilterSobelHoriz (const QVImage< sShort > &src, QVImage< sShort > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Applies a horizontal Sobel derivative filter (3x3) to an image.
void FilterSobelHoriz (const QVImage< sFloat > &src, QVImage< sFloat > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Applies a horizontal Sobel derivative filter (3x3) to an image.
void FilterSobelHoriz (const QVImage< uChar, 3 > &src, QVImage< uChar, 3 > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Applies a horizontal Sobel derivative filter (3x3) to an image.
void FilterSobelHoriz (const QVImage< sShort, 3 > &src, QVImage< sShort, 3 > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Applies a horizontal Sobel derivative filter (3x3) to an image.
void FilterSobelHoriz (const QVImage< sFloat, 3 > &src, QVImage< sFloat, 3 > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Applies a horizontal Sobel derivative filter (3x3) to an image.
void FilterSobelVert (const QVImage< uChar > &src, QVImage< uChar > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Applies a vertical Sobel derivative filter (3x3) to an image.
void FilterSobelVert (const QVImage< sShort > &src, QVImage< sShort > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Applies a vertical Sobel derivative filter (3x3) to an image.
void FilterSobelVert (const QVImage< sFloat > &src, QVImage< sFloat > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Applies a vertical Sobel derivative filter (3x3) to an image.
void FilterSobelVert (const QVImage< uChar, 3 > &src, QVImage< uChar, 3 > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Applies a vertical Sobel derivative filter (3x3) to an image.
void FilterSobelVert (const QVImage< sShort, 3 > &src, QVImage< sShort, 3 > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Applies a vertical Sobel derivative filter (3x3) to an image.
void FilterSobelVert (const QVImage< sFloat, 3 > &src, QVImage< sFloat, 3 > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Applies a vertical Sobel derivative filter (3x3) to an image.
void FilterSobelHorizBorder (const QVImage< uChar > &src, QVImage< sShort > &dest, const IppiMaskSize maskSize, const IppiBorderType borderType, const uChar borderValue, QVImage< uChar > &buffer, const QPoint &destROIOffset=QPoint(0, 0))
Applies horizontal Sobel filter with border.This function is similar to FilterSobelHorizMask, but automatically creates a required border and define appropriate pixel values.
void FilterSobelNegVertBorder (const QVImage< uChar > &src, QVImage< sShort > &dest, const IppiMaskSize maskSize, const IppiBorderType borderType, const uChar borderValue, QVImage< uChar > &buffer, const QPoint &destROIOffset=QPoint(0, 0))
Applies vertical Sobel filter with border.This function is similar to FilterSobelVertMask, but uses negative values for the mask applied, and automatically create a required border and define appropriate pixel values.
void FilterSobelHorizGetBufferSize (const QVGenericImage &src, const IppiMaskSize maskSize, QVImage< uChar > &buffer)
Allocates size in a buffer image for temporary data for function FilterSobelHoriz.This function should be applied to any QVImage<uChar> image to be used as a buffer image for function FilterSobelHoriz. Initializes dimensions for that buffer image, appropriated for that algorithm.
void FilterSobelNegVertGetBufferSize (const QVGenericImage &src, const IppiMaskSize maskSize, QVImage< uChar > &buffer)
Allocates size in a buffer image for temporary data for function FilterSobelNegVert.This function should be applied to any QVImage<uChar> image to be used as a buffer image for function FilterSobelNegVert. Initializes dimensions for that buffer image, appropriated for that algorithm.
void FilterGaussBorder (const QVImage< sFloat, 1 > &src, QVImage< sFloat, 1 > &dest, QVImage< uChar > &buffer, sInt kernelSize, sFloat sigma, IppiBorderType borderType=ippBorderConst, sFloat borderValue=0.0, const QPoint &destROIOffset=QPoint(0, 0))
Applies Gauss filter with border.This function applies the Gaussian filter to the source image ROI pSrc. The kernel of this filter is the matrix of size with the standard deviation . The values of the elements of the Gaussian kernel are calculated according to the formula:
void FilterGaussGetBufferSize (const QVGenericImage &image, QVImage< uChar > &buffer, uInt kernelSize)
Computes the size of the external buffer for the Gaussian filter with border.This function computes the size of the external buffer that is required for the filter function FilterGaussBorder. This buffer can be used to filter an image whose width and height are equal to or less than param QVGenericImage image, and the kernel size is equal to or less than kernelSize.
void FilterBox (const QVImage< uChar, 1 > &qvimage_pSrc, QVImage< uChar, 1 > &qvimage_pDst, const QSize &maskSize=QSize(3, 3), const QPoint &anchor=QPoint(0, 0), const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterBox_8u_C1R.
void FilterBox (const QVImage< uChar, 3 > &qvimage_pSrc, QVImage< uChar, 3 > &qvimage_pDst, const QSize &maskSize=QSize(3, 3), const QPoint &anchor=QPoint(0, 0), const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterBox_8u_C3R.
void FilterBox (const QVImage< uShort, 1 > &qvimage_pSrc, QVImage< uShort, 1 > &qvimage_pDst, const QSize &maskSize=QSize(3, 3), const QPoint &anchor=QPoint(0, 0), const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterBox_16u_C1R.
void FilterBox (const QVImage< sFloat, 1 > &qvimage_pSrc, QVImage< sFloat, 1 > &qvimage_pDst, const QSize &maskSize=QSize(3, 3), const QPoint &anchor=QPoint(0, 0), const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterBox_32f_C1R.
void FilterMin (const QVImage< uChar, 1 > &qvimage_pSrc, QVImage< uChar, 1 > &qvimage_pDst, const QSize &maskSize=QSize(3, 3), const QPoint &anchor=QPoint(0, 0), const QPoint &destROIOffset=QPoint(0, 0))
Applies the "min" filter to an image.
void FilterMin (const QVImage< uChar, 3 > &qvimage_pSrc, QVImage< uChar, 3 > &qvimage_pDst, const QSize &maskSize=QSize(3, 3), const QPoint &anchor=QPoint(0, 0), const QPoint &destROIOffset=QPoint(0, 0))
Applies the "min" filter to an image.
void FilterMin (const QVImage< uShort, 1 > &qvimage_pSrc, QVImage< uShort, 1 > &qvimage_pDst, const QSize &maskSize=QSize(3, 3), const QPoint &anchor=QPoint(0, 0), const QPoint &destROIOffset=QPoint(0, 0))
Applies the "min" filter to an image.
void FilterMin (const QVImage< sFloat, 1 > &qvimage_pSrc, QVImage< sFloat, 1 > &qvimage_pDst, const QSize &maskSize=QSize(3, 3), const QPoint &anchor=QPoint(0, 0), const QPoint &destROIOffset=QPoint(0, 0))
Applies the "min" filter to an image.
void FilterMax (const QVImage< uChar, 1 > &qvimage_pSrc, QVImage< uChar, 1 > &qvimage_pDst, const QSize &maskSize=QSize(3, 3), const QPoint &anchor=QPoint(0, 0), const QPoint &destROIOffset=QPoint(0, 0))
Applies the "max" filter to an image.
void FilterMax (const QVImage< uChar, 3 > &qvimage_pSrc, QVImage< uChar, 3 > &qvimage_pDst, const QSize &maskSize=QSize(3, 3), const QPoint &anchor=QPoint(0, 0), const QPoint &destROIOffset=QPoint(0, 0))
Applies the "max" filter to an image.
void FilterMax (const QVImage< uShort, 1 > &qvimage_pSrc, QVImage< uShort, 1 > &qvimage_pDst, const QSize &maskSize=QSize(3, 3), const QPoint &anchor=QPoint(0, 0), const QPoint &destROIOffset=QPoint(0, 0))
Applies the "max" filter to an image.
void FilterMax (const QVImage< sFloat, 1 > &qvimage_pSrc, QVImage< sFloat, 1 > &qvimage_pDst, const QSize &maskSize=QSize(3, 3), const QPoint &anchor=QPoint(0, 0), const QPoint &destROIOffset=QPoint(0, 0))
Applies the "max" filter to an image.
void FilterMedian (const QVImage< uChar, 1 > &qvimage_pSrc, QVImage< uChar, 1 > &qvimage_pDst, const QSize &maskSize=QSize(3, 3), const QPoint &anchor=QPoint(0, 0), const QPoint &destROIOffset=QPoint(0, 0))
Filters an image using a box median filter.
void FilterMedian (const QVImage< uChar, 3 > &qvimage_pSrc, QVImage< uChar, 3 > &qvimage_pDst, const QSize &maskSize=QSize(3, 3), const QPoint &anchor=QPoint(0, 0), const QPoint &destROIOffset=QPoint(0, 0))
Filters an image using a box median filter.
void FilterMedian (const QVImage< uShort, 1 > &qvimage_pSrc, QVImage< uShort, 1 > &qvimage_pDst, const QSize &maskSize=QSize(3, 3), const QPoint &anchor=QPoint(0, 0), const QPoint &destROIOffset=QPoint(0, 0))
Filters an image using a box median filter.
void FilterMedianHoriz (const QVImage< uChar, 1 > &qvimage_pSrc, QVImage< uChar, 1 > &qvimage_pDst, const IppiMaskSize mask=ippMskSize3x3, const QPoint &destROIOffset=QPoint(0, 0))
Performs horizontal median filtering.
void FilterMedianVert (const QVImage< uChar, 1 > &qvimage_pSrc, QVImage< uChar, 1 > &qvimage_pDst, const IppiMaskSize mask=ippMskSize3x3, const QPoint &destROIOffset=QPoint(0, 0))
Performs vertical median filtering.
void FilterMedianCross (const QVImage< uChar, 1 > &qvimage_pSrc, QVImage< uChar, 1 > &qvimage_pDst, const IppiMaskSize mask=ippMskSize3x3, const QPoint &destROIOffset=QPoint(0, 0))
Filters an image using a cross median filter.
void FilterMedianWeightedCenter3x3 (const QVImage< uChar, 1 > &qvimage_pSrc, QVImage< uChar, 1 > &qvimage_pDst, const int weight, const QPoint &destROIOffset=QPoint(0, 0))
Filter an image using a median filter with kernel size 3x3 and enlarged weight of central pixel.
void FilterMedianColor (const QVImage< uChar, 3 > &qvimage_pSrc, QVImage< uChar, 3 > &qvimage_pDst, const IppiMaskSize mask=ippMskSize3x3, const QPoint &destROIOffset=QPoint(0, 0))
Filters an image using a box color median filter.
void FilterSobelHorizMask (const QVImage< sFloat, 1 > &qvimage_pSrc, QVImage< sFloat, 1 > &qvimage_pDst, const IppiMaskSize mask=ippMskSize3x3, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterSobelHorizMask_32f_C1R.
void FilterSobelVertMask (const QVImage< sFloat, 1 > &qvimage_pSrc, QVImage< sFloat, 1 > &qvimage_pDst, const IppiMaskSize mask=ippMskSize3x3, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterSobelVertMask_32f_C1R.
void FilterLaplace (const QVImage< uChar, 1 > &qvimage_pSrc, QVImage< uChar, 1 > &qvimage_pDst, const IppiMaskSize mask=ippMskSize3x3, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterLaplace_8u_C1R.
void FilterLaplace (const QVImage< sShort, 1 > &qvimage_pSrc, QVImage< sShort, 1 > &qvimage_pDst, const IppiMaskSize mask=ippMskSize3x3, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterLaplace_16s_C1R.
void FilterLaplace (const QVImage< sFloat, 1 > &qvimage_pSrc, QVImage< sFloat, 1 > &qvimage_pDst, const IppiMaskSize mask=ippMskSize3x3, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterLaplace_32f_C1R.
void FilterGauss (const QVImage< uChar, 1 > &qvimage_pSrc, QVImage< uChar, 1 > &qvimage_pDst, const IppiMaskSize mask=ippMskSize3x3, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterGauss_8u_C1R.
void FilterGauss (const QVImage< sFloat, 1 > &qvimage_pSrc, QVImage< sFloat, 1 > &qvimage_pDst, const IppiMaskSize mask=ippMskSize3x3, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterGauss_32f_C1R.
void FilterGauss (const QVImage< uChar, 3 > &qvimage_pSrc, QVImage< uChar, 3 > &qvimage_pDst, const IppiMaskSize mask=ippMskSize3x3, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterGauss_8u_C3R.
void FilterGauss (const QVImage< sFloat, 3 > &qvimage_pSrc, QVImage< sFloat, 3 > &qvimage_pDst, const IppiMaskSize mask=ippMskSize3x3, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterGauss_32f_C3R.
void FilterHipass (const QVImage< uChar, 1 > &qvimage_pSrc, QVImage< uChar, 1 > &qvimage_pDst, const IppiMaskSize mask=ippMskSize3x3, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterHipass_8u_C1R.
void FilterHipass (const QVImage< uChar, 3 > &qvimage_pSrc, QVImage< uChar, 3 > &qvimage_pDst, const IppiMaskSize mask=ippMskSize3x3, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterHipass_8u_C3R.
void FilterHipass (const QVImage< sFloat, 1 > &qvimage_pSrc, QVImage< sFloat, 1 > &qvimage_pDst, const IppiMaskSize mask=ippMskSize3x3, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterHipass_32f_C1R.
void FilterHipass (const QVImage< sFloat, 3 > &qvimage_pSrc, QVImage< sFloat, 3 > &qvimage_pDst, const IppiMaskSize mask=ippMskSize3x3, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterHipass_32f_C3R.
void FilterLowpass (const QVImage< uChar, 1 > &qvimage_pSrc, QVImage< uChar, 1 > &qvimage_pDst, const IppiMaskSize mask=ippMskSize3x3, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterLowpass_8u_C1R.
void FilterLowpass (const QVImage< sFloat, 1 > &qvimage_pSrc, QVImage< sFloat, 1 > &qvimage_pDst, const IppiMaskSize mask=ippMskSize3x3, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterLowpass_32f_C1R.
Detailed Description
Image processing functions that perform linear and non-linear filtering operations on an image.
Filtering can be used in a variety of image processing operations; for example, edge detection, blurring, noise removal, and feature detection.
Function Documentation
void Filter (const QVImage< sFloat > & src, QVImage< sFloat > & dest, const QVMatrix kernel, const QPoint & destROIOffset = QPoint(0, 0))
This function uses the general square kernel defined in the matrix kernel to filter an image, using a convolution operation.
Parameters:
src source image to filter.
dest destination image to hold the resulting image after filtering.
kernel matrix containing filter kernel.
Note:
ojo, quizs haya que indicar en IPP_POINT(0,0), el ltimo elemento de la matriz 'kernel', tal y como pasa en las funciones FilterColumn y FilterRow.
Definition at line 333 of file qvipp.cpp.
void FilterColumn (const QVImage< sFloat > & src, QVImage< sFloat > & dest, const QVVector kernel, const QPoint & destROIOffset)
Filters an image using a spatial kernel that consists of a single column.This function uses the vertical column kernel contained in vector kernel to filter an image ROI.
Parameters:
src source image to filter.
dest destination image to hold the resulting image after filtering.
kernel vector containing the kernel to filter.
Note:
Ojo: muerte, peligro. Hay que indicar como anchor, el tamao del kernel (menos 1). La iteracin ir desde el valor 'kernelSize', hacia abajo.
Definition at line 357 of file qvipp.cpp.
Referenced by FilterSeparable().
void FilterRow (const QVImage< sFloat > & src, QVImage< sFloat > & dest, const QVVector kernel, const QPoint & destROIOffset)
Filters an image using a spatial kernel that consists of a single row.This function uses the vertical column kernel contained in vector kernel to filter an image ROI.
Parameters:
src source image to filter.
dest destination image to hold the resulting image after filtering.
kernel vector containing the kernel to filter.
Note:
Ojo: muerte, peligro. Hay que indicar como anchor, el tamao del kernel (menos 1). La iteracin ir desde el valor 'kernelSize', hacia abajo.
Definition at line 376 of file qvipp.cpp.
Referenced by FilterSeparable().
void FilterSharpen (const QVImage< uChar > & src, QVImage< uChar > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Filters an image using a sharpening filter.This function applies a sharpening filter to an image ROI. The corresponding kernel is the matrix of 3x3 size with the following values:
This filter enhances high-frequency components and thus sharpens an image.
Parameters:
src source image to filter.
dest destination image to hold the resulting image after filtering.
void FilterSharpen (const QVImage< sFloat > & src, QVImage< sFloat > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Filters an image using a sharpening filter.
See also:
FilterSharpen(const QVImage<uChar> &, QVImage<uChar> &)
void Erode3x3 (const QVImage< uChar > & src, QVImage< uChar > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Applies a morphological Erode3x3 filter.
Parameters:
src source image to filter.
dest destination image to hold the resulting image after filtering.
void Erode3x3 (const QVImage< uShort > & src, QVImage< uShort > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Applies a morphological Erode3x3 filter.
Parameters:
src source image to filter.
dest destination image to hold the resulting image after filtering.
void Erode3x3 (const QVImage< sFloat > & src, QVImage< sFloat > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Applies a morphological Erode3x3 filter.
Parameters:
src source image to filter.
dest destination image to hold the resulting image after filtering.
void Erode3x3 (const QVImage< uChar, 3 > & src, QVImage< uChar, 3 > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Applies a morphological Erode3x3 filter.
Parameters:
src source image to filter.
dest destination image to hold the resulting image after filtering.
void Erode3x3 (const QVImage< uShort, 3 > & src, QVImage< uShort, 3 > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Applies a morphological Erode3x3 filter.
Parameters:
src source image to filter.
dest destination image to hold the resulting image after filtering.
void Erode3x3 (const QVImage< sFloat, 3 > & src, QVImage< sFloat, 3 > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Applies a morphological Erode3x3 filter.
Parameters:
src source image to filter.
dest destination image to hold the resulting image after filtering.
void Dilate3x3 (const QVImage< uChar > & src, QVImage< uChar > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Applies a morphological Dilate3x3 filter.
Parameters:
src source image to filter.
dest destination image to hold the resulting image after filtering.
void Dilate3x3 (const QVImage< uShort > & src, QVImage< uShort > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Applies a morphological Dilate3x3 filter.
Parameters:
src source image to filter.
dest destination image to hold the resulting image after filtering.
void Dilate3x3 (const QVImage< sFloat > & src, QVImage< sFloat > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Applies a morphological Dilate3x3 filter.
Parameters:
src source image to filter.
dest destination image to hold the resulting image after filtering.
void Dilate3x3 (const QVImage< uChar, 3 > & src, QVImage< uChar, 3 > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Applies a morphological Dilate3x3 filter.
Parameters:
src source image to filter.
dest destination image to hold the resulting image after filtering.
void Dilate3x3 (const QVImage< uShort, 3 > & src, QVImage< uShort, 3 > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Applies a morphological Dilate3x3 filter.
Parameters:
src source image to filter.
dest destination image to hold the resulting image after filtering.
void Dilate3x3 (const QVImage< sFloat, 3 > & src, QVImage< sFloat, 3 > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Applies a morphological Dilate3x3 filter.
Parameters:
src source image to filter.
dest destination image to hold the resulting image after filtering.
void FilterSobelHoriz (const QVImage< uChar > & src, QVImage< uChar > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Applies a horizontal Sobel derivative filter (3x3) to an image.
Parameters:
src source image to filter.
dest destination image to hold the resulting image after filtering.
void FilterSobelHoriz (const QVImage< sShort > & src, QVImage< sShort > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Applies a horizontal Sobel derivative filter (3x3) to an image.
Parameters:
src source image to filter.
dest destination image to hold the resulting image after filtering.
void FilterSobelHoriz (const QVImage< sFloat > & src, QVImage< sFloat > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Applies a horizontal Sobel derivative filter (3x3) to an image.
Parameters:
src source image to filter.
dest destination image to hold the resulting image after filtering.
void FilterSobelHoriz (const QVImage< uChar, 3 > & src, QVImage< uChar, 3 > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Applies a horizontal Sobel derivative filter (3x3) to an image.
Parameters:
src source image to filter.
dest destination image to hold the resulting image after filtering.
void FilterSobelHoriz (const QVImage< sShort, 3 > & src, QVImage< sShort, 3 > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Applies a horizontal Sobel derivative filter (3x3) to an image.
Parameters:
src source image to filter.
dest destination image to hold the resulting image after filtering.
void FilterSobelHoriz (const QVImage< sFloat, 3 > & src, QVImage< sFloat, 3 > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Applies a horizontal Sobel derivative filter (3x3) to an image.
Parameters:
src source image to filter.
dest destination image to hold the resulting image after filtering.
void FilterSobelVert (const QVImage< uChar > & src, QVImage< uChar > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Applies a vertical Sobel derivative filter (3x3) to an image.
Parameters:
src source image to filter.
dest destination image to hold the resulting image after filtering.
void FilterSobelVert (const QVImage< sShort > & src, QVImage< sShort > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Applies a vertical Sobel derivative filter (3x3) to an image.
Parameters:
src source image to filter.
dest destination image to hold the resulting image after filtering.
void FilterSobelVert (const QVImage< sFloat > & src, QVImage< sFloat > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Applies a vertical Sobel derivative filter (3x3) to an image.
Parameters:
src source image to filter.
dest destination image to hold the resulting image after filtering.
void FilterSobelVert (const QVImage< uChar, 3 > & src, QVImage< uChar, 3 > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Applies a vertical Sobel derivative filter (3x3) to an image.
Parameters:
src source image to filter.
dest destination image to hold the resulting image after filtering.
void FilterSobelVert (const QVImage< sShort, 3 > & src, QVImage< sShort, 3 > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Applies a vertical Sobel derivative filter (3x3) to an image.
Parameters:
src source image to filter.
dest destination image to hold the resulting image after filtering.
void FilterSobelVert (const QVImage< sFloat, 3 > & src, QVImage< sFloat, 3 > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Applies a vertical Sobel derivative filter (3x3) to an image.
Parameters:
src source image to filter.
dest destination image to hold the resulting image after filtering.
void FilterSobelHorizBorder (const QVImage< uChar > & src, QVImage< sShort > & dest, const IppiMaskSize maskSize, const IppiBorderType borderType, const uChar borderValue, QVImage< uChar > & buffer, const QPoint & destROIOffset = QPoint(0, 0))
Applies horizontal Sobel filter with border.This function is similar to FilterSobelHorizMask, but automatically creates a required border and define appropriate pixel values.
Function FilterSobelHorizGetBufferSize should be used to initialize sizes for a buffer QVImage<uChar> image, which will hold temporary data for the function operations.
Parameters:
src source image to filter.
dest destination image to hold the resulting image after filtering.
buffer buffer image to hold temporal data during function operation.
maskSize size of mask. Should be 3 (for mask of size 3x3) or 5 (for mask of size 5x5).
See also:
FilterSobelHorizGetBufferSize
void FilterSobelNegVertBorder (const QVImage< uChar > & src, QVImage< sShort > & dest, const IppiMaskSize maskSize, const IppiBorderType borderType, const uChar borderValue, QVImage< uChar > & buffer, const QPoint & destROIOffset = QPoint(0, 0))
Applies vertical Sobel filter with border.This function is similar to FilterSobelVertMask, but uses negative values for the mask applied, and automatically create a required border and define appropriate pixel values.
Function FilterSobelNegVertGetBufferSize should be used to initialize sizes for a buffer QVImage<uChar> image, which will hold temporary data for the function operations.
Parameters:
src source image to filter.
dest destination image to hold the resulting image after filtering.
buffer buffer image to hold temporal data during function operation.
maskSize size of mask. Should be 3 (for mask of size 3x3) or 5 (for mask of size 5x5).
See also:
FilterSobelNegVertGetBufferSize
void FilterSobelHorizGetBufferSize (const QVGenericImage & src, const IppiMaskSize maskSize, QVImage< uChar > & buffer)
Allocates size in a buffer image for temporary data for function FilterSobelHoriz.This function should be applied to any QVImage<uChar> image to be used as a buffer image for function FilterSobelHoriz. Initializes dimensions for that buffer image, appropriated for that algorithm.
Parameters:
src source image to apply later filter.
buffer buffer image to initialize for further operations.
maskSize size of mask. Should be 3 (for mask of size 3x3) or 5 (for mask of size 5x5).
See also:
FilterSobelHoriz
void FilterSobelNegVertGetBufferSize (const QVGenericImage & src, const IppiMaskSize maskSize, QVImage< uChar > & buffer)
Allocates size in a buffer image for temporary data for function FilterSobelNegVert.This function should be applied to any QVImage<uChar> image to be used as a buffer image for function FilterSobelNegVert. Initializes dimensions for that buffer image, appropriated for that algorithm.
Parameters:
src source image to apply later filter.
buffer buffer image to initialize for further operations.
maskSize size of mask. Should be 3 (for mask of size 3x3) or 5 (for mask of size 5x5).
See also:
FilterSobelNegVert
void FilterGaussBorder (const QVImage< sFloat, 1 > & src, QVImage< sFloat, 1 > & dest, QVImage< uChar > & buffer, sInt kernelSize, sFloat sigma, IppiBorderType borderType = ippBorderConst, sFloat borderValue = 0.0, const QPoint & destROIOffset = QPoint(0, 0))
Applies Gauss filter with border.This function applies the Gaussian filter to the source image ROI pSrc. The kernel of this filter is the matrix of size with the standard deviation . The values of the elements of the Gaussian kernel are calculated according to the formula:
and then are normalized. The function requires a working image buffer whose size should be computed by the function FilterGaussGetBufferSize beforehand.
Parameters:
src source image to apply filter
dest resulting image.
buffer buffer image initiated beforehand by the function FilterGaussGetBufferSize.
kernelSize specifies the size of the Gaussian kernel, must be odd and greater than or equal to 3.
sigma standard deviation of the Gaussian kernel.
borderType type of border. Following values are possible:
ippBorderConst. Values of all border pixels are set to constant.
ippBorderRepl. Replicated border is used.
ippBorderWrap. Wrapped border is used
ippBorderMirror. Mirrored border is used
ippBorderMirrorR. Mirrored border with replication is used
borderValue The constant value to assign to the pixels in the constant border (not applicable for other borders type).
See also:
FilterGaussGetBufferSize
void FilterGaussGetBufferSize (const QVGenericImage & image, QVImage< uChar > & buffer, uInt kernelSize)
Computes the size of the external buffer for the Gaussian filter with border.This function computes the size of the external buffer that is required for the filter function FilterGaussBorder. This buffer can be used to filter an image whose width and height are equal to or less than param QVGenericImage image, and the kernel size is equal to or less than kernelSize.
Parameters:
src source image to apply later filter.
buffer buffer image to initialize for further operations.
kernelSize Size of the Gaussian kernel, odd, greater than or equal to 3.
See also:
FilterGaussBorder
Definition at line 193 of file qvipp.cpp.
Referenced by FilterGaussGetBufferSize().
void FilterBox (const QVImage< uChar, 1 > & qvimage_pSrc, QVImage< uChar, 1 > & qvimage_pDst, const QSize & maskSize = QSize(3, 3), const QPoint & anchor = QPoint(0, 0), const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterBox_8u_C1R.
This is the QVision wrapper function for IPP's ippiFilterBox_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
maskSize Corresponds to the same parameter of type IppiSize in the IPP function.
anchor Corresponds to the same parameter of type IppiPoint in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3676 of file qvippfunctions.cpp.
Referenced by FilterBox(), QVFilterBox_sFloatC1Block::iterate(), QVFilterBox_uCharC3Block::iterate(), and QVFilterBox_uCharC1Block::iterate().
void FilterBox (const QVImage< uChar, 3 > & qvimage_pSrc, QVImage< uChar, 3 > & qvimage_pDst, const QSize & maskSize = QSize(3, 3), const QPoint & anchor = QPoint(0, 0), const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterBox_8u_C3R.
This is the QVision wrapper function for IPP's ippiFilterBox_8u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
maskSize Corresponds to the same parameter of type IppiSize in the IPP function.
anchor Corresponds to the same parameter of type IppiPoint in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3695 of file qvippfunctions.cpp.
void FilterBox (const QVImage< uShort, 1 > & qvimage_pSrc, QVImage< uShort, 1 > & qvimage_pDst, const QSize & maskSize = QSize(3, 3), const QPoint & anchor = QPoint(0, 0), const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterBox_16u_C1R.
This is the QVision wrapper function for IPP's ippiFilterBox_16u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
maskSize Corresponds to the same parameter of type IppiSize in the IPP function.
anchor Corresponds to the same parameter of type IppiPoint in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3714 of file qvippfunctions.cpp.
void FilterBox (const QVImage< sFloat, 1 > & qvimage_pSrc, QVImage< sFloat, 1 > & qvimage_pDst, const QSize & maskSize = QSize(3, 3), const QPoint & anchor = QPoint(0, 0), const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterBox_32f_C1R.
This is the QVision wrapper function for IPP's ippiFilterBox_32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
maskSize Corresponds to the same parameter of type IppiSize in the IPP function.
anchor Corresponds to the same parameter of type IppiPoint in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3733 of file qvippfunctions.cpp.
void FilterMin (const QVImage< uChar, 1 > & qvimage_pSrc, QVImage< uChar, 1 > & qvimage_pDst, const QSize & maskSize = QSize(3, 3), const QPoint & anchor = QPoint(0, 0), const QPoint & destROIOffset = QPoint(0, 0))
Applies the "min" filter to an image.
This is the QVision wrapper function for IPP's ippiFilterMin_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
maskSize Corresponds to the same parameter of type IppiSize in the IPP function.
anchor Corresponds to the same parameter of type IppiPoint in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3752 of file qvippfunctions.cpp.
Referenced by FilterMin(), QVFilterMin_sFloatC1Block::iterate(), QVFilterMin_uCharC3Block::iterate(), and QVFilterMin_uCharC1Block::iterate().
void FilterMin (const QVImage< uChar, 3 > & qvimage_pSrc, QVImage< uChar, 3 > & qvimage_pDst, const QSize & maskSize = QSize(3, 3), const QPoint & anchor = QPoint(0, 0), const QPoint & destROIOffset = QPoint(0, 0))
Applies the "min" filter to an image.
This is the QVision wrapper function for IPP's ippiFilterMin_8u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
maskSize Corresponds to the same parameter of type IppiSize in the IPP function.
anchor Corresponds to the same parameter of type IppiPoint in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3771 of file qvippfunctions.cpp.
void FilterMin (const QVImage< uShort, 1 > & qvimage_pSrc, QVImage< uShort, 1 > & qvimage_pDst, const QSize & maskSize = QSize(3, 3), const QPoint & anchor = QPoint(0, 0), const QPoint & destROIOffset = QPoint(0, 0))
Applies the "min" filter to an image.
This is the QVision wrapper function for IPP's ippiFilterMin_16u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
maskSize Corresponds to the same parameter of type IppiSize in the IPP function.
anchor Corresponds to the same parameter of type IppiPoint in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3790 of file qvippfunctions.cpp.
void FilterMin (const QVImage< sFloat, 1 > & qvimage_pSrc, QVImage< sFloat, 1 > & qvimage_pDst, const QSize & maskSize = QSize(3, 3), const QPoint & anchor = QPoint(0, 0), const QPoint & destROIOffset = QPoint(0, 0))
Applies the "min" filter to an image.
This is the QVision wrapper function for IPP's ippiFilterMin_32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
maskSize Corresponds to the same parameter of type IppiSize in the IPP function.
anchor Corresponds to the same parameter of type IppiPoint in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3809 of file qvippfunctions.cpp.
void FilterMax (const QVImage< uChar, 1 > & qvimage_pSrc, QVImage< uChar, 1 > & qvimage_pDst, const QSize & maskSize = QSize(3, 3), const QPoint & anchor = QPoint(0, 0), const QPoint & destROIOffset = QPoint(0, 0))
Applies the "max" filter to an image.
This is the QVision wrapper function for IPP's ippiFilterMax_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
maskSize Corresponds to the same parameter of type IppiSize in the IPP function.
anchor Corresponds to the same parameter of type IppiPoint in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3828 of file qvippfunctions.cpp.
Referenced by fastMaximalPoints(), FilterMax(), QVFilterMax_sFloatC1Block::iterate(), QVFilterMax_uCharC3Block::iterate(), and QVFilterMax_uCharC1Block::iterate().
void FilterMax (const QVImage< uChar, 3 > & qvimage_pSrc, QVImage< uChar, 3 > & qvimage_pDst, const QSize & maskSize = QSize(3, 3), const QPoint & anchor = QPoint(0, 0), const QPoint & destROIOffset = QPoint(0, 0))
Applies the "max" filter to an image.
This is the QVision wrapper function for IPP's ippiFilterMax_8u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
maskSize Corresponds to the same parameter of type IppiSize in the IPP function.
anchor Corresponds to the same parameter of type IppiPoint in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3847 of file qvippfunctions.cpp.
void FilterMax (const QVImage< uShort, 1 > & qvimage_pSrc, QVImage< uShort, 1 > & qvimage_pDst, const QSize & maskSize = QSize(3, 3), const QPoint & anchor = QPoint(0, 0), const QPoint & destROIOffset = QPoint(0, 0))
Applies the "max" filter to an image.
This is the QVision wrapper function for IPP's ippiFilterMax_16u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
maskSize Corresponds to the same parameter of type IppiSize in the IPP function.
anchor Corresponds to the same parameter of type IppiPoint in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3866 of file qvippfunctions.cpp.
void FilterMax (const QVImage< sFloat, 1 > & qvimage_pSrc, QVImage< sFloat, 1 > & qvimage_pDst, const QSize & maskSize = QSize(3, 3), const QPoint & anchor = QPoint(0, 0), const QPoint & destROIOffset = QPoint(0, 0))
Applies the "max" filter to an image.
This is the QVision wrapper function for IPP's ippiFilterMax_32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
maskSize Corresponds to the same parameter of type IppiSize in the IPP function.
anchor Corresponds to the same parameter of type IppiPoint in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3885 of file qvippfunctions.cpp.
void FilterMedian (const QVImage< uChar, 1 > & qvimage_pSrc, QVImage< uChar, 1 > & qvimage_pDst, const QSize & maskSize = QSize(3, 3), const QPoint & anchor = QPoint(0, 0), const QPoint & destROIOffset = QPoint(0, 0))
Filters an image using a box median filter.
This is the QVision wrapper function for IPP's ippiFilterMedian_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
maskSize Corresponds to the same parameter of type IppiSize in the IPP function.
anchor Corresponds to the same parameter of type IppiPoint in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3904 of file qvippfunctions.cpp.
Referenced by FilterMedian(), QVFilterMedian_uCharC3Block::iterate(), and QVFilterMedian_uCharC1Block::iterate().
void FilterMedian (const QVImage< uChar, 3 > & qvimage_pSrc, QVImage< uChar, 3 > & qvimage_pDst, const QSize & maskSize = QSize(3, 3), const QPoint & anchor = QPoint(0, 0), const QPoint & destROIOffset = QPoint(0, 0))
Filters an image using a box median filter.
This is the QVision wrapper function for IPP's ippiFilterMedian_8u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
maskSize Corresponds to the same parameter of type IppiSize in the IPP function.
anchor Corresponds to the same parameter of type IppiPoint in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3923 of file qvippfunctions.cpp.
void FilterMedian (const QVImage< uShort, 1 > & qvimage_pSrc, QVImage< uShort, 1 > & qvimage_pDst, const QSize & maskSize = QSize(3, 3), const QPoint & anchor = QPoint(0, 0), const QPoint & destROIOffset = QPoint(0, 0))
Filters an image using a box median filter.
This is the QVision wrapper function for IPP's ippiFilterMedian_16u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
maskSize Corresponds to the same parameter of type IppiSize in the IPP function.
anchor Corresponds to the same parameter of type IppiPoint in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3942 of file qvippfunctions.cpp.
void FilterMedianHoriz (const QVImage< uChar, 1 > & qvimage_pSrc, QVImage< uChar, 1 > & qvimage_pDst, const IppiMaskSize mask = ippMskSize3x3, const QPoint & destROIOffset = QPoint(0, 0))
Performs horizontal median filtering.
This is the QVision wrapper function for IPP's ippiFilterMedianHoriz_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
mask Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3961 of file qvippfunctions.cpp.
Referenced by FilterMedianHoriz(), and QVFilterMedianHoriz_uCharC1Block::iterate().
void FilterMedianVert (const QVImage< uChar, 1 > & qvimage_pSrc, QVImage< uChar, 1 > & qvimage_pDst, const IppiMaskSize mask = ippMskSize3x3, const QPoint & destROIOffset = QPoint(0, 0))
Performs vertical median filtering.
This is the QVision wrapper function for IPP's ippiFilterMedianVert_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
mask Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3978 of file qvippfunctions.cpp.
Referenced by FilterMedianVert().
void FilterMedianCross (const QVImage< uChar, 1 > & qvimage_pSrc, QVImage< uChar, 1 > & qvimage_pDst, const IppiMaskSize mask = ippMskSize3x3, const QPoint & destROIOffset = QPoint(0, 0))
Filters an image using a cross median filter.
This is the QVision wrapper function for IPP's ippiFilterMedianCross_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
mask Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3995 of file qvippfunctions.cpp.
Referenced by FilterMedianCross().
void FilterMedianWeightedCenter3x3 (const QVImage< uChar, 1 > & qvimage_pSrc, QVImage< uChar, 1 > & qvimage_pDst, const int weight, const QPoint & destROIOffset = QPoint(0, 0))
Filter an image using a median filter with kernel size 3x3 and enlarged weight of central pixel.
This is the QVision wrapper function for IPP's ippiFilterMedianWeightedCenter3x3_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
weight Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 4013 of file qvippfunctions.cpp.
Referenced by FilterMedianWeightedCenter3x3().
void FilterMedianColor (const QVImage< uChar, 3 > & qvimage_pSrc, QVImage< uChar, 3 > & qvimage_pDst, const IppiMaskSize mask = ippMskSize3x3, const QPoint & destROIOffset = QPoint(0, 0))
Filters an image using a box color median filter.
This is the QVision wrapper function for IPP's ippiFilterMedianColor_8u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
mask Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 4029 of file qvippfunctions.cpp.
Referenced by FilterMedianColor().
void FilterSobelHorizMask (const QVImage< sFloat, 1 > & qvimage_pSrc, QVImage< sFloat, 1 > & qvimage_pDst, const IppiMaskSize mask = ippMskSize3x3, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterSobelHorizMask_32f_C1R.
This is the QVision wrapper function for IPP's ippiFilterSobelHorizMask_32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
mask Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 4046 of file qvippfunctions.cpp.
Referenced by FilterHessianCornerResponseImage(), FilterSobelHorizMask(), and QVFilterSobelHorizMask_sFloatC1Block::iterate().
void FilterSobelVertMask (const QVImage< sFloat, 1 > & qvimage_pSrc, QVImage< sFloat, 1 > & qvimage_pDst, const IppiMaskSize mask = ippMskSize3x3, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterSobelVertMask_32f_C1R.
This is the QVision wrapper function for IPP's ippiFilterSobelVertMask_32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
mask Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 4063 of file qvippfunctions.cpp.
Referenced by FilterHessianCornerResponseImage(), FilterSobelVertMask(), and QVFilterSobelVertMask_sFloatC1Block::iterate().
void FilterLaplace (const QVImage< uChar, 1 > & qvimage_pSrc, QVImage< uChar, 1 > & qvimage_pDst, const IppiMaskSize mask = ippMskSize3x3, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterLaplace_8u_C1R.
This is the QVision wrapper function for IPP's ippiFilterLaplace_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
mask Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 4080 of file qvippfunctions.cpp.
Referenced by FilterLaplace(), QVFilterLaplace_sFloatC1Block::iterate(), and QVFilterLaplace_uCharC1Block::iterate().
void FilterLaplace (const QVImage< sShort, 1 > & qvimage_pSrc, QVImage< sShort, 1 > & qvimage_pDst, const IppiMaskSize mask = ippMskSize3x3, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterLaplace_16s_C1R.
This is the QVision wrapper function for IPP's ippiFilterLaplace_16s_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
mask Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 4097 of file qvippfunctions.cpp.
void FilterLaplace (const QVImage< sFloat, 1 > & qvimage_pSrc, QVImage< sFloat, 1 > & qvimage_pDst, const IppiMaskSize mask = ippMskSize3x3, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterLaplace_32f_C1R.
This is the QVision wrapper function for IPP's ippiFilterLaplace_32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
mask Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 4114 of file qvippfunctions.cpp.
void FilterGauss (const QVImage< uChar, 1 > & qvimage_pSrc, QVImage< uChar, 1 > & qvimage_pDst, const IppiMaskSize mask = ippMskSize3x3, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterGauss_8u_C1R.
This is the QVision wrapper function for IPP's ippiFilterGauss_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
mask Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 4131 of file qvippfunctions.cpp.
Referenced by FilterDoG(), FilterGauss(), QVFilterGauss_sFloatC3Block::iterate(), QVFilterGauss_uCharC3Block::iterate(), QVFilterGauss_sFloatC1Block::iterate(), and QVFilterGauss_uCharC1Block::iterate().
void FilterGauss (const QVImage< sFloat, 1 > & qvimage_pSrc, QVImage< sFloat, 1 > & qvimage_pDst, const IppiMaskSize mask = ippMskSize3x3, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterGauss_32f_C1R.
This is the QVision wrapper function for IPP's ippiFilterGauss_32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
mask Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 4148 of file qvippfunctions.cpp.
void FilterGauss (const QVImage< uChar, 3 > & qvimage_pSrc, QVImage< uChar, 3 > & qvimage_pDst, const IppiMaskSize mask = ippMskSize3x3, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterGauss_8u_C3R.
This is the QVision wrapper function for IPP's ippiFilterGauss_8u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
mask Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 4165 of file qvippfunctions.cpp.
void FilterGauss (const QVImage< sFloat, 3 > & qvimage_pSrc, QVImage< sFloat, 3 > & qvimage_pDst, const IppiMaskSize mask = ippMskSize3x3, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterGauss_32f_C3R.
This is the QVision wrapper function for IPP's ippiFilterGauss_32f_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
mask Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 4182 of file qvippfunctions.cpp.
void FilterHipass (const QVImage< uChar, 1 > & qvimage_pSrc, QVImage< uChar, 1 > & qvimage_pDst, const IppiMaskSize mask = ippMskSize3x3, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterHipass_8u_C1R.
This is the QVision wrapper function for IPP's ippiFilterHipass_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
mask Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 4199 of file qvippfunctions.cpp.
Referenced by FilterHipass(), QVFilterHipass_sFloatC3Block::iterate(), QVFilterHipass_sFloatC1Block::iterate(), QVFilterHipass_uCharC3Block::iterate(), and QVFilterHipass_uCharC1Block::iterate().
void FilterHipass (const QVImage< uChar, 3 > & qvimage_pSrc, QVImage< uChar, 3 > & qvimage_pDst, const IppiMaskSize mask = ippMskSize3x3, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterHipass_8u_C3R.
This is the QVision wrapper function for IPP's ippiFilterHipass_8u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
mask Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 4216 of file qvippfunctions.cpp.
void FilterHipass (const QVImage< sFloat, 1 > & qvimage_pSrc, QVImage< sFloat, 1 > & qvimage_pDst, const IppiMaskSize mask = ippMskSize3x3, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterHipass_32f_C1R.
This is the QVision wrapper function for IPP's ippiFilterHipass_32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
mask Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 4233 of file qvippfunctions.cpp.
void FilterHipass (const QVImage< sFloat, 3 > & qvimage_pSrc, QVImage< sFloat, 3 > & qvimage_pDst, const IppiMaskSize mask = ippMskSize3x3, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterHipass_32f_C3R.
This is the QVision wrapper function for IPP's ippiFilterHipass_32f_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
mask Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 4250 of file qvippfunctions.cpp.
void FilterLowpass (const QVImage< uChar, 1 > & qvimage_pSrc, QVImage< uChar, 1 > & qvimage_pDst, const IppiMaskSize mask = ippMskSize3x3, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterLowpass_8u_C1R.
This is the QVision wrapper function for IPP's ippiFilterLowpass_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
mask Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 4267 of file qvippfunctions.cpp.
Referenced by FilterLowpass(), QVFilterLowpass_sFloatC1Block::iterate(), and QVFilterLowpass_uCharC1Block::iterate().
void FilterLowpass (const QVImage< sFloat, 1 > & qvimage_pSrc, QVImage< sFloat, 1 > & qvimage_pDst, const IppiMaskSize mask = ippMskSize3x3, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiFilterLowpass_32f_C1R.
This is the QVision wrapper function for IPP's ippiFilterLowpass_32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
mask Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 4284 of file qvippfunctions.cpp.
QVision framework. PARP research group. Copyright © 2007, 2008, 2009, 2010, 2011.