QVision: Qt's Image, Video and Computer Vision Library
PARP Research Group Universidad de Murcia
Image Statistics Functions
[IPP wrapper functions]
Functions that can be used to compute the following statistical parameters of an image.
Functions
void Sum (const QVImage< uChar, 1 > &qvimage_pSrc, sDouble &pSum)
Computes the sum of image pixel values.
void Sum (const QVImage< uChar, 3 > &qvimage_pSrc, sDouble sum[3])
Computes the sum of image pixel values.
void Sum (const QVImage< sShort, 1 > &qvimage_pSrc, sDouble &pSum)
Computes the sum of image pixel values.
void Sum (const QVImage< sShort, 3 > &qvimage_pSrc, sDouble sum[3])
Computes the sum of image pixel values.
void Integral (const QVImage< uChar, 1 > &qvimage_pSrc, QVImage< sInt, 1 > &qvimage_pDst, const sInt val, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiIntegral_8u32s_C1R.
void Integral (const QVImage< uChar, 1 > &qvimage_pSrc, QVImage< sFloat, 1 > &qvimage_pDst, const sFloat val, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiIntegral_8u32f_C1R.
void Mean (const QVImage< uChar, 1 > &qvimage_pSrc, sDouble &pMean)
Computes the mean of image pixel values.
void Mean (const QVImage< uChar, 3 > &qvimage_pSrc, sDouble mean[3])
Computes the mean of image pixel values.
void Mean (const QVImage< sShort, 1 > &qvimage_pSrc, sDouble &pMean)
Computes the mean of image pixel values.
void Mean (const QVImage< sShort, 3 > &qvimage_pSrc, sDouble mean[3])
Computes the mean of image pixel values.
void Min (const QVImage< uChar, 1 > &qvimage_pSrc, uChar &pMin)
Computes the minimum of image pixel values.
void Min (const QVImage< uChar, 3 > &qvimage_pSrc, uChar min[3])
Computes the minimum of image pixel values.
void Min (const QVImage< sShort, 1 > &qvimage_pSrc, sShort &pMin)
Computes the minimum of image pixel values.
void Min (const QVImage< sShort, 3 > &qvimage_pSrc, sShort min[3])
Computes the minimum of image pixel values.
void Min (const QVImage< sFloat, 1 > &qvimage_pSrc, sFloat &pMin)
Computes the minimum of image pixel values.
void Max (const QVImage< uChar, 1 > &qvimage_pSrc, uChar &pMax)
Computes the maximum of image pixel values.
void Max (const QVImage< uChar, 3 > &qvimage_pSrc, uChar max[3])
Computes the maximum of image pixel values.
void Max (const QVImage< sShort, 1 > &qvimage_pSrc, sShort &pMax)
Computes the maximum of image pixel values.
void Max (const QVImage< sShort, 3 > &qvimage_pSrc, sShort max[3])
Computes the maximum of image pixel values.
void Max (const QVImage< sFloat, 1 > &qvimage_pSrc, sFloat &pMax)
Computes the maximum of image pixel values.
void MinEvery (const QVImage< uChar, 1 > &qvimage_pSrc, QVImage< uChar, 1 > &qvimage_pSrcDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiMinEvery_8u_C1IR.
void MinEvery (const QVImage< uChar, 3 > &qvimage_pSrc, QVImage< uChar, 3 > &qvimage_pSrcDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiMinEvery_8u_C3IR.
void MinEvery (const QVImage< sShort, 1 > &qvimage_pSrc, QVImage< sShort, 1 > &qvimage_pSrcDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiMinEvery_16s_C1IR.
void MinEvery (const QVImage< sShort, 3 > &qvimage_pSrc, QVImage< sShort, 3 > &qvimage_pSrcDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiMinEvery_16s_C3IR.
void MinEvery (const QVImage< sFloat, 1 > &qvimage_pSrc, QVImage< sFloat, 1 > &qvimage_pSrcDst, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiMinEvery_32f_C1IR.
void MaxEvery (const QVImage< uChar, 1 > &qvimage_pSrc, QVImage< uChar, 1 > &qvimage_pSrcDst, const QPoint &destROIOffset=QPoint(0, 0))
Calculation min max value for every element of two images.
void MaxEvery (const QVImage< uChar, 3 > &qvimage_pSrc, QVImage< uChar, 3 > &qvimage_pSrcDst, const QPoint &destROIOffset=QPoint(0, 0))
Calculation min max value for every element of two images.
void MaxEvery (const QVImage< sShort, 1 > &qvimage_pSrc, QVImage< sShort, 1 > &qvimage_pSrcDst, const QPoint &destROIOffset=QPoint(0, 0))
Calculation min max value for every element of two images.
void MaxEvery (const QVImage< sShort, 3 > &qvimage_pSrc, QVImage< sShort, 3 > &qvimage_pSrcDst, const QPoint &destROIOffset=QPoint(0, 0))
Calculation min max value for every element of two images.
void MaxEvery (const QVImage< sFloat, 1 > &qvimage_pSrc, QVImage< sFloat, 1 > &qvimage_pSrcDst, const QPoint &destROIOffset=QPoint(0, 0))
Calculation min max value for every element of two images.
Detailed Description
Functions that can be used to compute the following statistical parameters of an image.
Function Documentation
void Sum (const QVImage< uChar, 1 > & qvimage_pSrc, sDouble & pSum)
Computes the sum of image pixel values.
This is the QVision wrapper function for IPP's ippiSum_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
pSum Corresponds to the same parameter in the IPP function.
Definition at line 4301 of file qvippfunctions.cpp.
Referenced by QVSum_uCharC1Block::iterate(), and Sum().
void Sum (const QVImage< uChar, 3 > & qvimage_pSrc, sDouble sum[3])
Computes the sum of image pixel values.
This is the QVision wrapper function for IPP's ippiSum_8u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
sum Corresponds to the same parameter in the IPP function.
Definition at line 4312 of file qvippfunctions.cpp.
void Sum (const QVImage< sShort, 1 > & qvimage_pSrc, sDouble & pSum)
Computes the sum of image pixel values.
This is the QVision wrapper function for IPP's ippiSum_16s_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
pSum Corresponds to the same parameter in the IPP function.
Definition at line 4323 of file qvippfunctions.cpp.
void Sum (const QVImage< sShort, 3 > & qvimage_pSrc, sDouble sum[3])
Computes the sum of image pixel values.
This is the QVision wrapper function for IPP's ippiSum_16s_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
sum Corresponds to the same parameter in the IPP function.
Definition at line 4334 of file qvippfunctions.cpp.
void Integral (const QVImage< uChar, 1 > & qvimage_pSrc, QVImage< sInt, 1 > & qvimage_pDst, const sInt val, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiIntegral_8u32s_C1R.
This is the QVision wrapper function for IPP's ippiIntegral_8u32s_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
val Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 4345 of file qvippfunctions.cpp.
Referenced by Integral().
void Integral (const QVImage< uChar, 1 > & qvimage_pSrc, QVImage< sFloat, 1 > & qvimage_pDst, const sFloat val, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiIntegral_8u32f_C1R.
This is the QVision wrapper function for IPP's ippiIntegral_8u32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
val Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 4361 of file qvippfunctions.cpp.
void Mean (const QVImage< uChar, 1 > & qvimage_pSrc, sDouble & pMean)
Computes the mean of image pixel values.
This is the QVision wrapper function for IPP's ippiMean_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
pMean Corresponds to the same parameter in the IPP function.
Definition at line 4377 of file qvippfunctions.cpp.
Referenced by QVMean_uCharC1Block::iterate(), and Mean().
void Mean (const QVImage< uChar, 3 > & qvimage_pSrc, sDouble mean[3])
Computes the mean of image pixel values.
This is the QVision wrapper function for IPP's ippiMean_8u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
mean Corresponds to the same parameter in the IPP function.
Definition at line 4388 of file qvippfunctions.cpp.
void Mean (const QVImage< sShort, 1 > & qvimage_pSrc, sDouble & pMean)
Computes the mean of image pixel values.
This is the QVision wrapper function for IPP's ippiMean_16s_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
pMean Corresponds to the same parameter in the IPP function.
Definition at line 4399 of file qvippfunctions.cpp.
void Mean (const QVImage< sShort, 3 > & qvimage_pSrc, sDouble mean[3])
Computes the mean of image pixel values.
This is the QVision wrapper function for IPP's ippiMean_16s_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
mean Corresponds to the same parameter in the IPP function.
Definition at line 4410 of file qvippfunctions.cpp.
void Min (const QVImage< uChar, 1 > & qvimage_pSrc, uChar & pMin)
Computes the minimum of image pixel values.
This is the QVision wrapper function for IPP's ippiMin_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
pMin Corresponds to the same parameter in the IPP function.
Definition at line 4421 of file qvippfunctions.cpp.
Referenced by QVMin_sFloatC1Block::iterate(), QVMin_uCharC1Block::iterate(), and Min().
void Min (const QVImage< uChar, 3 > & qvimage_pSrc, uChar min[3])
Computes the minimum of image pixel values.
This is the QVision wrapper function for IPP's ippiMin_8u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
min Corresponds to the same parameter in the IPP function.
Definition at line 4432 of file qvippfunctions.cpp.
void Min (const QVImage< sShort, 1 > & qvimage_pSrc, sShort & pMin)
Computes the minimum of image pixel values.
This is the QVision wrapper function for IPP's ippiMin_16s_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
pMin Corresponds to the same parameter in the IPP function.
Definition at line 4443 of file qvippfunctions.cpp.
void Min (const QVImage< sShort, 3 > & qvimage_pSrc, sShort min[3])
Computes the minimum of image pixel values.
This is the QVision wrapper function for IPP's ippiMin_16s_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
min Corresponds to the same parameter in the IPP function.
Definition at line 4454 of file qvippfunctions.cpp.
void Min (const QVImage< sFloat, 1 > & qvimage_pSrc, sFloat & pMin)
Computes the minimum of image pixel values.
This is the QVision wrapper function for IPP's ippiMin_32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
pMin Corresponds to the same parameter in the IPP function.
Definition at line 4465 of file qvippfunctions.cpp.
void Max (const QVImage< uChar, 1 > & qvimage_pSrc, uChar & pMax)
Computes the maximum of image pixel values.
This is the QVision wrapper function for IPP's ippiMax_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
pMax Corresponds to the same parameter in the IPP function.
Definition at line 4476 of file qvippfunctions.cpp.
Referenced by QVMax_sFloatC1Block::iterate(), QVMax_uCharC1Block::iterate(), and Max().
void Max (const QVImage< uChar, 3 > & qvimage_pSrc, uChar max[3])
Computes the maximum of image pixel values.
This is the QVision wrapper function for IPP's ippiMax_8u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
max Corresponds to the same parameter in the IPP function.
Definition at line 4487 of file qvippfunctions.cpp.
void Max (const QVImage< sShort, 1 > & qvimage_pSrc, sShort & pMax)
Computes the maximum of image pixel values.
This is the QVision wrapper function for IPP's ippiMax_16s_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
pMax Corresponds to the same parameter in the IPP function.
Definition at line 4498 of file qvippfunctions.cpp.
void Max (const QVImage< sShort, 3 > & qvimage_pSrc, sShort max[3])
Computes the maximum of image pixel values.
This is the QVision wrapper function for IPP's ippiMax_16s_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
max Corresponds to the same parameter in the IPP function.
Definition at line 4509 of file qvippfunctions.cpp.
void Max (const QVImage< sFloat, 1 > & qvimage_pSrc, sFloat & pMax)
Computes the maximum of image pixel values.
This is the QVision wrapper function for IPP's ippiMax_32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
pMax Corresponds to the same parameter in the IPP function.
Definition at line 4520 of file qvippfunctions.cpp.
void MinEvery (const QVImage< uChar, 1 > & qvimage_pSrc, QVImage< uChar, 1 > & qvimage_pSrcDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiMinEvery_8u_C1IR.
This is the QVision wrapper function for IPP's ippiMinEvery_8u_C1IR. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pSrcDst Image corresponding to the data buffer pointer pSrcDst and step number srcDstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 4531 of file qvippfunctions.cpp.
Referenced by MinEvery().
void MinEvery (const QVImage< uChar, 3 > & qvimage_pSrc, QVImage< uChar, 3 > & qvimage_pSrcDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiMinEvery_8u_C3IR.
This is the QVision wrapper function for IPP's ippiMinEvery_8u_C3IR. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pSrcDst Image corresponding to the data buffer pointer pSrcDst and step number srcDstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 4545 of file qvippfunctions.cpp.
void MinEvery (const QVImage< sShort, 1 > & qvimage_pSrc, QVImage< sShort, 1 > & qvimage_pSrcDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiMinEvery_16s_C1IR.
This is the QVision wrapper function for IPP's ippiMinEvery_16s_C1IR. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pSrcDst Image corresponding to the data buffer pointer pSrcDst and step number srcDstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 4559 of file qvippfunctions.cpp.
void MinEvery (const QVImage< sShort, 3 > & qvimage_pSrc, QVImage< sShort, 3 > & qvimage_pSrcDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiMinEvery_16s_C3IR.
This is the QVision wrapper function for IPP's ippiMinEvery_16s_C3IR. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pSrcDst Image corresponding to the data buffer pointer pSrcDst and step number srcDstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 4573 of file qvippfunctions.cpp.
void MinEvery (const QVImage< sFloat, 1 > & qvimage_pSrc, QVImage< sFloat, 1 > & qvimage_pSrcDst, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiMinEvery_32f_C1IR.
This is the QVision wrapper function for IPP's ippiMinEvery_32f_C1IR. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pSrcDst Image corresponding to the data buffer pointer pSrcDst and step number srcDstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 4587 of file qvippfunctions.cpp.
void MaxEvery (const QVImage< uChar, 1 > & qvimage_pSrc, QVImage< uChar, 1 > & qvimage_pSrcDst, const QPoint & destROIOffset = QPoint(0, 0))
Calculation min max value for every element of two images.
This is the QVision wrapper function for IPP's ippiMaxEvery_8u_C1IR. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pSrcDst Image corresponding to the data buffer pointer pSrcDst and step number srcDstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 4601 of file qvippfunctions.cpp.
Referenced by MaxEvery().
void MaxEvery (const QVImage< uChar, 3 > & qvimage_pSrc, QVImage< uChar, 3 > & qvimage_pSrcDst, const QPoint & destROIOffset = QPoint(0, 0))
Calculation min max value for every element of two images.
This is the QVision wrapper function for IPP's ippiMaxEvery_8u_C3IR. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pSrcDst Image corresponding to the data buffer pointer pSrcDst and step number srcDstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 4615 of file qvippfunctions.cpp.
void MaxEvery (const QVImage< sShort, 1 > & qvimage_pSrc, QVImage< sShort, 1 > & qvimage_pSrcDst, const QPoint & destROIOffset = QPoint(0, 0))
Calculation min max value for every element of two images.
This is the QVision wrapper function for IPP's ippiMaxEvery_16s_C1IR. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pSrcDst Image corresponding to the data buffer pointer pSrcDst and step number srcDstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 4629 of file qvippfunctions.cpp.
void MaxEvery (const QVImage< sShort, 3 > & qvimage_pSrc, QVImage< sShort, 3 > & qvimage_pSrcDst, const QPoint & destROIOffset = QPoint(0, 0))
Calculation min max value for every element of two images.
This is the QVision wrapper function for IPP's ippiMaxEvery_16s_C3IR. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pSrcDst Image corresponding to the data buffer pointer pSrcDst and step number srcDstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 4643 of file qvippfunctions.cpp.
void MaxEvery (const QVImage< sFloat, 1 > & qvimage_pSrc, QVImage< sFloat, 1 > & qvimage_pSrcDst, const QPoint & destROIOffset = QPoint(0, 0))
Calculation min max value for every element of two images.
This is the QVision wrapper function for IPP's ippiMaxEvery_32f_C1IR. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pSrcDst Image corresponding to the data buffer pointer pSrcDst and step number srcDstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 4657 of file qvippfunctions.cpp.
QVision framework. PARP research group. Copyright © 2007, 2008, 2009, 2010, 2011.