QVision: Qt's Image, Video and Computer Vision Library
PARP Research Group Universidad de Murcia
Image Data Exchange and Initialization Functions
[IPP wrapper functions]
Image processing functions that perform image data manipulation, exchange and initialization operations.
Functions
void Copy (const QVImage< uChar, 1 > &src1, const QVImage< uChar, 1 > &src2, const QVImage< uChar, 1 > &src3, QVImage< uChar, 3 > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Composes color image from separate channel imagesThis function copies data from a source 1-channel image ROI src, to each of the channels of the destination 3-channel image ROI dest.
void Copy (const QVImage< uShort, 1 > &src1, const QVImage< uShort, 1 > &src2, const QVImage< uShort, 1 > &src3, QVImage< uShort, 3 > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Composes color image from separate channel images.
void Copy (const QVImage< sShort, 1 > &src1, const QVImage< sShort, 1 > &src2, const QVImage< sShort, 1 > &src3, QVImage< sShort, 3 > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Composes color image from separate channel images.
void Copy (const QVImage< sInt, 1 > &src1, const QVImage< sInt, 1 > &src2, const QVImage< sInt, 1 > &src3, QVImage< sInt, 3 > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Composes color image from separate channel images.
void Copy (const QVImage< sFloat, 1 > &src1, const QVImage< sFloat, 1 > &src2, const QVImage< sFloat, 1 > &src3, QVImage< sFloat, 3 > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Composes color image from separate channel images.
void Copy (const QVImage< uChar, 3 > &src, QVImage< uChar, 1 > &dest1, QVImage< uChar, 1 > &dest2, QVImage< uChar, 1 > &dest3, const QPoint &destROIOffset=QPoint(0, 0))
void Copy (const QVImage< sFloat, 3 > &src, QVImage< sFloat, 1 > &dest1, QVImage< sFloat, 1 > &dest2, QVImage< sFloat, 1 > &dest3, const QPoint &destROIOffset=QPoint(0, 0))
void Copy (const QVImage< uChar, 3 > &src, const uChar channel, QVImage< uChar, 1 > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Copy a selected channel from a 3-channel image to a 1-channel imageThis function converts an RGB image to gray scale.
void Copy (const QVImage< uShort, 3 > &src, const uChar channel, QVImage< uShort, 1 > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Copy a selected channel from a 3-channel image to a 1-channel image.
void Copy (const QVImage< sShort, 3 > &src, const uChar channel, QVImage< sShort, 1 > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Copy a selected channel from a 3-channel image to a 1-channel image.
void Copy (const QVImage< sInt, 3 > &src, const uChar channel, QVImage< sInt, 1 > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Copy a selected channel from a 3-channel image to a 1-channel image.
void Copy (const QVImage< sFloat, 3 > &src, const uChar channel, QVImage< sFloat, 1 > &dest, const QPoint &destROIOffset=QPoint(0, 0))
Copy a selected channel from a 3-channel image to a 1-channel image.
void Compare (const QVImage< uChar, 3 > &src1, const QVImage< uChar, 3 > &src2, QVImage< uChar > &dest, IppCmpOp ippCmpOp=ippCmpEq, const QPoint &destROIOffset=QPoint(0, 0))
Compares pixel values of two images using a specified compare operation.
void Convert (const QVImage< uChar, 1 > &qvimage_pSrc, QVImage< uShort, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
void Convert (const QVImage< uChar, 1 > &qvimage_pSrc, QVImage< sShort, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
void Convert (const QVImage< uChar, 1 > &qvimage_pSrc, QVImage< sInt, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
void Convert (const QVImage< uChar, 1 > &qvimage_pSrc, QVImage< sFloat, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
void Convert (const QVImage< uChar, 3 > &qvimage_pSrc, QVImage< uShort, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
void Convert (const QVImage< uChar, 3 > &qvimage_pSrc, QVImage< sShort, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
void Convert (const QVImage< uChar, 3 > &qvimage_pSrc, QVImage< sInt, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
void Convert (const QVImage< uChar, 3 > &qvimage_pSrc, QVImage< sFloat, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
void Convert (const QVImage< uShort, 1 > &qvimage_pSrc, QVImage< uChar, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
void Convert (const QVImage< uShort, 1 > &qvimage_pSrc, QVImage< sInt, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
void Convert (const QVImage< uShort, 1 > &qvimage_pSrc, QVImage< sFloat, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
void Convert (const QVImage< uShort, 3 > &qvimage_pSrc, QVImage< uChar, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
void Convert (const QVImage< uShort, 3 > &qvimage_pSrc, QVImage< sInt, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
void Convert (const QVImage< uShort, 3 > &qvimage_pSrc, QVImage< sFloat, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
void Convert (const QVImage< sShort, 1 > &qvimage_pSrc, QVImage< uChar, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
void Convert (const QVImage< sShort, 1 > &qvimage_pSrc, QVImage< sInt, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
void Convert (const QVImage< sShort, 1 > &qvimage_pSrc, QVImage< sFloat, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
void Convert (const QVImage< sShort, 3 > &qvimage_pSrc, QVImage< uChar, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
void Convert (const QVImage< sShort, 3 > &qvimage_pSrc, QVImage< sInt, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
void Convert (const QVImage< sShort, 3 > &qvimage_pSrc, QVImage< sFloat, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
void Convert (const QVImage< sInt, 1 > &qvimage_pSrc, QVImage< uChar, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
void Convert (const QVImage< sInt, 3 > &qvimage_pSrc, QVImage< uChar, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
void Convert (const QVImage< sFloat, 1 > &qvimage_pSrc, QVImage< uChar, 1 > &qvimage_pDst, const IppRoundMode roundMode=ippRndNear, const QPoint &destROIOffset=QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
void Convert (const QVImage< sFloat, 1 > &qvimage_pSrc, QVImage< uShort, 1 > &qvimage_pDst, const IppRoundMode roundMode=ippRndNear, const QPoint &destROIOffset=QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
void Convert (const QVImage< sFloat, 1 > &qvimage_pSrc, QVImage< sShort, 1 > &qvimage_pDst, const IppRoundMode roundMode=ippRndNear, const QPoint &destROIOffset=QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
void Convert (const QVImage< sFloat, 3 > &qvimage_pSrc, QVImage< uChar, 3 > &qvimage_pDst, const IppRoundMode roundMode=ippRndNear, const QPoint &destROIOffset=QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
void Convert (const QVImage< sFloat, 3 > &qvimage_pSrc, QVImage< uShort, 3 > &qvimage_pDst, const IppRoundMode roundMode=ippRndNear, const QPoint &destROIOffset=QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
void Convert (const QVImage< sFloat, 3 > &qvimage_pSrc, QVImage< sShort, 3 > &qvimage_pDst, const IppRoundMode roundMode=ippRndNear, const QPoint &destROIOffset=QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
void Scale (const QVImage< uChar, 1 > &qvimage_pSrc, QVImage< uShort, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Scales pixel values of an image and converts them to another bit depth dst = a + b * src; a = type_min_dst - b * type_min_src; b = (type_max_dst - type_min_dst) (type_max_src - type_min_src).
void Scale (const QVImage< uChar, 1 > &qvimage_pSrc, QVImage< sShort, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Scales pixel values of an image and converts them to another bit depth dst = a + b * src; a = type_min_dst - b * type_min_src; b = (type_max_dst - type_min_dst) (type_max_src - type_min_src).
void Scale (const QVImage< uChar, 1 > &qvimage_pSrc, QVImage< sInt, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Scales pixel values of an image and converts them to another bit depth dst = a + b * src; a = type_min_dst - b * type_min_src; b = (type_max_dst - type_min_dst) (type_max_src - type_min_src).
void Scale (const QVImage< uChar, 3 > &qvimage_pSrc, QVImage< uShort, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Scales pixel values of an image and converts them to another bit depth dst = a + b * src; a = type_min_dst - b * type_min_src; b = (type_max_dst - type_min_dst) (type_max_src - type_min_src).
void Scale (const QVImage< uChar, 3 > &qvimage_pSrc, QVImage< sShort, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Scales pixel values of an image and converts them to another bit depth dst = a + b * src; a = type_min_dst - b * type_min_src; b = (type_max_dst - type_min_dst) (type_max_src - type_min_src).
void Scale (const QVImage< uChar, 3 > &qvimage_pSrc, QVImage< sInt, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Scales pixel values of an image and converts them to another bit depth dst = a + b * src; a = type_min_dst - b * type_min_src; b = (type_max_dst - type_min_dst) (type_max_src - type_min_src).
void Set (const uChar value, QVImage< uChar, 1 > &qvimage_pDst)
Sets pixels in the image buffer to a constant value.
void Set (const uShort value, QVImage< uShort, 1 > &qvimage_pDst)
Sets pixels in the image buffer to a constant value.
void Set (const sShort value, QVImage< sShort, 1 > &qvimage_pDst)
Sets pixels in the image buffer to a constant value.
void Set (const sInt value, QVImage< sInt, 1 > &qvimage_pDst)
Sets pixels in the image buffer to a constant value.
void Set (const sFloat value, QVImage< sFloat, 1 > &qvimage_pDst)
Sets pixels in the image buffer to a constant value.
void Set (const uChar value[3], QVImage< uChar, 3 > &qvimage_pDst)
Sets pixels in the image buffer to a constant value.
void Set (const uShort value[3], QVImage< uShort, 3 > &qvimage_pDst)
Sets pixels in the image buffer to a constant value.
void Set (const sShort value[3], QVImage< sShort, 3 > &qvimage_pDst)
Sets pixels in the image buffer to a constant value.
void Set (const sInt value[3], QVImage< sInt, 3 > &qvimage_pDst)
Sets pixels in the image buffer to a constant value.
void Set (const sFloat value[3], QVImage< sFloat, 3 > &qvimage_pDst)
Sets pixels in the image buffer to a constant value.
void Copy (const QVImage< uChar, 1 > &qvimage_pSrc, QVImage< uChar, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Copy pixel values from the source image to the destination image.
void Copy (const QVImage< uChar, 3 > &qvimage_pSrc, QVImage< uChar, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Copy pixel values from the source image to the destination image.
void Copy (const QVImage< uShort, 1 > &qvimage_pSrc, QVImage< uShort, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Copy pixel values from the source image to the destination image.
void Copy (const QVImage< uShort, 3 > &qvimage_pSrc, QVImage< uShort, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Copy pixel values from the source image to the destination image.
void Copy (const QVImage< sShort, 1 > &qvimage_pSrc, QVImage< sShort, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Copy pixel values from the source image to the destination image.
void Copy (const QVImage< sShort, 3 > &qvimage_pSrc, QVImage< sShort, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Copy pixel values from the source image to the destination image.
void Copy (const QVImage< sInt, 1 > &qvimage_pSrc, QVImage< sInt, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Copy pixel values from the source image to the destination image.
void Copy (const QVImage< sInt, 3 > &qvimage_pSrc, QVImage< sInt, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Copy pixel values from the source image to the destination image.
void Copy (const QVImage< sFloat, 1 > &qvimage_pSrc, QVImage< sFloat, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Copy pixel values from the source image to the destination image.
void Copy (const QVImage< sFloat, 3 > &qvimage_pSrc, QVImage< sFloat, 3 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Copy pixel values from the source image to the destination image.
void AddRandUniform_Direct (QVImage< uChar, 1 > &qvimage_pSrcDst, const uChar low, const uChar high, unsigned int &pSeed)
Generates pseudo-random samples with uniform distribution and adds them to an image.
void AddRandUniform_Direct (QVImage< uShort, 1 > &qvimage_pSrcDst, const uShort low, const uShort high, unsigned int &pSeed)
Generates pseudo-random samples with uniform distribution and adds them to an image.
void AddRandUniform_Direct (QVImage< sShort, 1 > &qvimage_pSrcDst, const sShort low, const sShort high, unsigned int &pSeed)
Generates pseudo-random samples with uniform distribution and adds them to an image.
void AddRandUniform_Direct (QVImage< sFloat, 1 > &qvimage_pSrcDst, const sFloat low, const sFloat high, unsigned int &pSeed)
Generates pseudo-random samples with uniform distribution and adds them to an image.
void AddRandUniform_Direct (QVImage< uChar, 3 > &qvimage_pSrcDst, const uChar low, const uChar high, unsigned int &pSeed)
Generates pseudo-random samples with uniform distribution and adds them to an image.
void AddRandUniform_Direct (QVImage< uShort, 3 > &qvimage_pSrcDst, const uShort low, const uShort high, unsigned int &pSeed)
Generates pseudo-random samples with uniform distribution and adds them to an image.
void AddRandUniform_Direct (QVImage< sShort, 3 > &qvimage_pSrcDst, const sShort low, const sShort high, unsigned int &pSeed)
Generates pseudo-random samples with uniform distribution and adds them to an image.
void AddRandUniform_Direct (QVImage< sFloat, 3 > &qvimage_pSrcDst, const sFloat low, const sFloat high, unsigned int &pSeed)
Generates pseudo-random samples with uniform distribution and adds them to an image.
Detailed Description
Image processing functions that perform image data manipulation, exchange and initialization operations.
Function Documentation
void Copy (const QVImage< uChar, 1 > & src1, const QVImage< uChar, 1 > & src2, const QVImage< uChar, 1 > & src3, QVImage< uChar, 3 > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Composes color image from separate channel imagesThis function copies data from a source 1-channel image ROI src, to each of the channels of the destination 3-channel image ROI dest.
Todo:
Problema con las funciones IPP: al llamar a una funcin no inline con la misma imagen de entrada que de salida, por ejemplo:
QVImage<uChar> image = ...;
FilterBox(image, image);
Los bufferes que se le pasarn a la llamada de la ippiFilterBox sern los mismos. El cdigo correcto, que s funciona, sera este:
QVImage<uChar> image = ... , temp = image;
FilterBox(temp, image);
Parameters:
src1 source image for first channel.
src2 source image for second channel.
src3 source image for third channel.
dest destination image.
void Copy (const QVImage< uShort, 1 > & src1, const QVImage< uShort, 1 > & src2, const QVImage< uShort, 1 > & src3, QVImage< uShort, 3 > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Composes color image from separate channel images.
See also:
Copy(const QVImage<uChar, 1> &, const QVImage<uChar, 1> &, const QVImage<uChar, 1> &, QVImage<uChar, 3> &)
void Copy (const QVImage< sShort, 1 > & src1, const QVImage< sShort, 1 > & src2, const QVImage< sShort, 1 > & src3, QVImage< sShort, 3 > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Composes color image from separate channel images.
See also:
Copy(const QVImage<uChar, 1> &, const QVImage<uChar, 1> &, const QVImage<uChar, 1> &, QVImage<uChar, 3> &)
void Copy (const QVImage< sInt, 1 > & src1, const QVImage< sInt, 1 > & src2, const QVImage< sInt, 1 > & src3, QVImage< sInt, 3 > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Composes color image from separate channel images.
See also:
Copy(const QVImage<uChar, 1> &, const QVImage<uChar, 1> &, const QVImage<uChar, 1> &, QVImage<uChar, 3> &)
void Copy (const QVImage< sFloat, 1 > & src1, const QVImage< sFloat, 1 > & src2, const QVImage< sFloat, 1 > & src3, QVImage< sFloat, 3 > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Composes color image from separate channel images.
See also:
Copy(const QVImage<uChar, 1> &, const QVImage<uChar, 1> &, const QVImage<uChar, 1> &, QVImage<uChar, 3> &)
void Copy (const QVImage< uChar, 3 > & src, QVImage< uChar, 1 > & dest1, QVImage< uChar, 1 > & dest2, QVImage< uChar, 1 > & dest3, const QPoint & destROIOffset = QPoint(0, 0))
Todo:
Document.
void Copy (const QVImage< sFloat, 3 > & src, QVImage< sFloat, 1 > & dest1, QVImage< sFloat, 1 > & dest2, QVImage< sFloat, 1 > & dest3, const QPoint & destROIOffset = QPoint(0, 0))
Todo:
Document.
void Copy (const QVImage< uChar, 3 > & src, const uChar channel, QVImage< uChar, 1 > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Copy a selected channel from a 3-channel image to a 1-channel imageThis function converts an RGB image to gray scale.
Parameters:
src source image.
dest destination image.
channel number of channel to copy.
void Copy (const QVImage< uShort, 3 > & src, const uChar channel, QVImage< uShort, 1 > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Copy a selected channel from a 3-channel image to a 1-channel image.
See also:
Copy(const QVImage<uChar, 3> &, QVImage<uChar, 1> &, uChar)
void Copy (const QVImage< sShort, 3 > & src, const uChar channel, QVImage< sShort, 1 > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Copy a selected channel from a 3-channel image to a 1-channel image.
See also:
Copy(const QVImage<uChar, 3> &, QVImage<uChar, 1> &, uChar)
void Copy (const QVImage< sInt, 3 > & src, const uChar channel, QVImage< sInt, 1 > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Copy a selected channel from a 3-channel image to a 1-channel image.
See also:
Copy(const QVImage<uChar, 3> &, QVImage<uChar, 1> &, uChar)
void Copy (const QVImage< sFloat, 3 > & src, const uChar channel, QVImage< sFloat, 1 > & dest, const QPoint & destROIOffset = QPoint(0, 0))
Copy a selected channel from a 3-channel image to a 1-channel image.
See also:
Copy(const QVImage<uChar, 3> &, QVImage<uChar, 1> &, uChar)
void Compare (const QVImage< uChar, 3 > & src1, const QVImage< uChar, 3 > & src2, QVImage< uChar > & dest, IppCmpOp ippCmpOp = ippCmpEq, const QPoint & destROIOffset = QPoint(0, 0))
Compares pixel values of two images using a specified compare operation.
See also:
void Compare(const QVImage<uChar> &, const QVImage<uChar> &src2, QVImage<uChar> &, IppCmpOp)
Referenced by Compare(), QVCompare_sFloatC1Block::iterate(), and QVCompare_uCharC1Block::iterate().
void Convert (const QVImage< uChar, 1 > & qvimage_pSrc, QVImage< uShort, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
This is the QVision wrapper function for IPP's ippiConvert_8u16u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 29 of file qvippfunctions.cpp.
void Convert (const QVImage< uChar, 1 > & qvimage_pSrc, QVImage< sShort, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
This is the QVision wrapper function for IPP's ippiConvert_8u16s_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 43 of file qvippfunctions.cpp.
void Convert (const QVImage< uChar, 1 > & qvimage_pSrc, QVImage< sInt, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
This is the QVision wrapper function for IPP's ippiConvert_8u32s_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 57 of file qvippfunctions.cpp.
void Convert (const QVImage< uChar, 1 > & qvimage_pSrc, QVImage< sFloat, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
This is the QVision wrapper function for IPP's ippiConvert_8u32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 71 of file qvippfunctions.cpp.
void Convert (const QVImage< uChar, 3 > & qvimage_pSrc, QVImage< uShort, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
This is the QVision wrapper function for IPP's ippiConvert_8u16u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 85 of file qvippfunctions.cpp.
void Convert (const QVImage< uChar, 3 > & qvimage_pSrc, QVImage< sShort, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
This is the QVision wrapper function for IPP's ippiConvert_8u16s_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 99 of file qvippfunctions.cpp.
void Convert (const QVImage< uChar, 3 > & qvimage_pSrc, QVImage< sInt, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
This is the QVision wrapper function for IPP's ippiConvert_8u32s_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 113 of file qvippfunctions.cpp.
void Convert (const QVImage< uChar, 3 > & qvimage_pSrc, QVImage< sFloat, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
This is the QVision wrapper function for IPP's ippiConvert_8u32f_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 127 of file qvippfunctions.cpp.
void Convert (const QVImage< uShort, 1 > & qvimage_pSrc, QVImage< uChar, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
This is the QVision wrapper function for IPP's ippiConvert_16u8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 141 of file qvippfunctions.cpp.
void Convert (const QVImage< uShort, 1 > & qvimage_pSrc, QVImage< sInt, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
This is the QVision wrapper function for IPP's ippiConvert_16u32s_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 155 of file qvippfunctions.cpp.
void Convert (const QVImage< uShort, 1 > & qvimage_pSrc, QVImage< sFloat, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
This is the QVision wrapper function for IPP's ippiConvert_16u32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 169 of file qvippfunctions.cpp.
void Convert (const QVImage< uShort, 3 > & qvimage_pSrc, QVImage< uChar, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
This is the QVision wrapper function for IPP's ippiConvert_16u8u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 183 of file qvippfunctions.cpp.
void Convert (const QVImage< uShort, 3 > & qvimage_pSrc, QVImage< sInt, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
This is the QVision wrapper function for IPP's ippiConvert_16u32s_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 197 of file qvippfunctions.cpp.
void Convert (const QVImage< uShort, 3 > & qvimage_pSrc, QVImage< sFloat, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
This is the QVision wrapper function for IPP's ippiConvert_16u32f_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 211 of file qvippfunctions.cpp.
void Convert (const QVImage< sShort, 1 > & qvimage_pSrc, QVImage< uChar, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
This is the QVision wrapper function for IPP's ippiConvert_16s8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 225 of file qvippfunctions.cpp.
void Convert (const QVImage< sShort, 1 > & qvimage_pSrc, QVImage< sInt, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
This is the QVision wrapper function for IPP's ippiConvert_16s32s_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 239 of file qvippfunctions.cpp.
void Convert (const QVImage< sShort, 1 > & qvimage_pSrc, QVImage< sFloat, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
This is the QVision wrapper function for IPP's ippiConvert_16s32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 253 of file qvippfunctions.cpp.
void Convert (const QVImage< sShort, 3 > & qvimage_pSrc, QVImage< uChar, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
This is the QVision wrapper function for IPP's ippiConvert_16s8u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 267 of file qvippfunctions.cpp.
void Convert (const QVImage< sShort, 3 > & qvimage_pSrc, QVImage< sInt, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
This is the QVision wrapper function for IPP's ippiConvert_16s32s_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 281 of file qvippfunctions.cpp.
void Convert (const QVImage< sShort, 3 > & qvimage_pSrc, QVImage< sFloat, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
This is the QVision wrapper function for IPP's ippiConvert_16s32f_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 295 of file qvippfunctions.cpp.
void Convert (const QVImage< sInt, 1 > & qvimage_pSrc, QVImage< uChar, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
This is the QVision wrapper function for IPP's ippiConvert_32s8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 309 of file qvippfunctions.cpp.
void Convert (const QVImage< sInt, 3 > & qvimage_pSrc, QVImage< uChar, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
This is the QVision wrapper function for IPP's ippiConvert_32s8u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 323 of file qvippfunctions.cpp.
void Convert (const QVImage< sFloat, 1 > & qvimage_pSrc, QVImage< uChar, 1 > & qvimage_pDst, const IppRoundMode roundMode = ippRndNear, const QPoint & destROIOffset = QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
This is the QVision wrapper function for IPP's ippiConvert_32f8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
roundMode Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 337 of file qvippfunctions.cpp.
void Convert (const QVImage< sFloat, 1 > & qvimage_pSrc, QVImage< uShort, 1 > & qvimage_pDst, const IppRoundMode roundMode = ippRndNear, const QPoint & destROIOffset = QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
This is the QVision wrapper function for IPP's ippiConvert_32f16u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
roundMode Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 353 of file qvippfunctions.cpp.
void Convert (const QVImage< sFloat, 1 > & qvimage_pSrc, QVImage< sShort, 1 > & qvimage_pDst, const IppRoundMode roundMode = ippRndNear, const QPoint & destROIOffset = QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
This is the QVision wrapper function for IPP's ippiConvert_32f16s_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
roundMode Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 369 of file qvippfunctions.cpp.
void Convert (const QVImage< sFloat, 3 > & qvimage_pSrc, QVImage< uChar, 3 > & qvimage_pDst, const IppRoundMode roundMode = ippRndNear, const QPoint & destROIOffset = QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
This is the QVision wrapper function for IPP's ippiConvert_32f8u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
roundMode Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 385 of file qvippfunctions.cpp.
void Convert (const QVImage< sFloat, 3 > & qvimage_pSrc, QVImage< uShort, 3 > & qvimage_pDst, const IppRoundMode roundMode = ippRndNear, const QPoint & destROIOffset = QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
This is the QVision wrapper function for IPP's ippiConvert_32f16u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
roundMode Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 401 of file qvippfunctions.cpp.
void Convert (const QVImage< sFloat, 3 > & qvimage_pSrc, QVImage< sShort, 3 > & qvimage_pDst, const IppRoundMode roundMode = ippRndNear, const QPoint & destROIOffset = QPoint(0, 0))
Converts pixel values of an image from one bit depth to another.
This is the QVision wrapper function for IPP's ippiConvert_32f16s_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
roundMode Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 417 of file qvippfunctions.cpp.
void Scale (const QVImage< uChar, 1 > & qvimage_pSrc, QVImage< uShort, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Scales pixel values of an image and converts them to another bit depth dst = a + b * src; a = type_min_dst - b * type_min_src; b = (type_max_dst - type_min_dst) (type_max_src - type_min_src).
This is the QVision wrapper function for IPP's ippiScale_8u16u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 433 of file qvippfunctions.cpp.
Referenced by Scale().
void Scale (const QVImage< uChar, 1 > & qvimage_pSrc, QVImage< sShort, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Scales pixel values of an image and converts them to another bit depth dst = a + b * src; a = type_min_dst - b * type_min_src; b = (type_max_dst - type_min_dst) (type_max_src - type_min_src).
This is the QVision wrapper function for IPP's ippiScale_8u16s_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 447 of file qvippfunctions.cpp.
void Scale (const QVImage< uChar, 1 > & qvimage_pSrc, QVImage< sInt, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Scales pixel values of an image and converts them to another bit depth dst = a + b * src; a = type_min_dst - b * type_min_src; b = (type_max_dst - type_min_dst) (type_max_src - type_min_src).
This is the QVision wrapper function for IPP's ippiScale_8u32s_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 461 of file qvippfunctions.cpp.
void Scale (const QVImage< uChar, 3 > & qvimage_pSrc, QVImage< uShort, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Scales pixel values of an image and converts them to another bit depth dst = a + b * src; a = type_min_dst - b * type_min_src; b = (type_max_dst - type_min_dst) (type_max_src - type_min_src).
This is the QVision wrapper function for IPP's ippiScale_8u16u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 475 of file qvippfunctions.cpp.
void Scale (const QVImage< uChar, 3 > & qvimage_pSrc, QVImage< sShort, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Scales pixel values of an image and converts them to another bit depth dst = a + b * src; a = type_min_dst - b * type_min_src; b = (type_max_dst - type_min_dst) (type_max_src - type_min_src).
This is the QVision wrapper function for IPP's ippiScale_8u16s_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 489 of file qvippfunctions.cpp.
void Scale (const QVImage< uChar, 3 > & qvimage_pSrc, QVImage< sInt, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Scales pixel values of an image and converts them to another bit depth dst = a + b * src; a = type_min_dst - b * type_min_src; b = (type_max_dst - type_min_dst) (type_max_src - type_min_src).
This is the QVision wrapper function for IPP's ippiScale_8u32s_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 503 of file qvippfunctions.cpp.
void Set (const uChar value, QVImage< uChar, 1 > & qvimage_pDst)
Sets pixels in the image buffer to a constant value.
This is the QVision wrapper function for IPP's ippiSet_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
Definition at line 517 of file qvippfunctions.cpp.
Referenced by FilterLocalMax(), getConnectedSetBorderContoursThreshold(), QVVideoReaderBlock::QVVideoReaderBlock(), Set(), and writeYUV4MPEG2Frame().
void Set (const uShort value, QVImage< uShort, 1 > & qvimage_pDst)
Sets pixels in the image buffer to a constant value.
This is the QVision wrapper function for IPP's ippiSet_16u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
Definition at line 528 of file qvippfunctions.cpp.
void Set (const sShort value, QVImage< sShort, 1 > & qvimage_pDst)
Sets pixels in the image buffer to a constant value.
This is the QVision wrapper function for IPP's ippiSet_16s_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
Definition at line 539 of file qvippfunctions.cpp.
void Set (const sInt value, QVImage< sInt, 1 > & qvimage_pDst)
Sets pixels in the image buffer to a constant value.
This is the QVision wrapper function for IPP's ippiSet_32s_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
Definition at line 550 of file qvippfunctions.cpp.
void Set (const sFloat value, QVImage< sFloat, 1 > & qvimage_pDst)
Sets pixels in the image buffer to a constant value.
This is the QVision wrapper function for IPP's ippiSet_32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
Definition at line 561 of file qvippfunctions.cpp.
void Set (const uChar value[3], QVImage< uChar, 3 > & qvimage_pDst)
Sets pixels in the image buffer to a constant value.
This is the QVision wrapper function for IPP's ippiSet_8u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
Definition at line 572 of file qvippfunctions.cpp.
void Set (const uShort value[3], QVImage< uShort, 3 > & qvimage_pDst)
Sets pixels in the image buffer to a constant value.
This is the QVision wrapper function for IPP's ippiSet_16u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
Definition at line 583 of file qvippfunctions.cpp.
void Set (const sShort value[3], QVImage< sShort, 3 > & qvimage_pDst)
Sets pixels in the image buffer to a constant value.
This is the QVision wrapper function for IPP's ippiSet_16s_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
Definition at line 594 of file qvippfunctions.cpp.
void Set (const sInt value[3], QVImage< sInt, 3 > & qvimage_pDst)
Sets pixels in the image buffer to a constant value.
This is the QVision wrapper function for IPP's ippiSet_32s_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
Definition at line 605 of file qvippfunctions.cpp.
void Set (const sFloat value[3], QVImage< sFloat, 3 > & qvimage_pDst)
Sets pixels in the image buffer to a constant value.
This is the QVision wrapper function for IPP's ippiSet_32f_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
value Corresponds to the same parameter in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
Definition at line 616 of file qvippfunctions.cpp.
void Copy (const QVImage< uChar, 1 > & qvimage_pSrc, QVImage< uChar, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Copy pixel values from the source image to the destination image.
This is the QVision wrapper function for IPP's ippiCopy_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 627 of file qvippfunctions.cpp.
void Copy (const QVImage< uChar, 3 > & qvimage_pSrc, QVImage< uChar, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Copy pixel values from the source image to the destination image.
This is the QVision wrapper function for IPP's ippiCopy_8u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 641 of file qvippfunctions.cpp.
void Copy (const QVImage< uShort, 1 > & qvimage_pSrc, QVImage< uShort, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Copy pixel values from the source image to the destination image.
This is the QVision wrapper function for IPP's ippiCopy_16u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 655 of file qvippfunctions.cpp.
void Copy (const QVImage< uShort, 3 > & qvimage_pSrc, QVImage< uShort, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Copy pixel values from the source image to the destination image.
This is the QVision wrapper function for IPP's ippiCopy_16u_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 669 of file qvippfunctions.cpp.
void Copy (const QVImage< sShort, 1 > & qvimage_pSrc, QVImage< sShort, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Copy pixel values from the source image to the destination image.
This is the QVision wrapper function for IPP's ippiCopy_16s_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 683 of file qvippfunctions.cpp.
void Copy (const QVImage< sShort, 3 > & qvimage_pSrc, QVImage< sShort, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Copy pixel values from the source image to the destination image.
This is the QVision wrapper function for IPP's ippiCopy_16s_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 697 of file qvippfunctions.cpp.
void Copy (const QVImage< sInt, 1 > & qvimage_pSrc, QVImage< sInt, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Copy pixel values from the source image to the destination image.
This is the QVision wrapper function for IPP's ippiCopy_32s_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 711 of file qvippfunctions.cpp.
void Copy (const QVImage< sInt, 3 > & qvimage_pSrc, QVImage< sInt, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Copy pixel values from the source image to the destination image.
This is the QVision wrapper function for IPP's ippiCopy_32s_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 725 of file qvippfunctions.cpp.
void Copy (const QVImage< sFloat, 1 > & qvimage_pSrc, QVImage< sFloat, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Copy pixel values from the source image to the destination image.
This is the QVision wrapper function for IPP's ippiCopy_32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 739 of file qvippfunctions.cpp.
void Copy (const QVImage< sFloat, 3 > & qvimage_pSrc, QVImage< sFloat, 3 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Copy pixel values from the source image to the destination image.
This is the QVision wrapper function for IPP's ippiCopy_32f_C3R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 753 of file qvippfunctions.cpp.
void AddRandUniform_Direct (QVImage< uChar, 1 > & qvimage_pSrcDst, const uChar low, const uChar high, unsigned int & pSeed)
Generates pseudo-random samples with uniform distribution and adds them to an image.
This is the QVision wrapper function for IPP's ippiAddRandUniform_Direct_8u_C1IR. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrcDst Image corresponding to the data buffer pointer pSrcDst and step number srcDstStep variables in the IPP function
low Corresponds to the same parameter of type IppiSize in the IPP function.
high Corresponds to the same parameter of type IppiSize in the IPP function.
pSeed Corresponds to the same parameter in the IPP function.
Definition at line 767 of file qvippfunctions.cpp.
Referenced by AddRandUniform_Direct().
void AddRandUniform_Direct (QVImage< uShort, 1 > & qvimage_pSrcDst, const uShort low, const uShort high, unsigned int & pSeed)
Generates pseudo-random samples with uniform distribution and adds them to an image.
This is the QVision wrapper function for IPP's ippiAddRandUniform_Direct_16u_C1IR. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrcDst Image corresponding to the data buffer pointer pSrcDst and step number srcDstStep variables in the IPP function
low Corresponds to the same parameter of type IppiSize in the IPP function.
high Corresponds to the same parameter of type IppiSize in the IPP function.
pSeed Corresponds to the same parameter in the IPP function.
Definition at line 782 of file qvippfunctions.cpp.
void AddRandUniform_Direct (QVImage< sShort, 1 > & qvimage_pSrcDst, const sShort low, const sShort high, unsigned int & pSeed)
Generates pseudo-random samples with uniform distribution and adds them to an image.
This is the QVision wrapper function for IPP's ippiAddRandUniform_Direct_16s_C1IR. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrcDst Image corresponding to the data buffer pointer pSrcDst and step number srcDstStep variables in the IPP function
low Corresponds to the same parameter of type IppiSize in the IPP function.
high Corresponds to the same parameter of type IppiSize in the IPP function.
pSeed Corresponds to the same parameter in the IPP function.
Definition at line 797 of file qvippfunctions.cpp.
void AddRandUniform_Direct (QVImage< sFloat, 1 > & qvimage_pSrcDst, const sFloat low, const sFloat high, unsigned int & pSeed)
Generates pseudo-random samples with uniform distribution and adds them to an image.
This is the QVision wrapper function for IPP's ippiAddRandUniform_Direct_32f_C1IR. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrcDst Image corresponding to the data buffer pointer pSrcDst and step number srcDstStep variables in the IPP function
low Corresponds to the same parameter of type IppiSize in the IPP function.
high Corresponds to the same parameter of type IppiSize in the IPP function.
pSeed Corresponds to the same parameter in the IPP function.
Definition at line 812 of file qvippfunctions.cpp.
void AddRandUniform_Direct (QVImage< uChar, 3 > & qvimage_pSrcDst, const uChar low, const uChar high, unsigned int & pSeed)
Generates pseudo-random samples with uniform distribution and adds them to an image.
This is the QVision wrapper function for IPP's ippiAddRandUniform_Direct_8u_C3IR. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrcDst Image corresponding to the data buffer pointer pSrcDst and step number srcDstStep variables in the IPP function
low Corresponds to the same parameter of type IppiSize in the IPP function.
high Corresponds to the same parameter of type IppiSize in the IPP function.
pSeed Corresponds to the same parameter in the IPP function.
Definition at line 827 of file qvippfunctions.cpp.
void AddRandUniform_Direct (QVImage< uShort, 3 > & qvimage_pSrcDst, const uShort low, const uShort high, unsigned int & pSeed)
Generates pseudo-random samples with uniform distribution and adds them to an image.
This is the QVision wrapper function for IPP's ippiAddRandUniform_Direct_16u_C3IR. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrcDst Image corresponding to the data buffer pointer pSrcDst and step number srcDstStep variables in the IPP function
low Corresponds to the same parameter of type IppiSize in the IPP function.
high Corresponds to the same parameter of type IppiSize in the IPP function.
pSeed Corresponds to the same parameter in the IPP function.
Definition at line 842 of file qvippfunctions.cpp.
void AddRandUniform_Direct (QVImage< sShort, 3 > & qvimage_pSrcDst, const sShort low, const sShort high, unsigned int & pSeed)
Generates pseudo-random samples with uniform distribution and adds them to an image.
This is the QVision wrapper function for IPP's ippiAddRandUniform_Direct_16s_C3IR. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrcDst Image corresponding to the data buffer pointer pSrcDst and step number srcDstStep variables in the IPP function
low Corresponds to the same parameter of type IppiSize in the IPP function.
high Corresponds to the same parameter of type IppiSize in the IPP function.
pSeed Corresponds to the same parameter in the IPP function.
Definition at line 857 of file qvippfunctions.cpp.
void AddRandUniform_Direct (QVImage< sFloat, 3 > & qvimage_pSrcDst, const sFloat low, const sFloat high, unsigned int & pSeed)
Generates pseudo-random samples with uniform distribution and adds them to an image.
This is the QVision wrapper function for IPP's ippiAddRandUniform_Direct_32f_C3IR. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrcDst Image corresponding to the data buffer pointer pSrcDst and step number srcDstStep variables in the IPP function
low Corresponds to the same parameter of type IppiSize in the IPP function.
high Corresponds to the same parameter of type IppiSize in the IPP function.
pSeed Corresponds to the same parameter in the IPP function.
Definition at line 872 of file qvippfunctions.cpp.
QVision framework. PARP research group. Copyright © 2007, 2008, 2009, 2010, 2011.