QVision: Qt's Image, Video and Computer Vision Library
PARP Research Group Universidad de Murcia
Threshold and Compare Operations
[IPP wrapper functions]
Image processing functions that operate on a pixel-by-pixel basis: threshold and compare functions.
Functions
void Compare (const QVImage< uShort, 3 > &src1, const QVImage< uShort, 3 > &src2, QVImage< uChar > &dest, IppCmpOp ippCmpOp=ippCmpEq, const QPoint &destROIOffset=QPoint(0, 0))
Compares pixel values of two images using a specified compare operation.
void Compare (const QVImage< sShort, 3 > &src1, const QVImage< sShort, 3 > &src2, QVImage< uChar > &dest, IppCmpOp ippCmpOp=ippCmpEq, const QPoint &destROIOffset=QPoint(0, 0))
Compares pixel values of two images using a specified compare operation.
void Compare (const QVImage< sFloat, 3 > &src1, const QVImage< sFloat, 3 > &src2, QVImage< uChar > &dest, IppCmpOp ippCmpOp=ippCmpEq, const QPoint &destROIOffset=QPoint(0, 0))
Compares pixel values of two images using a specified compare operation.
void Threshold (const QVImage< uChar, 1 > &qvimage_pSrc, QVImage< uChar, 1 > &qvimage_pDst, const uChar threshold, const IppCmpOp ippCmpOp=ippCmpEq, const QPoint &destROIOffset=QPoint(0, 0))
Performs thresholding of an image using the specified level.
void Threshold (QVImage< uChar, 1 > &qvimage_pSrcDst, const uChar threshold, const IppCmpOp ippCmpOp=ippCmpEq)
Performs thresholding of an image using the specified level.
void Threshold (const QVImage< sShort, 1 > &qvimage_pSrc, QVImage< sShort, 1 > &qvimage_pDst, const sShort threshold, const IppCmpOp ippCmpOp=ippCmpEq, const QPoint &destROIOffset=QPoint(0, 0))
Performs thresholding of an image using the specified level.
void Threshold (QVImage< sShort, 1 > &qvimage_pSrcDst, const sShort threshold, const IppCmpOp ippCmpOp=ippCmpEq)
Performs thresholding of an image using the specified level.
void Threshold (const QVImage< sFloat, 1 > &qvimage_pSrc, QVImage< sFloat, 1 > &qvimage_pDst, const sFloat threshold, const IppCmpOp ippCmpOp=ippCmpEq, const QPoint &destROIOffset=QPoint(0, 0))
Performs thresholding of an image using the specified level.
void Threshold (QVImage< sFloat, 1 > &qvimage_pSrcDst, const sFloat threshold, const IppCmpOp ippCmpOp=ippCmpEq)
Performs thresholding of an image using the specified level.
void Threshold_Val (const QVImage< uChar, 1 > &qvimage_pSrc, QVImage< uChar, 1 > &qvimage_pDst, const uChar threshold, const uChar value, const IppCmpOp ippCmpOp=ippCmpEq, const QPoint &destROIOffset=QPoint(0, 0))
Performs thresholding of pixel values.
void Threshold_Val (QVImage< uChar, 1 > &qvimage_pSrcDst, const uChar threshold, const uChar value, const IppCmpOp ippCmpOp=ippCmpEq)
Performs thresholding of pixel values.
void Threshold_Val (QVImage< sShort, 1 > &qvimage_pSrcDst, const sShort threshold, const sShort value, const IppCmpOp ippCmpOp=ippCmpEq)
Performs thresholding of pixel values.
void Threshold_Val (const QVImage< sFloat, 1 > &qvimage_pSrc, QVImage< sFloat, 1 > &qvimage_pDst, const sFloat threshold, const sFloat value, const IppCmpOp ippCmpOp=ippCmpEq, const QPoint &destROIOffset=QPoint(0, 0))
Performs thresholding of pixel values.
void Threshold_Val (QVImage< sFloat, 1 > &qvimage_pSrcDst, const sFloat threshold, const sFloat value, const IppCmpOp ippCmpOp=ippCmpEq)
Performs thresholding of pixel values.
void Threshold_LTValGTVal (const QVImage< uChar, 1 > &qvimage_pSrc, QVImage< uChar, 1 > &qvimage_pDst, const uChar thresholdLT, const uChar valueLT, const uChar thresholdGT, const uChar valueGT, const QPoint &destROIOffset=QPoint(0, 0))
Performs double thresholding of pixel values.
void Threshold_LTValGTVal (const QVImage< sFloat, 1 > &qvimage_pSrc, QVImage< sFloat, 1 > &qvimage_pDst, const sFloat thresholdLT, const sFloat valueLT, const sFloat thresholdGT, const sFloat valueGT, const QPoint &destROIOffset=QPoint(0, 0))
Performs double thresholding of pixel values.
void ComputeThreshold_Otsu (const QVImage< uChar, 1 > &qvimage_pSrc, uChar &pThreshold)
Calculate Otsu theshold value of images.
void Compare (const QVImage< uChar, 1 > &qvimage_pSrc1, const QVImage< uChar, 1 > &qvimage_pSrc2, QVImage< uChar, 1 > &qvimage_pDst, const IppCmpOp ippCmpOp=ippCmpEq, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiCompare_8u_C1R.
void Compare (const QVImage< uShort, 1 > &qvimage_pSrc1, const QVImage< uShort, 1 > &qvimage_pSrc2, QVImage< uChar, 1 > &qvimage_pDst, const IppCmpOp ippCmpOp=ippCmpEq, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiCompare_16u_C1R.
void Compare (const QVImage< sShort, 1 > &qvimage_pSrc1, const QVImage< sShort, 1 > &qvimage_pSrc2, QVImage< uChar, 1 > &qvimage_pDst, const IppCmpOp ippCmpOp=ippCmpEq, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiCompare_16s_C1R.
void Compare (const QVImage< sFloat, 1 > &qvimage_pSrc1, const QVImage< sFloat, 1 > &qvimage_pSrc2, QVImage< uChar, 1 > &qvimage_pDst, const IppCmpOp ippCmpOp=ippCmpEq, const QPoint &destROIOffset=QPoint(0, 0))
QVision wrapper function for IPP's ippiCompare_32f_C1R.
void CompareC (const QVImage< uChar, 1 > &qvimage_pSrc, const uChar value, QVImage< uChar, 1 > &qvimage_pDst, const IppCmpOp ippCmpOp=ippCmpEq, const QPoint &destROIOffset=QPoint(0, 0))
Compares pixel values of two images, or pixel values of an image to a constant value using the following compare conditions.
void CompareC (const QVImage< sFloat, 1 > &qvimage_pSrc, const sFloat value, QVImage< uChar, 1 > &qvimage_pDst, const IppCmpOp ippCmpOp=ippCmpEq, const QPoint &destROIOffset=QPoint(0, 0))
Compares pixel values of two images, or pixel values of an image to a constant value using the following compare conditions.
Detailed Description
Image processing functions that operate on a pixel-by-pixel basis: threshold and compare functions.
Function Documentation
void Compare (const QVImage< uShort, 3 > & src1, const QVImage< uShort, 3 > & src2, QVImage< uChar > & dest, IppCmpOp ippCmpOp = ippCmpEq, const QPoint & destROIOffset = QPoint(0, 0))
Compares pixel values of two images using a specified compare operation.
See also:
void Compare(const QVImage<uChar> &, const QVImage<uChar> &src2, QVImage<uChar> &, IppCmpOp)
void Compare (const QVImage< sShort, 3 > & src1, const QVImage< sShort, 3 > & src2, QVImage< uChar > & dest, IppCmpOp ippCmpOp = ippCmpEq, const QPoint & destROIOffset = QPoint(0, 0))
Compares pixel values of two images using a specified compare operation.
See also:
void Compare(const QVImage<uChar> &, const QVImage<uChar> &src2, QVImage<uChar> &, IppCmpOp)
void Compare (const QVImage< sFloat, 3 > & src1, const QVImage< sFloat, 3 > & src2, QVImage< uChar > & dest, IppCmpOp ippCmpOp = ippCmpEq, const QPoint & destROIOffset = QPoint(0, 0))
Compares pixel values of two images using a specified compare operation.
See also:
void Compare(const QVImage<uChar> &, const QVImage<uChar> &src2, QVImage<uChar> &, IppCmpOp)
void Threshold (const QVImage< uChar, 1 > & qvimage_pSrc, QVImage< uChar, 1 > & qvimage_pDst, const uChar threshold, const IppCmpOp ippCmpOp = ippCmpEq, const QPoint & destROIOffset = QPoint(0, 0))
Performs thresholding of an image using the specified level.
This is the QVision wrapper function for IPP's ippiThreshold_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
threshold Corresponds to the same parameter of type IppiSize in the IPP function.
ippCmpOp Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3048 of file qvippfunctions.cpp.
Referenced by QVThreshold_sFloatC1Block::iterate(), QVThreshold_uCharC1Block::iterate(), and Threshold().
void Threshold (QVImage< uChar, 1 > & qvimage_pSrcDst, const uChar threshold, const IppCmpOp ippCmpOp = ippCmpEq)
Performs thresholding of an image using the specified level.
This is the QVision wrapper function for IPP's ippiThreshold_8u_C1IR. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrcDst Image corresponding to the data buffer pointer pSrcDst and step number srcDstStep variables in the IPP function
threshold Corresponds to the same parameter of type IppiSize in the IPP function.
ippCmpOp Corresponds to the same parameter of type IppiSize in the IPP function.
Definition at line 3066 of file qvippfunctions.cpp.
void Threshold (const QVImage< sShort, 1 > & qvimage_pSrc, QVImage< sShort, 1 > & qvimage_pDst, const sShort threshold, const IppCmpOp ippCmpOp = ippCmpEq, const QPoint & destROIOffset = QPoint(0, 0))
Performs thresholding of an image using the specified level.
This is the QVision wrapper function for IPP's ippiThreshold_16s_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
threshold Corresponds to the same parameter of type IppiSize in the IPP function.
ippCmpOp Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3079 of file qvippfunctions.cpp.
void Threshold (QVImage< sShort, 1 > & qvimage_pSrcDst, const sShort threshold, const IppCmpOp ippCmpOp = ippCmpEq)
Performs thresholding of an image using the specified level.
This is the QVision wrapper function for IPP's ippiThreshold_16s_C1IR. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrcDst Image corresponding to the data buffer pointer pSrcDst and step number srcDstStep variables in the IPP function
threshold Corresponds to the same parameter of type IppiSize in the IPP function.
ippCmpOp Corresponds to the same parameter of type IppiSize in the IPP function.
Definition at line 3097 of file qvippfunctions.cpp.
void Threshold (const QVImage< sFloat, 1 > & qvimage_pSrc, QVImage< sFloat, 1 > & qvimage_pDst, const sFloat threshold, const IppCmpOp ippCmpOp = ippCmpEq, const QPoint & destROIOffset = QPoint(0, 0))
Performs thresholding of an image using the specified level.
This is the QVision wrapper function for IPP's ippiThreshold_32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
threshold Corresponds to the same parameter of type IppiSize in the IPP function.
ippCmpOp Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3110 of file qvippfunctions.cpp.
void Threshold (QVImage< sFloat, 1 > & qvimage_pSrcDst, const sFloat threshold, const IppCmpOp ippCmpOp = ippCmpEq)
Performs thresholding of an image using the specified level.
This is the QVision wrapper function for IPP's ippiThreshold_32f_C1IR. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrcDst Image corresponding to the data buffer pointer pSrcDst and step number srcDstStep variables in the IPP function
threshold Corresponds to the same parameter of type IppiSize in the IPP function.
ippCmpOp Corresponds to the same parameter of type IppiSize in the IPP function.
Definition at line 3128 of file qvippfunctions.cpp.
void Threshold_Val (const QVImage< uChar, 1 > & qvimage_pSrc, QVImage< uChar, 1 > & qvimage_pDst, const uChar threshold, const uChar value, const IppCmpOp ippCmpOp = ippCmpEq, const QPoint & destROIOffset = QPoint(0, 0))
Performs thresholding of pixel values.
This is the QVision wrapper function for IPP's ippiThreshold_Val_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
threshold Corresponds to the same parameter of type IppiSize in the IPP function.
value Corresponds to the same parameter of type IppiSize in the IPP function.
ippCmpOp Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3141 of file qvippfunctions.cpp.
Referenced by Threshold_Val().
void Threshold_Val (QVImage< uChar, 1 > & qvimage_pSrcDst, const uChar threshold, const uChar value, const IppCmpOp ippCmpOp = ippCmpEq)
Performs thresholding of pixel values.
This is the QVision wrapper function for IPP's ippiThreshold_Val_8u_C1IR. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrcDst Image corresponding to the data buffer pointer pSrcDst and step number srcDstStep variables in the IPP function
threshold Corresponds to the same parameter of type IppiSize in the IPP function.
value Corresponds to the same parameter of type IppiSize in the IPP function.
ippCmpOp Corresponds to the same parameter of type IppiSize in the IPP function.
Definition at line 3161 of file qvippfunctions.cpp.
void Threshold_Val (QVImage< sShort, 1 > & qvimage_pSrcDst, const sShort threshold, const sShort value, const IppCmpOp ippCmpOp = ippCmpEq)
Performs thresholding of pixel values.
This is the QVision wrapper function for IPP's ippiThreshold_Val_16s_C1IR. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrcDst Image corresponding to the data buffer pointer pSrcDst and step number srcDstStep variables in the IPP function
threshold Corresponds to the same parameter of type IppiSize in the IPP function.
value Corresponds to the same parameter of type IppiSize in the IPP function.
ippCmpOp Corresponds to the same parameter of type IppiSize in the IPP function.
Definition at line 3176 of file qvippfunctions.cpp.
void Threshold_Val (const QVImage< sFloat, 1 > & qvimage_pSrc, QVImage< sFloat, 1 > & qvimage_pDst, const sFloat threshold, const sFloat value, const IppCmpOp ippCmpOp = ippCmpEq, const QPoint & destROIOffset = QPoint(0, 0))
Performs thresholding of pixel values.
This is the QVision wrapper function for IPP's ippiThreshold_Val_32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
threshold Corresponds to the same parameter of type IppiSize in the IPP function.
value Corresponds to the same parameter of type IppiSize in the IPP function.
ippCmpOp Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3191 of file qvippfunctions.cpp.
void Threshold_Val (QVImage< sFloat, 1 > & qvimage_pSrcDst, const sFloat threshold, const sFloat value, const IppCmpOp ippCmpOp = ippCmpEq)
Performs thresholding of pixel values.
This is the QVision wrapper function for IPP's ippiThreshold_Val_32f_C1IR. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrcDst Image corresponding to the data buffer pointer pSrcDst and step number srcDstStep variables in the IPP function
threshold Corresponds to the same parameter of type IppiSize in the IPP function.
value Corresponds to the same parameter of type IppiSize in the IPP function.
ippCmpOp Corresponds to the same parameter of type IppiSize in the IPP function.
Definition at line 3211 of file qvippfunctions.cpp.
void Threshold_LTValGTVal (const QVImage< uChar, 1 > & qvimage_pSrc, QVImage< uChar, 1 > & qvimage_pDst, const uChar thresholdLT, const uChar valueLT, const uChar thresholdGT, const uChar valueGT, const QPoint & destROIOffset = QPoint(0, 0))
Performs double thresholding of pixel values.
This is the QVision wrapper function for IPP's ippiThreshold_LTValGTVal_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
thresholdLT Corresponds to the same parameter of type IppiSize in the IPP function.
valueLT Corresponds to the same parameter of type IppiSize in the IPP function.
thresholdGT Corresponds to the same parameter of type IppiSize in the IPP function.
valueGT Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3226 of file qvippfunctions.cpp.
Referenced by Threshold_LTValGTVal().
void Threshold_LTValGTVal (const QVImage< sFloat, 1 > & qvimage_pSrc, QVImage< sFloat, 1 > & qvimage_pDst, const sFloat thresholdLT, const sFloat valueLT, const sFloat thresholdGT, const sFloat valueGT, const QPoint & destROIOffset = QPoint(0, 0))
Performs double thresholding of pixel values.
This is the QVision wrapper function for IPP's ippiThreshold_LTValGTVal_32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
thresholdLT Corresponds to the same parameter of type IppiSize in the IPP function.
valueLT Corresponds to the same parameter of type IppiSize in the IPP function.
thresholdGT Corresponds to the same parameter of type IppiSize in the IPP function.
valueGT Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3248 of file qvippfunctions.cpp.
void ComputeThreshold_Otsu (const QVImage< uChar, 1 > & qvimage_pSrc, uChar & pThreshold)
Calculate Otsu theshold value of images.
This is the QVision wrapper function for IPP's ippiComputeThreshold_Otsu_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
pThreshold Corresponds to the same parameter in the IPP function.
Definition at line 3271 of file qvippfunctions.cpp.
Referenced by ComputeThreshold_Otsu(), and QVComputeThreshold_Otsu_uCharC1Block::iterate().
void Compare (const QVImage< uChar, 1 > & qvimage_pSrc1, const QVImage< uChar, 1 > & qvimage_pSrc2, QVImage< uChar, 1 > & qvimage_pDst, const IppCmpOp ippCmpOp = ippCmpEq, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiCompare_8u_C1R.
This is the QVision wrapper function for IPP's ippiCompare_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
ippCmpOp Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3282 of file qvippfunctions.cpp.
void Compare (const QVImage< uShort, 1 > & qvimage_pSrc1, const QVImage< uShort, 1 > & qvimage_pSrc2, QVImage< uChar, 1 > & qvimage_pDst, const IppCmpOp ippCmpOp = ippCmpEq, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiCompare_16u_C1R.
This is the QVision wrapper function for IPP's ippiCompare_16u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
ippCmpOp Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3301 of file qvippfunctions.cpp.
void Compare (const QVImage< sShort, 1 > & qvimage_pSrc1, const QVImage< sShort, 1 > & qvimage_pSrc2, QVImage< uChar, 1 > & qvimage_pDst, const IppCmpOp ippCmpOp = ippCmpEq, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiCompare_16s_C1R.
This is the QVision wrapper function for IPP's ippiCompare_16s_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
ippCmpOp Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3320 of file qvippfunctions.cpp.
void Compare (const QVImage< sFloat, 1 > & qvimage_pSrc1, const QVImage< sFloat, 1 > & qvimage_pSrc2, QVImage< uChar, 1 > & qvimage_pDst, const IppCmpOp ippCmpOp = ippCmpEq, const QPoint & destROIOffset = QPoint(0, 0))
QVision wrapper function for IPP's ippiCompare_32f_C1R.
This is the QVision wrapper function for IPP's ippiCompare_32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc1 Image corresponding to the data buffer pointer pSrc1 and step number src1Step variables in the IPP function
qvimage_pSrc2 Image corresponding to the data buffer pointer pSrc2 and step number src2Step variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
ippCmpOp Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3339 of file qvippfunctions.cpp.
void CompareC (const QVImage< uChar, 1 > & qvimage_pSrc, const uChar value, QVImage< uChar, 1 > & qvimage_pDst, const IppCmpOp ippCmpOp = ippCmpEq, const QPoint & destROIOffset = QPoint(0, 0))
Compares pixel values of two images, or pixel values of an image to a constant value using the following compare conditions.
This is the QVision wrapper function for IPP's ippiCompareC_8u_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
ippCmpOp Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3358 of file qvippfunctions.cpp.
Referenced by CompareC(), QVCompareC_sFloatC1Block::iterate(), and QVCompareC_uCharC1Block::iterate().
void CompareC (const QVImage< sFloat, 1 > & qvimage_pSrc, const sFloat value, QVImage< uChar, 1 > & qvimage_pDst, const IppCmpOp ippCmpOp = ippCmpEq, const QPoint & destROIOffset = QPoint(0, 0))
Compares pixel values of two images, or pixel values of an image to a constant value using the following compare conditions.
This is the QVision wrapper function for IPP's ippiCompareC_32f_C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
value Corresponds to the same parameter of type IppiSize in the IPP function.
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
ippCmpOp Corresponds to the same parameter of type IppiSize in the IPP function.
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3376 of file qvippfunctions.cpp.
QVision framework. PARP research group. Copyright © 2007, 2008, 2009, 2010, 2011.