QVision: Qt's Image, Video and Computer Vision Library
PARP Research Group Universidad de Murcia
Image Geometry Transforms
[IPP wrapper functions]
Functions that perform geometric operations of resizing, rotating, warping and remapping an image.
Functions
void Resize (const QVImage< uChar > &src, QVImage< uChar > &dest, int interpolation=IPPI_INTER_LINEAR)
Changes an image size.This function copies the content of the ROI in the source image, to the ROI of the destination image, adjusting it's original size to make it fit in the destination size It has the effect of resizing the original image, to fit the destination image, if both ROI's hold the whole of their respective images.
void Resize (const QVImage< sFloat > &src, QVImage< sFloat > &dest, int interpolation=IPPI_INTER_LINEAR)
Changes an image size.
void Resize (const QVImage< uShort > &src, QVImage< uShort > &dest, int interpolation=IPPI_INTER_LINEAR)
Changes an image size.
void Resize (const QVImage< uChar, 3 > &src, QVImage< uChar, 3 > &dest, int interpolation=IPPI_INTER_LINEAR)
Changes an image size.
void WarpPerspective (const QVImage< uChar > &src, QVImage< uChar > &dest, const QVMatrix &rectifyingHomography, int interpolation=IPPI_INTER_LINEAR, const QPoint &destROIOffset=QPoint(0, 0))
Performs perspective warping of the source image using the given transform coefficients.
void WarpPerspective (const QVImage< uChar, 3 > &src, QVImage< uChar, 3 > &dest, const QVMatrix &rectifyingHomography, int interpolation=IPPI_INTER_LINEAR, const QPoint &destROIOffset=QPoint(0, 0))
Performs perspective warping of the source image using the given transform coefficients.
Detailed Description
Functions that perform geometric operations of resizing, rotating, warping and remapping an image.
Function Documentation
void Resize (const QVImage< uChar > & src, QVImage< uChar > & dest, int interpolation = IPPI_INTER_LINEAR)
Changes an image size.This function copies the content of the ROI in the source image, to the ROI of the destination image, adjusting it's original size to make it fit in the destination size It has the effect of resizing the original image, to fit the destination image, if both ROI's hold the whole of their respective images.
IPPI_INTER_NN. Nearest neighbor interpolation
IPPI_INTER_LINEAR. Linear interpolation
IPPI_INTER_CUBIC. Cubic interpolation
IPPI_INTER_SUPER. Supersampling interpolation, cannot be applied for image enlarging
IPPI_INTER_LANCZOS. Interpolation with Lanczos window.
Referenced by QVVideoReader::getGrayImage(), getLTMSER(), QVVideoReader::getRGBImage(), QVVideoReader::getYUVImage(), and QVVideoReader::grab().
void Resize (const QVImage< sFloat > & src, QVImage< sFloat > & dest, int interpolation = IPPI_INTER_LINEAR)
Changes an image size.
See also:
Resize(const QVImage<uChar> &, QVImage<uChar> &, int)
void Resize (const QVImage< uShort > & src, QVImage< uShort > & dest, int interpolation = IPPI_INTER_LINEAR)
Changes an image size.
See also:
Resize(const QVImage<uShort> &, QVImage<uShort> &, int)
void Resize (const QVImage< uChar, 3 > & src, QVImage< uChar, 3 > & dest, int interpolation = IPPI_INTER_LINEAR)
Changes an image size.
See also:
Resize(const QVImage<uChar> &, QVImage<uChar> &, int)
void WarpPerspective (const QVImage< uChar > & src, QVImage< uChar > & dest, const QVMatrix & rectifyingHomography, int interpolation = IPPI_INTER_LINEAR, const QPoint & destROIOffset = QPoint(0, 0))
Performs perspective warping of the source image using the given transform coefficients.
Todo:
Document this function
Parameters:
src source image to wrap.
dest destination image to contain wrapped image.
rectifyingHomography homography matrix corresponding to the wrapping.
interpolation interpolation type. Selects the algorithm for interpolate pixel values. Possible values for this parameter are:
IPPI_INTER_NN. Nearest neighbor interpolation
IPPI_INTER_LINEAR. Linear interpolation
IPPI_INTER_CUBIC. Cubic interpolation
Referenced by applyHomography().
void WarpPerspective (const QVImage< uChar, 3 > & src, QVImage< uChar, 3 > & dest, const QVMatrix & rectifyingHomography, int interpolation = IPPI_INTER_LINEAR, const QPoint & destROIOffset = QPoint(0, 0))
Performs perspective warping of the source image using the given transform coefficients.
See also:
WarpPerspective(const QVImage<uChar> &, QVImage<uChar> &, const QVMatrix &, int, QPoint)
QVision framework. PARP research group. Copyright © 2007, 2008, 2009, 2010, 2011.