QVision: Qt's Image, Video and Computer Vision Library
PARP Research Group Universidad de Murcia
Image Color Conversion
[IPP wrapper functions]
Image processing functions that perform different type of image color conversion.
Functions
void YUV420ToRGB (const QVImage< uChar, 1 > &srcY, const QVImage< uChar, 1 > &srcU, const QVImage< uChar, 1 > &srcV, QVImage< uChar, 3 > &destRGB, const QPoint &destROIOffset=QPoint(0, 0))
void RGBToYUV420 (const QVImage< uChar, 3 > &src, QVImage< uChar, 1 > &dst1, QVImage< uChar, 1 > &dst2, QVImage< uChar, 1 > &dst3, const QPoint &destROIOffset=QPoint(0, 0))
void RGBToGray (const QVImage< uChar, 3 > &qvimage_pSrc, QVImage< uChar, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Converts an RGB image to gray scale (fixed coefficients).
void RGBToGray (const QVImage< uShort, 3 > &qvimage_pSrc, QVImage< uShort, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Converts an RGB image to gray scale (fixed coefficients).
void RGBToGray (const QVImage< sShort, 3 > &qvimage_pSrc, QVImage< sShort, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Converts an RGB image to gray scale (fixed coefficients).
void RGBToGray (const QVImage< sFloat, 3 > &qvimage_pSrc, QVImage< sFloat, 1 > &qvimage_pDst, const QPoint &destROIOffset=QPoint(0, 0))
Converts an RGB image to gray scale (fixed coefficients).
Detailed Description
Image processing functions that perform different type of image color conversion.
Function Documentation
void YUV420ToRGB (const QVImage< uChar, 1 > & src1, const QVImage< uChar, 1 > & src2, const QVImage< uChar, 1 > & src3, QVImage< uChar, 3 > & dest, const QPoint & destROIOffset)
Todo:
document this
Todo:
Comprobar que los tamaños de las imagenes de entrada y de salida son adecuados
Definition at line 163 of file qvipp.cpp.
Referenced by QVVideoReader::getRGBImage().
void RGBToYUV420 (const QVImage< uChar, 3 > & src, QVImage< uChar, 1 > & dst1, QVImage< uChar, 1 > & dst2, QVImage< uChar, 1 > & dst3, const QPoint & destROIOffset)
Todo:
document this
Todo:
Comprobar que los tamaños de las imagenes de entrada y de salida son adecuados
Definition at line 178 of file qvipp.cpp.
Referenced by QVVideoReader::getYUVImage(), and writeYUV4MPEG2Frame().
void RGBToGray (const QVImage< uChar, 3 > & qvimage_pSrc, QVImage< uChar, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Converts an RGB image to gray scale (fixed coefficients).
This is the QVision wrapper function for IPP's ippiRGBToGray_8u_C3C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 2992 of file qvippfunctions.cpp.
void RGBToGray (const QVImage< uShort, 3 > & qvimage_pSrc, QVImage< uShort, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Converts an RGB image to gray scale (fixed coefficients).
This is the QVision wrapper function for IPP's ippiRGBToGray_16u_C3C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3006 of file qvippfunctions.cpp.
void RGBToGray (const QVImage< sShort, 3 > & qvimage_pSrc, QVImage< sShort, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Converts an RGB image to gray scale (fixed coefficients).
This is the QVision wrapper function for IPP's ippiRGBToGray_16s_C3C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3020 of file qvippfunctions.cpp.
void RGBToGray (const QVImage< sFloat, 3 > & qvimage_pSrc, QVImage< sFloat, 1 > & qvimage_pDst, const QPoint & destROIOffset = QPoint(0, 0))
Converts an RGB image to gray scale (fixed coefficients).
This is the QVision wrapper function for IPP's ippiRGBToGray_32f_C3C1R. See Intel's IPP documentation for a deeper understanding of that function. The parameters of this wrapper function are the following:
Parameters:
qvimage_pSrc Image corresponding to the data buffer pointer pSrc and step number srcStep variables in the IPP function
qvimage_pDst Image corresponding to the data buffer pointer pDst and step number dstStep variables in the IPP function
destROIOffset Pointer to destination ROI. See section Destination ROI pointer for more info about this parameter.
Definition at line 3034 of file qvippfunctions.cpp.
QVision framework. PARP research group. Copyright © 2007, 2008, 2009, 2010, 2011.