QVision: Qt's Image, Video and Computer Vision Library
PARP Research Group Universidad de Murcia
IPP wrapper functions
[Image processing]
Comprehensive set of wrapper functions for Intel(R) Integrated Performance Primitives (IPP).
Modules
Image Data Exchange and Initialization Functions
Image processing functions that perform image data manipulation, exchange and initialization operations.
Image Arithmetic and Logical Operations
Image processing functions that modify pixel values of an image using arithmetic or logical operations, and functions that perform image compositing based on opacity (alpha-blending).
Image Color Conversion
Image processing functions that perform different type of image color conversion.
Threshold and Compare Operations
Image processing functions that operate on a pixel-by-pixel basis: threshold and compare functions.
Morphological Operation
Image processing functions that perform morphological operations on images.
Filtering Functions
Image processing functions that perform linear and non-linear filtering operations on an image.
Image Linear Transforms
Functions that perform linear transform operations on an image.
Image Statistics Functions
Functions that can be used to compute the following statistical parameters of an image.
Image Geometry Transforms
Functions that perform geometric operations of resizing, rotating, warping and remapping an image.
Wavelet Transforms
Two-dimensional Discrete Wavelet Transform (DWT) functions implemented in the Intel IPP for image processing.
Computer Vision
Functions for computer vision.
Functions
void FilterHarrisCornerResponseImage (const QVImage< uChar > &image, QVImage< sFloat > &result, int aperture=3, int avgwindow=5, const QPoint &destROIOffset=QPoint(0, 0))
Obtains the Harris corner response image.
void FilterDoG (const QVImage< uChar > &image, QVImage< uChar > &result)
Obtains the DoG corner response image.
void SobelCornerResponseImage (const QVImage< sFloat > &image, QVImage< sFloat > &result)
Obtains the Sobel corner response image.
void FilterHessianCornerResponseImage (const QVImage< sFloat > &image, QVImage< sFloat > &result, const QPoint &destROIOffset=QPoint(0, 0))
Obtains the Hessian corner response image.
void FilterSeparable (const QVImage< sFloat, 1 > &image, QVImage< sFloat, 1 > &dest, const QVVector &rowFilter, const QVVector &colFilter, const QPoint &destROIOffset=QPoint(0, 0))
Applies a separable filter.
QMap< sFloat, QPointF > fastMaximalPoints (const QVImage< sFloat > &image, const double threshold=1.0, const int windowSize=2)
Finds luminance peaks in the input image.
QMap< uChar, QPointF > fastMaximalPoints (const QVImage< uChar > &image, const double threshold, const int windowRadius=2)
Finds luminance peaks in the input image This is an overloaded version provided for convenience. Processing 8 bit depth images is faster than doing it on 64 floating images.
QMap< sInt, int > HistogramRange (const QVImage< uChar, 1 > &src, QList< uChar > values)
Calculates frequency histogram for a given set of values, for a QVImageThis function computes the intensity histogram of an image in the ranges specified by the QList 'values'. Default value for this QList is empty list, indicating the set of integer which cover the group of valid values for uChar type (from 0 to 255).
QVector< int > HistogramRange (const QVImage< uChar, 1 > &src)
Calculates frequency histogram for a given set of values, for a QVImageThis function computes the intensity histogram of an image in the ranges from 0 to 255.
Detailed Description
Comprehensive set of wrapper functions for Intel(R) Integrated Performance Primitives (IPP).
This package provides a set of wrapper functions for the Intel's Performance Primitives library. Each of these functions has an usage and functionality equivalent to that of one of the functions of the IPP library. The IPP wrapper functions function offers an easier to use object oriented interface, defining QVImage objects as parameters instead of raw pointers to the data buffer of the images, and substituting other struct data type parameters like points, or sizes, with references to objects, like QPoint and QSize objects.
The naming convention for those wrapper functions is simpler, avoiding the need of specifying IPP names suffixes, which previously indicated the type and channel number of the input images.
For further details about the usage of these wrapper functions, see section AdvancedImageProcessing in the manual.
Function Documentation
void FilterHarrisCornerResponseImage (const QVImage< uChar > & image, QVImage< sFloat > & result, int aperture = 3, int avgwindow = 5, const QPoint & destROIOffset = QPoint(0, 0))
Obtains the Harris corner response image.
Note:
This function is based on the IPP library functionality. Thus it requires that library, to be available.
Todo:
document this
Definition at line 255 of file qvip.cpp.
void FilterDoG (const QVImage< uChar > & image, QVImage< uChar > & result)
Obtains the DoG corner response image.
Note:
This function is based on the IPP library functionality. Thus it requires that library, to be available.
Todo:
document this
Definition at line 263 of file qvip.cpp.
void SobelCornerResponseImage (const QVImage< sFloat > & image, QVImage< sFloat > & result)
Obtains the Sobel corner response image.
Note:
This function is based on the IPP library functionality. Thus it requires that library, to be available.
Todo:
document this
Definition at line 277 of file qvip.cpp.
void FilterHessianCornerResponseImage (const QVImage< sFloat > & image, QVImage< sFloat > & result, const QPoint & destROIOffset = QPoint(0, 0))
Obtains the Hessian corner response image.
Note:
This function is based on the IPP library functionality. Thus it requires that library, to be available.
Todo:
document this
Definition at line 283 of file qvip.cpp.
Referenced by SobelCornerResponseImage().
void FilterSeparable (const QVImage< sFloat, 1 > & image, QVImage< sFloat, 1 > & dest, const QVVector & rowFilter, const QVVector & colFilter, const QPoint & destROIOffset = QPoint(0, 0))
Applies a separable filter.
Note:
This function is based on the IPP library functionality. Thus it requires that library, to be available.
This function also requires GSL compatibility. This will not be necessary in the future.
Todo:
document this
Definition at line 303 of file qvip.cpp.
QMap<sFloat, QPointF> fastMaximalPoints (const QVImage< sFloat > & image, const double threshold = 1.0, const int windowSize = 2)
Finds luminance peaks in the input image.
Todo:
document this
See also:
fastMaximalPoints(const QVImage<uChar> &, const double, const int)
Definition at line 313 of file qvip.cpp.
QMap<uChar, QPointF> fastMaximalPoints (const QVImage< uChar > & image, const double threshold, const int windowRadius = 2)
Finds luminance peaks in the input image This is an overloaded version provided for convenience. Processing 8 bit depth images is faster than doing it on 64 floating images.
Pixels with a maximal luminance value inside a search window centered at them will be considered peaks. The search algorithm filters low response peaks with a threshold value to improve the performance time.
Parameters:
image Image to detect luminance peaks.
threshold Threshold used to filter out low luminance value peaks.
windowRadius Radius for the search window.
See also:
maximalPoints(const QVImage<sFloat> &, const double, const int)
fastMaximalPoints(const QVImage<sFloat> &, const double, const int)
Definition at line 335 of file qvip.cpp.
QMap<sInt, int> HistogramRange (const QVImage< uChar, 1 > & src, QList< uChar > values)
Calculates frequency histogram for a given set of values, for a QVImageThis function computes the intensity histogram of an image in the ranges specified by the QList 'values'. Default value for this QList is empty list, indicating the set of integer which cover the group of valid values for uChar type (from 0 to 255).
Todo:
fill pLevels array with values from QList 'values'
Parameters:
src source image to obtain histogram values.
values list of QVImage data type values, to obtain frequency in histogram.
Returns:
a QMap variable, that maps pixel values, with their frequency of depicting in the image.
Definition at line 270 of file qvipp.cpp.
QVector<int> HistogramRange (const QVImage< uChar, 1 > & src)
Calculates frequency histogram for a given set of values, for a QVImageThis function computes the intensity histogram of an image in the ranges from 0 to 255.
Parameters:
src source image to obtain histogram values.
Returns:
a QVector list of 256 integer values, that maps pixel values, with their frequency of apperance in the image.
Definition at line 247 of file qvipp.cpp.
Referenced by CountingSort(), getLTMSER(), and HistogramRange().
QVision framework. PARP research group. Copyright © 2007, 2008, 2009, 2010, 2011.